
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Credit: 'Credit',
  Genre: 'Genre',
  Movie: 'Movie',
  Person: 'Person',
  Review: 'Review',
  User: 'User',
  WatchlistEntry: 'WatchlistEntry',
  OneTimeToken: 'OneTimeToken',
  Role: 'Role',
  Permission: 'Permission',
  Seeder: 'Seeder',
  File: 'File'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const CreditScalarFieldEnum = {
  id: 'id',
  role: 'role',
  character: 'character',
  billingOrder: 'billingOrder',
  movieId: 'movieId',
  personId: 'personId',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt',
  createdById: 'createdById'
} as const

export type CreditScalarFieldEnum = (typeof CreditScalarFieldEnum)[keyof typeof CreditScalarFieldEnum]


export const GenreScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt',
  createdById: 'createdById'
} as const

export type GenreScalarFieldEnum = (typeof GenreScalarFieldEnum)[keyof typeof GenreScalarFieldEnum]


export const MovieScalarFieldEnum = {
  id: 'id',
  title: 'title',
  slug: 'slug',
  originalTitle: 'originalTitle',
  tagline: 'tagline',
  overview: 'overview',
  status: 'status',
  releaseDate: 'releaseDate',
  runtimeMinutes: 'runtimeMinutes',
  language: 'language',
  budgetUsd: 'budgetUsd',
  revenueUsd: 'revenueUsd',
  keywords: 'keywords',
  rating: 'rating',
  ratingCount: 'ratingCount',
  trendingScore: 'trendingScore',
  posterId: 'posterId',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt',
  createdById: 'createdById'
} as const

export type MovieScalarFieldEnum = (typeof MovieScalarFieldEnum)[keyof typeof MovieScalarFieldEnum]


export const PersonScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  knownFor: 'knownFor',
  birthDate: 'birthDate',
  deathDate: 'deathDate',
  birthPlace: 'birthPlace',
  biography: 'biography',
  photoId: 'photoId',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt',
  createdById: 'createdById'
} as const

export type PersonScalarFieldEnum = (typeof PersonScalarFieldEnum)[keyof typeof PersonScalarFieldEnum]


export const ReviewScalarFieldEnum = {
  id: 'id',
  rating: 'rating',
  title: 'title',
  body: 'body',
  containsSpoilers: 'containsSpoilers',
  authorName: 'authorName',
  movieId: 'movieId',
  authorId: 'authorId',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt',
  createdById: 'createdById'
} as const

export type ReviewScalarFieldEnum = (typeof ReviewScalarFieldEnum)[keyof typeof ReviewScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  displayName: 'displayName',
  email: 'email',
  bio: 'bio',
  passwordHash: 'passwordHash',
  verifiedEmail: 'verifiedEmail',
  twoFactorAuth: 'twoFactorAuth',
  enabled: 'enabled',
  logoutAt: 'logoutAt',
  avatarId: 'avatarId',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt',
  createdById: 'createdById'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const WatchlistEntryScalarFieldEnum = {
  id: 'id',
  status: 'status',
  watchedAt: 'watchedAt',
  notes: 'notes',
  userId: 'userId',
  movieId: 'movieId',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt',
  createdById: 'createdById'
} as const

export type WatchlistEntryScalarFieldEnum = (typeof WatchlistEntryScalarFieldEnum)[keyof typeof WatchlistEntryScalarFieldEnum]


export const OneTimeTokenScalarFieldEnum = {
  id: 'id',
  tokenHash: 'tokenHash',
  purpose: 'purpose',
  data: 'data',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
} as const

export type OneTimeTokenScalarFieldEnum = (typeof OneTimeTokenScalarFieldEnum)[keyof typeof OneTimeTokenScalarFieldEnum]


export const RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt',
  createdById: 'createdById'
} as const

export type RoleScalarFieldEnum = (typeof RoleScalarFieldEnum)[keyof typeof RoleScalarFieldEnum]


export const PermissionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt',
  createdById: 'createdById'
} as const

export type PermissionScalarFieldEnum = (typeof PermissionScalarFieldEnum)[keyof typeof PermissionScalarFieldEnum]


export const SeederScalarFieldEnum = {
  id: 'id',
  checksum: 'checksum',
  seederName: 'seederName',
  startedAt: 'startedAt',
  finishedAt: 'finishedAt',
  logs: 'logs'
} as const

export type SeederScalarFieldEnum = (typeof SeederScalarFieldEnum)[keyof typeof SeederScalarFieldEnum]


export const FileScalarFieldEnum = {
  id: 'id',
  name: 'name',
  originalName: 'originalName',
  mimeType: 'mimeType',
  sizeBytes: 'sizeBytes',
  checksum: 'checksum',
  title: 'title',
  description: 'description',
  resourceField: 'resourceField',
  resourceName: 'resourceName',
  resourceId: 'resourceId',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt',
  createdById: 'createdById',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById'
} as const

export type FileScalarFieldEnum = (typeof FileScalarFieldEnum)[keyof typeof FileScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]

