
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CannedResponse` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CannedResponse
 * 
 */
export type CannedResponseModel = runtime.Types.Result.DefaultSelection<Prisma.$CannedResponsePayload>

export type AggregateCannedResponse = {
  _count: CannedResponseCountAggregateOutputType | null
  _avg: CannedResponseAvgAggregateOutputType | null
  _sum: CannedResponseSumAggregateOutputType | null
  _min: CannedResponseMinAggregateOutputType | null
  _max: CannedResponseMaxAggregateOutputType | null
}

export type CannedResponseAvgAggregateOutputType = {
  id: number | null
  teamId: number | null
  createdById: number | null
}

export type CannedResponseSumAggregateOutputType = {
  id: number | null
  teamId: number | null
  createdById: number | null
}

export type CannedResponseMinAggregateOutputType = {
  id: number | null
  title: string | null
  body: string | null
  teamId: number | null
  updatedAt: Date | null
  createdAt: Date | null
  createdById: number | null
}

export type CannedResponseMaxAggregateOutputType = {
  id: number | null
  title: string | null
  body: string | null
  teamId: number | null
  updatedAt: Date | null
  createdAt: Date | null
  createdById: number | null
}

export type CannedResponseCountAggregateOutputType = {
  id: number
  title: number
  body: number
  teamId: number
  updatedAt: number
  createdAt: number
  createdById: number
  _all: number
}


export type CannedResponseAvgAggregateInputType = {
  id?: true
  teamId?: true
  createdById?: true
}

export type CannedResponseSumAggregateInputType = {
  id?: true
  teamId?: true
  createdById?: true
}

export type CannedResponseMinAggregateInputType = {
  id?: true
  title?: true
  body?: true
  teamId?: true
  updatedAt?: true
  createdAt?: true
  createdById?: true
}

export type CannedResponseMaxAggregateInputType = {
  id?: true
  title?: true
  body?: true
  teamId?: true
  updatedAt?: true
  createdAt?: true
  createdById?: true
}

export type CannedResponseCountAggregateInputType = {
  id?: true
  title?: true
  body?: true
  teamId?: true
  updatedAt?: true
  createdAt?: true
  createdById?: true
  _all?: true
}

export type CannedResponseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CannedResponse to aggregate.
   */
  where?: Prisma.CannedResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CannedResponses to fetch.
   */
  orderBy?: Prisma.CannedResponseOrderByWithRelationInput | Prisma.CannedResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CannedResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CannedResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CannedResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CannedResponses
  **/
  _count?: true | CannedResponseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CannedResponseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CannedResponseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CannedResponseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CannedResponseMaxAggregateInputType
}

export type GetCannedResponseAggregateType<T extends CannedResponseAggregateArgs> = {
      [P in keyof T & keyof AggregateCannedResponse]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCannedResponse[P]>
    : Prisma.GetScalarType<T[P], AggregateCannedResponse[P]>
}




export type CannedResponseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CannedResponseWhereInput
  orderBy?: Prisma.CannedResponseOrderByWithAggregationInput | Prisma.CannedResponseOrderByWithAggregationInput[]
  by: Prisma.CannedResponseScalarFieldEnum[] | Prisma.CannedResponseScalarFieldEnum
  having?: Prisma.CannedResponseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CannedResponseCountAggregateInputType | true
  _avg?: CannedResponseAvgAggregateInputType
  _sum?: CannedResponseSumAggregateInputType
  _min?: CannedResponseMinAggregateInputType
  _max?: CannedResponseMaxAggregateInputType
}

export type CannedResponseGroupByOutputType = {
  id: number
  title: string
  body: string
  teamId: number | null
  updatedAt: Date
  createdAt: Date
  createdById: number | null
  _count: CannedResponseCountAggregateOutputType | null
  _avg: CannedResponseAvgAggregateOutputType | null
  _sum: CannedResponseSumAggregateOutputType | null
  _min: CannedResponseMinAggregateOutputType | null
  _max: CannedResponseMaxAggregateOutputType | null
}

export type GetCannedResponseGroupByPayload<T extends CannedResponseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CannedResponseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CannedResponseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CannedResponseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CannedResponseGroupByOutputType[P]>
      }
    >
  >



export type CannedResponseWhereInput = {
  AND?: Prisma.CannedResponseWhereInput | Prisma.CannedResponseWhereInput[]
  OR?: Prisma.CannedResponseWhereInput[]
  NOT?: Prisma.CannedResponseWhereInput | Prisma.CannedResponseWhereInput[]
  id?: Prisma.IntFilter<"CannedResponse"> | number
  title?: Prisma.StringFilter<"CannedResponse"> | string
  body?: Prisma.StringFilter<"CannedResponse"> | string
  teamId?: Prisma.IntNullableFilter<"CannedResponse"> | number | null
  updatedAt?: Prisma.DateTimeFilter<"CannedResponse"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"CannedResponse"> | Date | string
  createdById?: Prisma.IntNullableFilter<"CannedResponse"> | number | null
  team?: Prisma.XOR<Prisma.TeamNullableScalarRelationFilter, Prisma.TeamWhereInput> | null
  createdBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type CannedResponseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  body?: Prisma.SortOrder
  teamId?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrderInput | Prisma.SortOrder
  team?: Prisma.TeamOrderByWithRelationInput
  createdBy?: Prisma.UserOrderByWithRelationInput
  _relevance?: Prisma.CannedResponseOrderByRelevanceInput
}

export type CannedResponseWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.CannedResponseWhereInput | Prisma.CannedResponseWhereInput[]
  OR?: Prisma.CannedResponseWhereInput[]
  NOT?: Prisma.CannedResponseWhereInput | Prisma.CannedResponseWhereInput[]
  title?: Prisma.StringFilter<"CannedResponse"> | string
  body?: Prisma.StringFilter<"CannedResponse"> | string
  teamId?: Prisma.IntNullableFilter<"CannedResponse"> | number | null
  updatedAt?: Prisma.DateTimeFilter<"CannedResponse"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"CannedResponse"> | Date | string
  createdById?: Prisma.IntNullableFilter<"CannedResponse"> | number | null
  team?: Prisma.XOR<Prisma.TeamNullableScalarRelationFilter, Prisma.TeamWhereInput> | null
  createdBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type CannedResponseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  body?: Prisma.SortOrder
  teamId?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.CannedResponseCountOrderByAggregateInput
  _avg?: Prisma.CannedResponseAvgOrderByAggregateInput
  _max?: Prisma.CannedResponseMaxOrderByAggregateInput
  _min?: Prisma.CannedResponseMinOrderByAggregateInput
  _sum?: Prisma.CannedResponseSumOrderByAggregateInput
}

export type CannedResponseScalarWhereWithAggregatesInput = {
  AND?: Prisma.CannedResponseScalarWhereWithAggregatesInput | Prisma.CannedResponseScalarWhereWithAggregatesInput[]
  OR?: Prisma.CannedResponseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CannedResponseScalarWhereWithAggregatesInput | Prisma.CannedResponseScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"CannedResponse"> | number
  title?: Prisma.StringWithAggregatesFilter<"CannedResponse"> | string
  body?: Prisma.StringWithAggregatesFilter<"CannedResponse"> | string
  teamId?: Prisma.IntNullableWithAggregatesFilter<"CannedResponse"> | number | null
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CannedResponse"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CannedResponse"> | Date | string
  createdById?: Prisma.IntNullableWithAggregatesFilter<"CannedResponse"> | number | null
}

export type CannedResponseCreateInput = {
  title: string
  body: string
  updatedAt?: Date | string
  createdAt?: Date | string
  team?: Prisma.TeamCreateNestedOneWithoutCannedResponsesInput
  createdBy?: Prisma.UserCreateNestedOneWithoutCreatedCannedResponsesInput
}

export type CannedResponseUncheckedCreateInput = {
  id?: number
  title: string
  body: string
  teamId?: number | null
  updatedAt?: Date | string
  createdAt?: Date | string
  createdById?: number | null
}

export type CannedResponseUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  team?: Prisma.TeamUpdateOneWithoutCannedResponsesNestedInput
  createdBy?: Prisma.UserUpdateOneWithoutCreatedCannedResponsesNestedInput
}

export type CannedResponseUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type CannedResponseCreateManyInput = {
  id?: number
  title: string
  body: string
  teamId?: number | null
  updatedAt?: Date | string
  createdAt?: Date | string
  createdById?: number | null
}

export type CannedResponseUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CannedResponseUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type CannedResponseOrderByRelevanceInput = {
  fields: Prisma.CannedResponseOrderByRelevanceFieldEnum | Prisma.CannedResponseOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type CannedResponseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  body?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type CannedResponseAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type CannedResponseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  body?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type CannedResponseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  body?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type CannedResponseSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type CannedResponseListRelationFilter = {
  every?: Prisma.CannedResponseWhereInput
  some?: Prisma.CannedResponseWhereInput
  none?: Prisma.CannedResponseWhereInput
}

export type CannedResponseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type CannedResponseCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.CannedResponseCreateWithoutTeamInput, Prisma.CannedResponseUncheckedCreateWithoutTeamInput> | Prisma.CannedResponseCreateWithoutTeamInput[] | Prisma.CannedResponseUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.CannedResponseCreateOrConnectWithoutTeamInput | Prisma.CannedResponseCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.CannedResponseCreateManyTeamInputEnvelope
  connect?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
}

export type CannedResponseUncheckedCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.CannedResponseCreateWithoutTeamInput, Prisma.CannedResponseUncheckedCreateWithoutTeamInput> | Prisma.CannedResponseCreateWithoutTeamInput[] | Prisma.CannedResponseUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.CannedResponseCreateOrConnectWithoutTeamInput | Prisma.CannedResponseCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.CannedResponseCreateManyTeamInputEnvelope
  connect?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
}

export type CannedResponseUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.CannedResponseCreateWithoutTeamInput, Prisma.CannedResponseUncheckedCreateWithoutTeamInput> | Prisma.CannedResponseCreateWithoutTeamInput[] | Prisma.CannedResponseUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.CannedResponseCreateOrConnectWithoutTeamInput | Prisma.CannedResponseCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.CannedResponseUpsertWithWhereUniqueWithoutTeamInput | Prisma.CannedResponseUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.CannedResponseCreateManyTeamInputEnvelope
  set?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
  disconnect?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
  delete?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
  connect?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
  update?: Prisma.CannedResponseUpdateWithWhereUniqueWithoutTeamInput | Prisma.CannedResponseUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.CannedResponseUpdateManyWithWhereWithoutTeamInput | Prisma.CannedResponseUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.CannedResponseScalarWhereInput | Prisma.CannedResponseScalarWhereInput[]
}

export type CannedResponseUncheckedUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.CannedResponseCreateWithoutTeamInput, Prisma.CannedResponseUncheckedCreateWithoutTeamInput> | Prisma.CannedResponseCreateWithoutTeamInput[] | Prisma.CannedResponseUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.CannedResponseCreateOrConnectWithoutTeamInput | Prisma.CannedResponseCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.CannedResponseUpsertWithWhereUniqueWithoutTeamInput | Prisma.CannedResponseUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.CannedResponseCreateManyTeamInputEnvelope
  set?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
  disconnect?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
  delete?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
  connect?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
  update?: Prisma.CannedResponseUpdateWithWhereUniqueWithoutTeamInput | Prisma.CannedResponseUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.CannedResponseUpdateManyWithWhereWithoutTeamInput | Prisma.CannedResponseUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.CannedResponseScalarWhereInput | Prisma.CannedResponseScalarWhereInput[]
}

export type CannedResponseCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.CannedResponseCreateWithoutCreatedByInput, Prisma.CannedResponseUncheckedCreateWithoutCreatedByInput> | Prisma.CannedResponseCreateWithoutCreatedByInput[] | Prisma.CannedResponseUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.CannedResponseCreateOrConnectWithoutCreatedByInput | Prisma.CannedResponseCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.CannedResponseCreateManyCreatedByInputEnvelope
  connect?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
}

export type CannedResponseUncheckedCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.CannedResponseCreateWithoutCreatedByInput, Prisma.CannedResponseUncheckedCreateWithoutCreatedByInput> | Prisma.CannedResponseCreateWithoutCreatedByInput[] | Prisma.CannedResponseUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.CannedResponseCreateOrConnectWithoutCreatedByInput | Prisma.CannedResponseCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.CannedResponseCreateManyCreatedByInputEnvelope
  connect?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
}

export type CannedResponseUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.CannedResponseCreateWithoutCreatedByInput, Prisma.CannedResponseUncheckedCreateWithoutCreatedByInput> | Prisma.CannedResponseCreateWithoutCreatedByInput[] | Prisma.CannedResponseUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.CannedResponseCreateOrConnectWithoutCreatedByInput | Prisma.CannedResponseCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.CannedResponseUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.CannedResponseUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.CannedResponseCreateManyCreatedByInputEnvelope
  set?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
  disconnect?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
  delete?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
  connect?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
  update?: Prisma.CannedResponseUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.CannedResponseUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.CannedResponseUpdateManyWithWhereWithoutCreatedByInput | Prisma.CannedResponseUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.CannedResponseScalarWhereInput | Prisma.CannedResponseScalarWhereInput[]
}

export type CannedResponseUncheckedUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.CannedResponseCreateWithoutCreatedByInput, Prisma.CannedResponseUncheckedCreateWithoutCreatedByInput> | Prisma.CannedResponseCreateWithoutCreatedByInput[] | Prisma.CannedResponseUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.CannedResponseCreateOrConnectWithoutCreatedByInput | Prisma.CannedResponseCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.CannedResponseUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.CannedResponseUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.CannedResponseCreateManyCreatedByInputEnvelope
  set?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
  disconnect?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
  delete?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
  connect?: Prisma.CannedResponseWhereUniqueInput | Prisma.CannedResponseWhereUniqueInput[]
  update?: Prisma.CannedResponseUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.CannedResponseUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.CannedResponseUpdateManyWithWhereWithoutCreatedByInput | Prisma.CannedResponseUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.CannedResponseScalarWhereInput | Prisma.CannedResponseScalarWhereInput[]
}

export type CannedResponseCreateWithoutTeamInput = {
  title: string
  body: string
  updatedAt?: Date | string
  createdAt?: Date | string
  createdBy?: Prisma.UserCreateNestedOneWithoutCreatedCannedResponsesInput
}

export type CannedResponseUncheckedCreateWithoutTeamInput = {
  id?: number
  title: string
  body: string
  updatedAt?: Date | string
  createdAt?: Date | string
  createdById?: number | null
}

export type CannedResponseCreateOrConnectWithoutTeamInput = {
  where: Prisma.CannedResponseWhereUniqueInput
  create: Prisma.XOR<Prisma.CannedResponseCreateWithoutTeamInput, Prisma.CannedResponseUncheckedCreateWithoutTeamInput>
}

export type CannedResponseCreateManyTeamInputEnvelope = {
  data: Prisma.CannedResponseCreateManyTeamInput | Prisma.CannedResponseCreateManyTeamInput[]
  skipDuplicates?: boolean
}

export type CannedResponseUpsertWithWhereUniqueWithoutTeamInput = {
  where: Prisma.CannedResponseWhereUniqueInput
  update: Prisma.XOR<Prisma.CannedResponseUpdateWithoutTeamInput, Prisma.CannedResponseUncheckedUpdateWithoutTeamInput>
  create: Prisma.XOR<Prisma.CannedResponseCreateWithoutTeamInput, Prisma.CannedResponseUncheckedCreateWithoutTeamInput>
}

export type CannedResponseUpdateWithWhereUniqueWithoutTeamInput = {
  where: Prisma.CannedResponseWhereUniqueInput
  data: Prisma.XOR<Prisma.CannedResponseUpdateWithoutTeamInput, Prisma.CannedResponseUncheckedUpdateWithoutTeamInput>
}

export type CannedResponseUpdateManyWithWhereWithoutTeamInput = {
  where: Prisma.CannedResponseScalarWhereInput
  data: Prisma.XOR<Prisma.CannedResponseUpdateManyMutationInput, Prisma.CannedResponseUncheckedUpdateManyWithoutTeamInput>
}

export type CannedResponseScalarWhereInput = {
  AND?: Prisma.CannedResponseScalarWhereInput | Prisma.CannedResponseScalarWhereInput[]
  OR?: Prisma.CannedResponseScalarWhereInput[]
  NOT?: Prisma.CannedResponseScalarWhereInput | Prisma.CannedResponseScalarWhereInput[]
  id?: Prisma.IntFilter<"CannedResponse"> | number
  title?: Prisma.StringFilter<"CannedResponse"> | string
  body?: Prisma.StringFilter<"CannedResponse"> | string
  teamId?: Prisma.IntNullableFilter<"CannedResponse"> | number | null
  updatedAt?: Prisma.DateTimeFilter<"CannedResponse"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"CannedResponse"> | Date | string
  createdById?: Prisma.IntNullableFilter<"CannedResponse"> | number | null
}

export type CannedResponseCreateWithoutCreatedByInput = {
  title: string
  body: string
  updatedAt?: Date | string
  createdAt?: Date | string
  team?: Prisma.TeamCreateNestedOneWithoutCannedResponsesInput
}

export type CannedResponseUncheckedCreateWithoutCreatedByInput = {
  id?: number
  title: string
  body: string
  teamId?: number | null
  updatedAt?: Date | string
  createdAt?: Date | string
}

export type CannedResponseCreateOrConnectWithoutCreatedByInput = {
  where: Prisma.CannedResponseWhereUniqueInput
  create: Prisma.XOR<Prisma.CannedResponseCreateWithoutCreatedByInput, Prisma.CannedResponseUncheckedCreateWithoutCreatedByInput>
}

export type CannedResponseCreateManyCreatedByInputEnvelope = {
  data: Prisma.CannedResponseCreateManyCreatedByInput | Prisma.CannedResponseCreateManyCreatedByInput[]
  skipDuplicates?: boolean
}

export type CannedResponseUpsertWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.CannedResponseWhereUniqueInput
  update: Prisma.XOR<Prisma.CannedResponseUpdateWithoutCreatedByInput, Prisma.CannedResponseUncheckedUpdateWithoutCreatedByInput>
  create: Prisma.XOR<Prisma.CannedResponseCreateWithoutCreatedByInput, Prisma.CannedResponseUncheckedCreateWithoutCreatedByInput>
}

export type CannedResponseUpdateWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.CannedResponseWhereUniqueInput
  data: Prisma.XOR<Prisma.CannedResponseUpdateWithoutCreatedByInput, Prisma.CannedResponseUncheckedUpdateWithoutCreatedByInput>
}

export type CannedResponseUpdateManyWithWhereWithoutCreatedByInput = {
  where: Prisma.CannedResponseScalarWhereInput
  data: Prisma.XOR<Prisma.CannedResponseUpdateManyMutationInput, Prisma.CannedResponseUncheckedUpdateManyWithoutCreatedByInput>
}

export type CannedResponseCreateManyTeamInput = {
  id?: number
  title: string
  body: string
  updatedAt?: Date | string
  createdAt?: Date | string
  createdById?: number | null
}

export type CannedResponseUpdateWithoutTeamInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.UserUpdateOneWithoutCreatedCannedResponsesNestedInput
}

export type CannedResponseUncheckedUpdateWithoutTeamInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type CannedResponseUncheckedUpdateManyWithoutTeamInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type CannedResponseCreateManyCreatedByInput = {
  id?: number
  title: string
  body: string
  teamId?: number | null
  updatedAt?: Date | string
  createdAt?: Date | string
}

export type CannedResponseUpdateWithoutCreatedByInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  team?: Prisma.TeamUpdateOneWithoutCannedResponsesNestedInput
}

export type CannedResponseUncheckedUpdateWithoutCreatedByInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CannedResponseUncheckedUpdateManyWithoutCreatedByInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CannedResponseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  body?: boolean
  teamId?: boolean
  updatedAt?: boolean
  createdAt?: boolean
  createdById?: boolean
  team?: boolean | Prisma.CannedResponse$teamArgs<ExtArgs>
  createdBy?: boolean | Prisma.CannedResponse$createdByArgs<ExtArgs>
}, ExtArgs["result"]["cannedResponse"]>



export type CannedResponseSelectScalar = {
  id?: boolean
  title?: boolean
  body?: boolean
  teamId?: boolean
  updatedAt?: boolean
  createdAt?: boolean
  createdById?: boolean
}

export type CannedResponseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "body" | "teamId" | "updatedAt" | "createdAt" | "createdById", ExtArgs["result"]["cannedResponse"]>
export type CannedResponseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  team?: boolean | Prisma.CannedResponse$teamArgs<ExtArgs>
  createdBy?: boolean | Prisma.CannedResponse$createdByArgs<ExtArgs>
}

export type $CannedResponsePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CannedResponse"
  objects: {
    /**
     * Related columns
     */
    team: Prisma.$TeamPayload<ExtArgs> | null
    createdBy: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    title: string
    body: string
    teamId: number | null
    /**
     * Audit columns
     */
    updatedAt: Date
    createdAt: Date
    createdById: number | null
  }, ExtArgs["result"]["cannedResponse"]>
  composites: {}
}

export type CannedResponseGetPayload<S extends boolean | null | undefined | CannedResponseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CannedResponsePayload, S>

export type CannedResponseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CannedResponseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CannedResponseCountAggregateInputType | true
  }

export interface CannedResponseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CannedResponse'], meta: { name: 'CannedResponse' } }
  /**
   * Find zero or one CannedResponse that matches the filter.
   * @param {CannedResponseFindUniqueArgs} args - Arguments to find a CannedResponse
   * @example
   * // Get one CannedResponse
   * const cannedResponse = await prisma.cannedResponse.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CannedResponseFindUniqueArgs>(args: Prisma.SelectSubset<T, CannedResponseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CannedResponseClient<runtime.Types.Result.GetResult<Prisma.$CannedResponsePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CannedResponse that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CannedResponseFindUniqueOrThrowArgs} args - Arguments to find a CannedResponse
   * @example
   * // Get one CannedResponse
   * const cannedResponse = await prisma.cannedResponse.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CannedResponseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CannedResponseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CannedResponseClient<runtime.Types.Result.GetResult<Prisma.$CannedResponsePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CannedResponse that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CannedResponseFindFirstArgs} args - Arguments to find a CannedResponse
   * @example
   * // Get one CannedResponse
   * const cannedResponse = await prisma.cannedResponse.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CannedResponseFindFirstArgs>(args?: Prisma.SelectSubset<T, CannedResponseFindFirstArgs<ExtArgs>>): Prisma.Prisma__CannedResponseClient<runtime.Types.Result.GetResult<Prisma.$CannedResponsePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CannedResponse that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CannedResponseFindFirstOrThrowArgs} args - Arguments to find a CannedResponse
   * @example
   * // Get one CannedResponse
   * const cannedResponse = await prisma.cannedResponse.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CannedResponseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CannedResponseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CannedResponseClient<runtime.Types.Result.GetResult<Prisma.$CannedResponsePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CannedResponses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CannedResponseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CannedResponses
   * const cannedResponses = await prisma.cannedResponse.findMany()
   * 
   * // Get first 10 CannedResponses
   * const cannedResponses = await prisma.cannedResponse.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const cannedResponseWithIdOnly = await prisma.cannedResponse.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CannedResponseFindManyArgs>(args?: Prisma.SelectSubset<T, CannedResponseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CannedResponsePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CannedResponse.
   * @param {CannedResponseCreateArgs} args - Arguments to create a CannedResponse.
   * @example
   * // Create one CannedResponse
   * const CannedResponse = await prisma.cannedResponse.create({
   *   data: {
   *     // ... data to create a CannedResponse
   *   }
   * })
   * 
   */
  create<T extends CannedResponseCreateArgs>(args: Prisma.SelectSubset<T, CannedResponseCreateArgs<ExtArgs>>): Prisma.Prisma__CannedResponseClient<runtime.Types.Result.GetResult<Prisma.$CannedResponsePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CannedResponses.
   * @param {CannedResponseCreateManyArgs} args - Arguments to create many CannedResponses.
   * @example
   * // Create many CannedResponses
   * const cannedResponse = await prisma.cannedResponse.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CannedResponseCreateManyArgs>(args?: Prisma.SelectSubset<T, CannedResponseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a CannedResponse.
   * @param {CannedResponseDeleteArgs} args - Arguments to delete one CannedResponse.
   * @example
   * // Delete one CannedResponse
   * const CannedResponse = await prisma.cannedResponse.delete({
   *   where: {
   *     // ... filter to delete one CannedResponse
   *   }
   * })
   * 
   */
  delete<T extends CannedResponseDeleteArgs>(args: Prisma.SelectSubset<T, CannedResponseDeleteArgs<ExtArgs>>): Prisma.Prisma__CannedResponseClient<runtime.Types.Result.GetResult<Prisma.$CannedResponsePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CannedResponse.
   * @param {CannedResponseUpdateArgs} args - Arguments to update one CannedResponse.
   * @example
   * // Update one CannedResponse
   * const cannedResponse = await prisma.cannedResponse.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CannedResponseUpdateArgs>(args: Prisma.SelectSubset<T, CannedResponseUpdateArgs<ExtArgs>>): Prisma.Prisma__CannedResponseClient<runtime.Types.Result.GetResult<Prisma.$CannedResponsePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CannedResponses.
   * @param {CannedResponseDeleteManyArgs} args - Arguments to filter CannedResponses to delete.
   * @example
   * // Delete a few CannedResponses
   * const { count } = await prisma.cannedResponse.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CannedResponseDeleteManyArgs>(args?: Prisma.SelectSubset<T, CannedResponseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CannedResponses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CannedResponseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CannedResponses
   * const cannedResponse = await prisma.cannedResponse.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CannedResponseUpdateManyArgs>(args: Prisma.SelectSubset<T, CannedResponseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one CannedResponse.
   * @param {CannedResponseUpsertArgs} args - Arguments to update or create a CannedResponse.
   * @example
   * // Update or create a CannedResponse
   * const cannedResponse = await prisma.cannedResponse.upsert({
   *   create: {
   *     // ... data to create a CannedResponse
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CannedResponse we want to update
   *   }
   * })
   */
  upsert<T extends CannedResponseUpsertArgs>(args: Prisma.SelectSubset<T, CannedResponseUpsertArgs<ExtArgs>>): Prisma.Prisma__CannedResponseClient<runtime.Types.Result.GetResult<Prisma.$CannedResponsePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CannedResponses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CannedResponseCountArgs} args - Arguments to filter CannedResponses to count.
   * @example
   * // Count the number of CannedResponses
   * const count = await prisma.cannedResponse.count({
   *   where: {
   *     // ... the filter for the CannedResponses we want to count
   *   }
   * })
  **/
  count<T extends CannedResponseCountArgs>(
    args?: Prisma.Subset<T, CannedResponseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CannedResponseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CannedResponse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CannedResponseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CannedResponseAggregateArgs>(args: Prisma.Subset<T, CannedResponseAggregateArgs>): Prisma.PrismaPromise<GetCannedResponseAggregateType<T>>

  /**
   * Group by CannedResponse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CannedResponseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CannedResponseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CannedResponseGroupByArgs['orderBy'] }
      : { orderBy?: CannedResponseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CannedResponseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCannedResponseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CannedResponse model
 */
readonly fields: CannedResponseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CannedResponse.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CannedResponseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  team<T extends Prisma.CannedResponse$teamArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CannedResponse$teamArgs<ExtArgs>>): Prisma.Prisma__TeamClient<runtime.Types.Result.GetResult<Prisma.$TeamPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  createdBy<T extends Prisma.CannedResponse$createdByArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CannedResponse$createdByArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CannedResponse model
 */
export interface CannedResponseFieldRefs {
  readonly id: Prisma.FieldRef<"CannedResponse", 'Int'>
  readonly title: Prisma.FieldRef<"CannedResponse", 'String'>
  readonly body: Prisma.FieldRef<"CannedResponse", 'String'>
  readonly teamId: Prisma.FieldRef<"CannedResponse", 'Int'>
  readonly updatedAt: Prisma.FieldRef<"CannedResponse", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"CannedResponse", 'DateTime'>
  readonly createdById: Prisma.FieldRef<"CannedResponse", 'Int'>
}
    

// Custom InputTypes
/**
 * CannedResponse findUnique
 */
export type CannedResponseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CannedResponse
   */
  select?: Prisma.CannedResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CannedResponse
   */
  omit?: Prisma.CannedResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CannedResponseInclude<ExtArgs> | null
  /**
   * Filter, which CannedResponse to fetch.
   */
  where: Prisma.CannedResponseWhereUniqueInput
}

/**
 * CannedResponse findUniqueOrThrow
 */
export type CannedResponseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CannedResponse
   */
  select?: Prisma.CannedResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CannedResponse
   */
  omit?: Prisma.CannedResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CannedResponseInclude<ExtArgs> | null
  /**
   * Filter, which CannedResponse to fetch.
   */
  where: Prisma.CannedResponseWhereUniqueInput
}

/**
 * CannedResponse findFirst
 */
export type CannedResponseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CannedResponse
   */
  select?: Prisma.CannedResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CannedResponse
   */
  omit?: Prisma.CannedResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CannedResponseInclude<ExtArgs> | null
  /**
   * Filter, which CannedResponse to fetch.
   */
  where?: Prisma.CannedResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CannedResponses to fetch.
   */
  orderBy?: Prisma.CannedResponseOrderByWithRelationInput | Prisma.CannedResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CannedResponses.
   */
  cursor?: Prisma.CannedResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CannedResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CannedResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CannedResponses.
   */
  distinct?: Prisma.CannedResponseScalarFieldEnum | Prisma.CannedResponseScalarFieldEnum[]
}

/**
 * CannedResponse findFirstOrThrow
 */
export type CannedResponseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CannedResponse
   */
  select?: Prisma.CannedResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CannedResponse
   */
  omit?: Prisma.CannedResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CannedResponseInclude<ExtArgs> | null
  /**
   * Filter, which CannedResponse to fetch.
   */
  where?: Prisma.CannedResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CannedResponses to fetch.
   */
  orderBy?: Prisma.CannedResponseOrderByWithRelationInput | Prisma.CannedResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CannedResponses.
   */
  cursor?: Prisma.CannedResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CannedResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CannedResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CannedResponses.
   */
  distinct?: Prisma.CannedResponseScalarFieldEnum | Prisma.CannedResponseScalarFieldEnum[]
}

/**
 * CannedResponse findMany
 */
export type CannedResponseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CannedResponse
   */
  select?: Prisma.CannedResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CannedResponse
   */
  omit?: Prisma.CannedResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CannedResponseInclude<ExtArgs> | null
  /**
   * Filter, which CannedResponses to fetch.
   */
  where?: Prisma.CannedResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CannedResponses to fetch.
   */
  orderBy?: Prisma.CannedResponseOrderByWithRelationInput | Prisma.CannedResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CannedResponses.
   */
  cursor?: Prisma.CannedResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CannedResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CannedResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CannedResponses.
   */
  distinct?: Prisma.CannedResponseScalarFieldEnum | Prisma.CannedResponseScalarFieldEnum[]
}

/**
 * CannedResponse create
 */
export type CannedResponseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CannedResponse
   */
  select?: Prisma.CannedResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CannedResponse
   */
  omit?: Prisma.CannedResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CannedResponseInclude<ExtArgs> | null
  /**
   * The data needed to create a CannedResponse.
   */
  data: Prisma.XOR<Prisma.CannedResponseCreateInput, Prisma.CannedResponseUncheckedCreateInput>
}

/**
 * CannedResponse createMany
 */
export type CannedResponseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CannedResponses.
   */
  data: Prisma.CannedResponseCreateManyInput | Prisma.CannedResponseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CannedResponse update
 */
export type CannedResponseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CannedResponse
   */
  select?: Prisma.CannedResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CannedResponse
   */
  omit?: Prisma.CannedResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CannedResponseInclude<ExtArgs> | null
  /**
   * The data needed to update a CannedResponse.
   */
  data: Prisma.XOR<Prisma.CannedResponseUpdateInput, Prisma.CannedResponseUncheckedUpdateInput>
  /**
   * Choose, which CannedResponse to update.
   */
  where: Prisma.CannedResponseWhereUniqueInput
}

/**
 * CannedResponse updateMany
 */
export type CannedResponseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CannedResponses.
   */
  data: Prisma.XOR<Prisma.CannedResponseUpdateManyMutationInput, Prisma.CannedResponseUncheckedUpdateManyInput>
  /**
   * Filter which CannedResponses to update
   */
  where?: Prisma.CannedResponseWhereInput
  /**
   * Limit how many CannedResponses to update.
   */
  limit?: number
}

/**
 * CannedResponse upsert
 */
export type CannedResponseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CannedResponse
   */
  select?: Prisma.CannedResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CannedResponse
   */
  omit?: Prisma.CannedResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CannedResponseInclude<ExtArgs> | null
  /**
   * The filter to search for the CannedResponse to update in case it exists.
   */
  where: Prisma.CannedResponseWhereUniqueInput
  /**
   * In case the CannedResponse found by the `where` argument doesn't exist, create a new CannedResponse with this data.
   */
  create: Prisma.XOR<Prisma.CannedResponseCreateInput, Prisma.CannedResponseUncheckedCreateInput>
  /**
   * In case the CannedResponse was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CannedResponseUpdateInput, Prisma.CannedResponseUncheckedUpdateInput>
}

/**
 * CannedResponse delete
 */
export type CannedResponseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CannedResponse
   */
  select?: Prisma.CannedResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CannedResponse
   */
  omit?: Prisma.CannedResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CannedResponseInclude<ExtArgs> | null
  /**
   * Filter which CannedResponse to delete.
   */
  where: Prisma.CannedResponseWhereUniqueInput
}

/**
 * CannedResponse deleteMany
 */
export type CannedResponseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CannedResponses to delete
   */
  where?: Prisma.CannedResponseWhereInput
  /**
   * Limit how many CannedResponses to delete.
   */
  limit?: number
}

/**
 * CannedResponse.team
 */
export type CannedResponse$teamArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Team
   */
  select?: Prisma.TeamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Team
   */
  omit?: Prisma.TeamOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamInclude<ExtArgs> | null
  where?: Prisma.TeamWhereInput
}

/**
 * CannedResponse.createdBy
 */
export type CannedResponse$createdByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * CannedResponse without action
 */
export type CannedResponseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CannedResponse
   */
  select?: Prisma.CannedResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CannedResponse
   */
  omit?: Prisma.CannedResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CannedResponseInclude<ExtArgs> | null
}
