
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import type * as Prisma from "./internal/prismaNamespace"


export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type FloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type EnumCompensationCurrencyFilter<$PrismaModel = never> = {
  equals?: $Enums.CompensationCurrency | Prisma.EnumCompensationCurrencyFieldRefInput<$PrismaModel>
  in?: $Enums.CompensationCurrency[]
  notIn?: $Enums.CompensationCurrency[]
  not?: Prisma.NestedEnumCompensationCurrencyFilter<$PrismaModel> | $Enums.CompensationCurrency
}

export type EnumCompensationReasonFilter<$PrismaModel = never> = {
  equals?: $Enums.CompensationReason | Prisma.EnumCompensationReasonFieldRefInput<$PrismaModel>
  in?: $Enums.CompensationReason[]
  notIn?: $Enums.CompensationReason[]
  not?: Prisma.NestedEnumCompensationReasonFilter<$PrismaModel> | $Enums.CompensationReason
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | null
  notIn?: string[] | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | null
  notIn?: Date[] | string[] | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type FloatWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedFloatFilter<$PrismaModel>
  _min?: Prisma.NestedFloatFilter<$PrismaModel>
  _max?: Prisma.NestedFloatFilter<$PrismaModel>
}

export type EnumCompensationCurrencyWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CompensationCurrency | Prisma.EnumCompensationCurrencyFieldRefInput<$PrismaModel>
  in?: $Enums.CompensationCurrency[]
  notIn?: $Enums.CompensationCurrency[]
  not?: Prisma.NestedEnumCompensationCurrencyWithAggregatesFilter<$PrismaModel> | $Enums.CompensationCurrency
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCompensationCurrencyFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCompensationCurrencyFilter<$PrismaModel>
}

export type EnumCompensationReasonWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CompensationReason | Prisma.EnumCompensationReasonFieldRefInput<$PrismaModel>
  in?: $Enums.CompensationReason[]
  notIn?: $Enums.CompensationReason[]
  not?: Prisma.NestedEnumCompensationReasonWithAggregatesFilter<$PrismaModel> | $Enums.CompensationReason
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCompensationReasonFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCompensationReasonFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | null
  notIn?: string[] | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | null
  notIn?: Date[] | string[] | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type EnumEmployeeDocumentCategoryFilter<$PrismaModel = never> = {
  equals?: $Enums.EmployeeDocumentCategory | Prisma.EnumEmployeeDocumentCategoryFieldRefInput<$PrismaModel>
  in?: $Enums.EmployeeDocumentCategory[]
  notIn?: $Enums.EmployeeDocumentCategory[]
  not?: Prisma.NestedEnumEmployeeDocumentCategoryFilter<$PrismaModel> | $Enums.EmployeeDocumentCategory
}

export type IntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type EnumEmployeeDocumentCategoryWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmployeeDocumentCategory | Prisma.EnumEmployeeDocumentCategoryFieldRefInput<$PrismaModel>
  in?: $Enums.EmployeeDocumentCategory[]
  notIn?: $Enums.EmployeeDocumentCategory[]
  not?: Prisma.NestedEnumEmployeeDocumentCategoryWithAggregatesFilter<$PrismaModel> | $Enums.EmployeeDocumentCategory
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmployeeDocumentCategoryFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmployeeDocumentCategoryFilter<$PrismaModel>
}

export type IntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type EnumEmployeeEmploymentTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.EmployeeEmploymentType | Prisma.EnumEmployeeEmploymentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EmployeeEmploymentType[]
  notIn?: $Enums.EmployeeEmploymentType[]
  not?: Prisma.NestedEnumEmployeeEmploymentTypeFilter<$PrismaModel> | $Enums.EmployeeEmploymentType
}

export type EnumEmployeeStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.EmployeeStatus | Prisma.EnumEmployeeStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EmployeeStatus[]
  notIn?: $Enums.EmployeeStatus[]
  not?: Prisma.NestedEnumEmployeeStatusFilter<$PrismaModel> | $Enums.EmployeeStatus
}

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type EnumEmployeeTwoFactorAuthFilter<$PrismaModel = never> = {
  equals?: $Enums.EmployeeTwoFactorAuth | Prisma.EnumEmployeeTwoFactorAuthFieldRefInput<$PrismaModel>
  in?: $Enums.EmployeeTwoFactorAuth[]
  notIn?: $Enums.EmployeeTwoFactorAuth[]
  not?: Prisma.NestedEnumEmployeeTwoFactorAuthFilter<$PrismaModel> | $Enums.EmployeeTwoFactorAuth
}

export type EnumEmployeeEmploymentTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmployeeEmploymentType | Prisma.EnumEmployeeEmploymentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EmployeeEmploymentType[]
  notIn?: $Enums.EmployeeEmploymentType[]
  not?: Prisma.NestedEnumEmployeeEmploymentTypeWithAggregatesFilter<$PrismaModel> | $Enums.EmployeeEmploymentType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmployeeEmploymentTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmployeeEmploymentTypeFilter<$PrismaModel>
}

export type EnumEmployeeStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmployeeStatus | Prisma.EnumEmployeeStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EmployeeStatus[]
  notIn?: $Enums.EmployeeStatus[]
  not?: Prisma.NestedEnumEmployeeStatusWithAggregatesFilter<$PrismaModel> | $Enums.EmployeeStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmployeeStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmployeeStatusFilter<$PrismaModel>
}

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type EnumEmployeeTwoFactorAuthWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmployeeTwoFactorAuth | Prisma.EnumEmployeeTwoFactorAuthFieldRefInput<$PrismaModel>
  in?: $Enums.EmployeeTwoFactorAuth[]
  notIn?: $Enums.EmployeeTwoFactorAuth[]
  not?: Prisma.NestedEnumEmployeeTwoFactorAuthWithAggregatesFilter<$PrismaModel> | $Enums.EmployeeTwoFactorAuth
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmployeeTwoFactorAuthFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmployeeTwoFactorAuthFilter<$PrismaModel>
}

export type EnumLeaveRequestTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.LeaveRequestType | Prisma.EnumLeaveRequestTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LeaveRequestType[]
  notIn?: $Enums.LeaveRequestType[]
  not?: Prisma.NestedEnumLeaveRequestTypeFilter<$PrismaModel> | $Enums.LeaveRequestType
}

export type EnumLeaveRequestStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.LeaveRequestStatus | Prisma.EnumLeaveRequestStatusFieldRefInput<$PrismaModel>
  in?: $Enums.LeaveRequestStatus[]
  notIn?: $Enums.LeaveRequestStatus[]
  not?: Prisma.NestedEnumLeaveRequestStatusFilter<$PrismaModel> | $Enums.LeaveRequestStatus
}

export type EnumLeaveRequestTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LeaveRequestType | Prisma.EnumLeaveRequestTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LeaveRequestType[]
  notIn?: $Enums.LeaveRequestType[]
  not?: Prisma.NestedEnumLeaveRequestTypeWithAggregatesFilter<$PrismaModel> | $Enums.LeaveRequestType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLeaveRequestTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLeaveRequestTypeFilter<$PrismaModel>
}

export type EnumLeaveRequestStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LeaveRequestStatus | Prisma.EnumLeaveRequestStatusFieldRefInput<$PrismaModel>
  in?: $Enums.LeaveRequestStatus[]
  notIn?: $Enums.LeaveRequestStatus[]
  not?: Prisma.NestedEnumLeaveRequestStatusWithAggregatesFilter<$PrismaModel> | $Enums.LeaveRequestStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLeaveRequestStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLeaveRequestStatusFilter<$PrismaModel>
}

export type JsonNullableFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<JsonNullableFilterBase<$PrismaModel>>, Exclude<keyof Required<JsonNullableFilterBase<$PrismaModel>>, 'path'>>,
    Required<JsonNullableFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<JsonNullableFilterBase<$PrismaModel>>, 'path'>>

export type JsonNullableFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
}

export type EnumPerformanceReviewStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.PerformanceReviewStatus | Prisma.EnumPerformanceReviewStatusFieldRefInput<$PrismaModel>
  in?: $Enums.PerformanceReviewStatus[]
  notIn?: $Enums.PerformanceReviewStatus[]
  not?: Prisma.NestedEnumPerformanceReviewStatusFilter<$PrismaModel> | $Enums.PerformanceReviewStatus
}

export type JsonNullableWithAggregatesFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>, Exclude<keyof Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>, 'path'>>,
    Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>, 'path'>>

export type JsonNullableWithAggregatesFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedJsonNullableFilter<$PrismaModel>
  _max?: Prisma.NestedJsonNullableFilter<$PrismaModel>
}

export type EnumPerformanceReviewStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PerformanceReviewStatus | Prisma.EnumPerformanceReviewStatusFieldRefInput<$PrismaModel>
  in?: $Enums.PerformanceReviewStatus[]
  notIn?: $Enums.PerformanceReviewStatus[]
  not?: Prisma.NestedEnumPerformanceReviewStatusWithAggregatesFilter<$PrismaModel> | $Enums.PerformanceReviewStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPerformanceReviewStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPerformanceReviewStatusFilter<$PrismaModel>
}

export type EnumPositionLevelFilter<$PrismaModel = never> = {
  equals?: $Enums.PositionLevel | Prisma.EnumPositionLevelFieldRefInput<$PrismaModel>
  in?: $Enums.PositionLevel[]
  notIn?: $Enums.PositionLevel[]
  not?: Prisma.NestedEnumPositionLevelFilter<$PrismaModel> | $Enums.PositionLevel
}

export type EnumPositionLevelWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PositionLevel | Prisma.EnumPositionLevelFieldRefInput<$PrismaModel>
  in?: $Enums.PositionLevel[]
  notIn?: $Enums.PositionLevel[]
  not?: Prisma.NestedEnumPositionLevelWithAggregatesFilter<$PrismaModel> | $Enums.PositionLevel
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPositionLevelFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPositionLevelFilter<$PrismaModel>
}

export type JsonFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<JsonFilterBase<$PrismaModel>>, Exclude<keyof Required<JsonFilterBase<$PrismaModel>>, 'path'>>,
    Required<JsonFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<JsonFilterBase<$PrismaModel>>, 'path'>>

export type JsonFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
}

export type JsonWithAggregatesFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<JsonWithAggregatesFilterBase<$PrismaModel>>, Exclude<keyof Required<JsonWithAggregatesFilterBase<$PrismaModel>>, 'path'>>,
    Required<JsonWithAggregatesFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<JsonWithAggregatesFilterBase<$PrismaModel>>, 'path'>>

export type JsonWithAggregatesFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedJsonFilter<$PrismaModel>
  _max?: Prisma.NestedJsonFilter<$PrismaModel>
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type NestedEnumCompensationCurrencyFilter<$PrismaModel = never> = {
  equals?: $Enums.CompensationCurrency | Prisma.EnumCompensationCurrencyFieldRefInput<$PrismaModel>
  in?: $Enums.CompensationCurrency[]
  notIn?: $Enums.CompensationCurrency[]
  not?: Prisma.NestedEnumCompensationCurrencyFilter<$PrismaModel> | $Enums.CompensationCurrency
}

export type NestedEnumCompensationReasonFilter<$PrismaModel = never> = {
  equals?: $Enums.CompensationReason | Prisma.EnumCompensationReasonFieldRefInput<$PrismaModel>
  in?: $Enums.CompensationReason[]
  notIn?: $Enums.CompensationReason[]
  not?: Prisma.NestedEnumCompensationReasonFilter<$PrismaModel> | $Enums.CompensationReason
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | null
  notIn?: string[] | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | null
  notIn?: Date[] | string[] | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedFloatWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedFloatFilter<$PrismaModel>
  _min?: Prisma.NestedFloatFilter<$PrismaModel>
  _max?: Prisma.NestedFloatFilter<$PrismaModel>
}

export type NestedEnumCompensationCurrencyWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CompensationCurrency | Prisma.EnumCompensationCurrencyFieldRefInput<$PrismaModel>
  in?: $Enums.CompensationCurrency[]
  notIn?: $Enums.CompensationCurrency[]
  not?: Prisma.NestedEnumCompensationCurrencyWithAggregatesFilter<$PrismaModel> | $Enums.CompensationCurrency
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCompensationCurrencyFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCompensationCurrencyFilter<$PrismaModel>
}

export type NestedEnumCompensationReasonWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CompensationReason | Prisma.EnumCompensationReasonFieldRefInput<$PrismaModel>
  in?: $Enums.CompensationReason[]
  notIn?: $Enums.CompensationReason[]
  not?: Prisma.NestedEnumCompensationReasonWithAggregatesFilter<$PrismaModel> | $Enums.CompensationReason
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCompensationReasonFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCompensationReasonFilter<$PrismaModel>
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | null
  notIn?: string[] | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | null
  notIn?: Date[] | string[] | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type NestedEnumEmployeeDocumentCategoryFilter<$PrismaModel = never> = {
  equals?: $Enums.EmployeeDocumentCategory | Prisma.EnumEmployeeDocumentCategoryFieldRefInput<$PrismaModel>
  in?: $Enums.EmployeeDocumentCategory[]
  notIn?: $Enums.EmployeeDocumentCategory[]
  not?: Prisma.NestedEnumEmployeeDocumentCategoryFilter<$PrismaModel> | $Enums.EmployeeDocumentCategory
}

export type NestedEnumEmployeeDocumentCategoryWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmployeeDocumentCategory | Prisma.EnumEmployeeDocumentCategoryFieldRefInput<$PrismaModel>
  in?: $Enums.EmployeeDocumentCategory[]
  notIn?: $Enums.EmployeeDocumentCategory[]
  not?: Prisma.NestedEnumEmployeeDocumentCategoryWithAggregatesFilter<$PrismaModel> | $Enums.EmployeeDocumentCategory
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmployeeDocumentCategoryFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmployeeDocumentCategoryFilter<$PrismaModel>
}

export type NestedIntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type NestedFloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null
}

export type NestedEnumEmployeeEmploymentTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.EmployeeEmploymentType | Prisma.EnumEmployeeEmploymentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EmployeeEmploymentType[]
  notIn?: $Enums.EmployeeEmploymentType[]
  not?: Prisma.NestedEnumEmployeeEmploymentTypeFilter<$PrismaModel> | $Enums.EmployeeEmploymentType
}

export type NestedEnumEmployeeStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.EmployeeStatus | Prisma.EnumEmployeeStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EmployeeStatus[]
  notIn?: $Enums.EmployeeStatus[]
  not?: Prisma.NestedEnumEmployeeStatusFilter<$PrismaModel> | $Enums.EmployeeStatus
}

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type NestedEnumEmployeeTwoFactorAuthFilter<$PrismaModel = never> = {
  equals?: $Enums.EmployeeTwoFactorAuth | Prisma.EnumEmployeeTwoFactorAuthFieldRefInput<$PrismaModel>
  in?: $Enums.EmployeeTwoFactorAuth[]
  notIn?: $Enums.EmployeeTwoFactorAuth[]
  not?: Prisma.NestedEnumEmployeeTwoFactorAuthFilter<$PrismaModel> | $Enums.EmployeeTwoFactorAuth
}

export type NestedEnumEmployeeEmploymentTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmployeeEmploymentType | Prisma.EnumEmployeeEmploymentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EmployeeEmploymentType[]
  notIn?: $Enums.EmployeeEmploymentType[]
  not?: Prisma.NestedEnumEmployeeEmploymentTypeWithAggregatesFilter<$PrismaModel> | $Enums.EmployeeEmploymentType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmployeeEmploymentTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmployeeEmploymentTypeFilter<$PrismaModel>
}

export type NestedEnumEmployeeStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmployeeStatus | Prisma.EnumEmployeeStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EmployeeStatus[]
  notIn?: $Enums.EmployeeStatus[]
  not?: Prisma.NestedEnumEmployeeStatusWithAggregatesFilter<$PrismaModel> | $Enums.EmployeeStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmployeeStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmployeeStatusFilter<$PrismaModel>
}

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type NestedEnumEmployeeTwoFactorAuthWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmployeeTwoFactorAuth | Prisma.EnumEmployeeTwoFactorAuthFieldRefInput<$PrismaModel>
  in?: $Enums.EmployeeTwoFactorAuth[]
  notIn?: $Enums.EmployeeTwoFactorAuth[]
  not?: Prisma.NestedEnumEmployeeTwoFactorAuthWithAggregatesFilter<$PrismaModel> | $Enums.EmployeeTwoFactorAuth
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmployeeTwoFactorAuthFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmployeeTwoFactorAuthFilter<$PrismaModel>
}

export type NestedEnumLeaveRequestTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.LeaveRequestType | Prisma.EnumLeaveRequestTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LeaveRequestType[]
  notIn?: $Enums.LeaveRequestType[]
  not?: Prisma.NestedEnumLeaveRequestTypeFilter<$PrismaModel> | $Enums.LeaveRequestType
}

export type NestedEnumLeaveRequestStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.LeaveRequestStatus | Prisma.EnumLeaveRequestStatusFieldRefInput<$PrismaModel>
  in?: $Enums.LeaveRequestStatus[]
  notIn?: $Enums.LeaveRequestStatus[]
  not?: Prisma.NestedEnumLeaveRequestStatusFilter<$PrismaModel> | $Enums.LeaveRequestStatus
}

export type NestedEnumLeaveRequestTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LeaveRequestType | Prisma.EnumLeaveRequestTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LeaveRequestType[]
  notIn?: $Enums.LeaveRequestType[]
  not?: Prisma.NestedEnumLeaveRequestTypeWithAggregatesFilter<$PrismaModel> | $Enums.LeaveRequestType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLeaveRequestTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLeaveRequestTypeFilter<$PrismaModel>
}

export type NestedEnumLeaveRequestStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LeaveRequestStatus | Prisma.EnumLeaveRequestStatusFieldRefInput<$PrismaModel>
  in?: $Enums.LeaveRequestStatus[]
  notIn?: $Enums.LeaveRequestStatus[]
  not?: Prisma.NestedEnumLeaveRequestStatusWithAggregatesFilter<$PrismaModel> | $Enums.LeaveRequestStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLeaveRequestStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLeaveRequestStatusFilter<$PrismaModel>
}

export type NestedEnumPerformanceReviewStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.PerformanceReviewStatus | Prisma.EnumPerformanceReviewStatusFieldRefInput<$PrismaModel>
  in?: $Enums.PerformanceReviewStatus[]
  notIn?: $Enums.PerformanceReviewStatus[]
  not?: Prisma.NestedEnumPerformanceReviewStatusFilter<$PrismaModel> | $Enums.PerformanceReviewStatus
}

export type NestedJsonNullableFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<NestedJsonNullableFilterBase<$PrismaModel>>, Exclude<keyof Required<NestedJsonNullableFilterBase<$PrismaModel>>, 'path'>>,
    Required<NestedJsonNullableFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<NestedJsonNullableFilterBase<$PrismaModel>>, 'path'>>

export type NestedJsonNullableFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
}

export type NestedEnumPerformanceReviewStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PerformanceReviewStatus | Prisma.EnumPerformanceReviewStatusFieldRefInput<$PrismaModel>
  in?: $Enums.PerformanceReviewStatus[]
  notIn?: $Enums.PerformanceReviewStatus[]
  not?: Prisma.NestedEnumPerformanceReviewStatusWithAggregatesFilter<$PrismaModel> | $Enums.PerformanceReviewStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPerformanceReviewStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPerformanceReviewStatusFilter<$PrismaModel>
}

export type NestedEnumPositionLevelFilter<$PrismaModel = never> = {
  equals?: $Enums.PositionLevel | Prisma.EnumPositionLevelFieldRefInput<$PrismaModel>
  in?: $Enums.PositionLevel[]
  notIn?: $Enums.PositionLevel[]
  not?: Prisma.NestedEnumPositionLevelFilter<$PrismaModel> | $Enums.PositionLevel
}

export type NestedEnumPositionLevelWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PositionLevel | Prisma.EnumPositionLevelFieldRefInput<$PrismaModel>
  in?: $Enums.PositionLevel[]
  notIn?: $Enums.PositionLevel[]
  not?: Prisma.NestedEnumPositionLevelWithAggregatesFilter<$PrismaModel> | $Enums.PositionLevel
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPositionLevelFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPositionLevelFilter<$PrismaModel>
}

export type NestedJsonFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<NestedJsonFilterBase<$PrismaModel>>, Exclude<keyof Required<NestedJsonFilterBase<$PrismaModel>>, 'path'>>,
    Required<NestedJsonFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<NestedJsonFilterBase<$PrismaModel>>, 'path'>>

export type NestedJsonFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
}


