
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const CompensationCurrency = {
  EUR: 'EUR',
  USD: 'USD',
  GBP: 'GBP'
} as const

export type CompensationCurrency = (typeof CompensationCurrency)[keyof typeof CompensationCurrency]


export const CompensationReason = {
  Hire: 'Hire',
  Promotion: 'Promotion',
  Adjustment: 'Adjustment',
  Market: 'Market'
} as const

export type CompensationReason = (typeof CompensationReason)[keyof typeof CompensationReason]


export const EmployeeDocumentCategory = {
  Contract: 'Contract',
  Payslip: 'Payslip',
  Certificate: 'Certificate',
  Policy: 'Policy',
  Other: 'Other'
} as const

export type EmployeeDocumentCategory = (typeof EmployeeDocumentCategory)[keyof typeof EmployeeDocumentCategory]


export const EmployeeEmploymentType = {
  FullTime: 'FullTime',
  PartTime: 'PartTime',
  Contractor: 'Contractor',
  Intern: 'Intern'
} as const

export type EmployeeEmploymentType = (typeof EmployeeEmploymentType)[keyof typeof EmployeeEmploymentType]


export const EmployeeStatus = {
  Active: 'Active',
  OnLeave: 'OnLeave',
  Terminated: 'Terminated'
} as const

export type EmployeeStatus = (typeof EmployeeStatus)[keyof typeof EmployeeStatus]


export const EmployeeTwoFactorAuth = {
  None: 'None',
  Email: 'Email'
} as const

export type EmployeeTwoFactorAuth = (typeof EmployeeTwoFactorAuth)[keyof typeof EmployeeTwoFactorAuth]


export const LeaveRequestType = {
  Annual: 'Annual',
  Sick: 'Sick',
  Parental: 'Parental',
  Unpaid: 'Unpaid'
} as const

export type LeaveRequestType = (typeof LeaveRequestType)[keyof typeof LeaveRequestType]


export const LeaveRequestStatus = {
  Pending: 'Pending',
  Approved: 'Approved',
  Rejected: 'Rejected',
  Cancelled: 'Cancelled'
} as const

export type LeaveRequestStatus = (typeof LeaveRequestStatus)[keyof typeof LeaveRequestStatus]


export const PerformanceReviewStatus = {
  Draft: 'Draft',
  Shared: 'Shared'
} as const

export type PerformanceReviewStatus = (typeof PerformanceReviewStatus)[keyof typeof PerformanceReviewStatus]


export const PositionLevel = {
  Junior: 'Junior',
  Mid: 'Mid',
  Senior: 'Senior',
  Lead: 'Lead',
  Principal: 'Principal'
} as const

export type PositionLevel = (typeof PositionLevel)[keyof typeof PositionLevel]
