
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Compensation'
export type * from './models/Department'
export type * from './models/EmployeeDocument'
export type * from './models/Employee'
export type * from './models/LeaveBalance'
export type * from './models/LeaveRequest'
export type * from './models/PerformanceReview'
export type * from './models/Position'
export type * from './models/OneTimeToken'
export type * from './models/Role'
export type * from './models/Permission'
export type * from './models/Seeder'
export type * from './models/File'
export type * from './commonInputTypes'