import { FetchResponse, MaybeOptionalInit } from 'openapi-fetch';
import {
  HttpMethod,
  MediaType,
  PathsWithMethod,
  RequiredKeysOf
} from 'openapi-typescript-helpers';
import { Observable } from 'rxjs';

export type ExtendedPaths<Paths> = Paths &
  Record<string, Record<HttpMethod, {}>>;

export type InitParam<Init> =
  RequiredKeysOf<Init> extends never
    ? [(Init & { [key: string]: unknown })?]
    : [Init & { [key: string]: unknown }];

export type ObservableOrPromise<T, B extends boolean> = B extends true
  ? Observable<T>
  : Promise<T>;

export type PromiseToObservable<T> =
  T extends Promise<infer R> ? Observable<R> : T;

export type ObservableMethods<T> = {
  [K in keyof T]: T[K] extends (...args: infer A) => infer R
    ? (...args: A) => PromiseToObservable<R>
    : T[K];
};

/**
 * Public interface for {@link BaseClient} exposing the three core request methods.
 *
 * @typeParam Paths - The OpenAPI path map generated by `openapi-typescript` for the target API.
 */
export interface BaseClientInterface<
  Paths extends {} = { [key: string]: any },
  UseObservable extends boolean = false
> {
  /**
   * Sends an HTTP request and returns the parsed response data.
   *
   * Throws a {@link ClientError} if the server returns an error response, including the
   * error message and status code from the response body when available.
   *
   * @typeParam Method - The HTTP method (e.g. `"get"`, `"post"`).
   * @typeParam Path - A path in `Paths` that supports `Method`.
   * @typeParam Init - The request init inferred from the OpenAPI schema for this operation.
   * @param {HttpMethod} method - The HTTP method to use.
   * @param {string} url - The API path to request.
   * @param {Object} params - Optional request parameters (body, query, headers, etc.) as defined by the schema.
   * @returns The non-nullable `data` field from the response.
   * @throws {ClientError} When the server returns an error response.
   */
  sendRequest<
    Method extends HttpMethod,
    Path extends PathsWithMethod<Paths, Method>,
    Init extends MaybeOptionalInit<ExtendedPaths<Paths>[Path], Method>
  >(
    method: Method,
    url: Path,
    ...params: InitParam<Init>
  ): ObservableOrPromise<
    NonNullable<
      FetchResponse<ExtendedPaths<Paths>[Path][Method], Init, MediaType>['data']
    >,
    UseObservable
  >;

  /**
   * Sends an HTTP request and returns the raw `openapi-fetch` response tuple.
   *
   * Unlike {@link sendRequest}, this method does **not** throw on error responses — callers
   * receive the full `{ data, error, response }` object and are responsible for handling
   * error cases themselves.
   *
   * @typeParam Method - The HTTP method (e.g. `"get"`, `"post"`).
   * @typeParam Path - A path in `Paths` that supports `Method`.
   * @typeParam Init - The request init inferred from the OpenAPI schema for this operation.
   * @param {HttpMethod} method - The HTTP method to use.
   * @param {string} url - The API path to request.
   * @param {Object} params - Optional request parameters (body, query, headers, etc.) as defined by the schema.
   * @returns The raw `FetchResponse` containing `data`, `error`, and the native `Response`.
   */
  sendRequestRaw<
    Method extends HttpMethod,
    Path extends PathsWithMethod<Paths, Method>,
    Init extends MaybeOptionalInit<ExtendedPaths<Paths>[Path], Method>
  >(
    method: Method,
    url: Path,
    ...params: InitParam<Init>
  ): ObservableOrPromise<
    FetchResponse<ExtendedPaths<Paths>[Path][Method], Init, MediaType>,
    UseObservable
  >;

  /**
   * Sends an HTTP request and returns the parsed response data as a Promise.
   *
   * This protected helper always returns a `Promise` and is intended to be called
   * by {@link sendRequest} and overrides in subclasses such as `AngularClient`.
   *
   * @throws {ClientError} When the server returns an error response.
   */
  sendRequestPromise<
    Method extends HttpMethod,
    Path extends PathsWithMethod<Paths, Method>,
    Init extends MaybeOptionalInit<ExtendedPaths<Paths>[Path], Method>
  >(
    method: Method,
    url: Path,
    ...params: InitParam<Init>
  ): Promise<
    NonNullable<
      FetchResponse<ExtendedPaths<Paths>[Path][Method], Init, MediaType>['data']
    >
  >;

  /**
   * Sends an HTTP request and returns the raw `openapi-fetch` response tuple as a Promise.
   *
   * This protected helper always returns a `Promise` and is intended to be called
   * by {@link sendRequestRaw} and overrides in subclasses such as `AngularClient`.
   */
  sendRequestRawPromise<
    Method extends HttpMethod,
    Path extends PathsWithMethod<Paths, Method>,
    Init extends MaybeOptionalInit<ExtendedPaths<Paths>[Path], Method>
  >(
    method: Method,
    url: Path,
    ...params: InitParam<Init>
  ): Promise<
    FetchResponse<ExtendedPaths<Paths>[Path][Method], Init, MediaType>
  >;
}
