
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Seeder` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Seeder
 * 
 */
export type SeederModel = runtime.Types.Result.DefaultSelection<Prisma.$SeederPayload>

export type AggregateSeeder = {
  _count: SeederCountAggregateOutputType | null
  _min: SeederMinAggregateOutputType | null
  _max: SeederMaxAggregateOutputType | null
}

export type SeederMinAggregateOutputType = {
  id: string | null
  checksum: string | null
  seederName: string | null
  startedAt: Date | null
  finishedAt: Date | null
  logs: string | null
}

export type SeederMaxAggregateOutputType = {
  id: string | null
  checksum: string | null
  seederName: string | null
  startedAt: Date | null
  finishedAt: Date | null
  logs: string | null
}

export type SeederCountAggregateOutputType = {
  id: number
  checksum: number
  seederName: number
  startedAt: number
  finishedAt: number
  logs: number
  _all: number
}


export type SeederMinAggregateInputType = {
  id?: true
  checksum?: true
  seederName?: true
  startedAt?: true
  finishedAt?: true
  logs?: true
}

export type SeederMaxAggregateInputType = {
  id?: true
  checksum?: true
  seederName?: true
  startedAt?: true
  finishedAt?: true
  logs?: true
}

export type SeederCountAggregateInputType = {
  id?: true
  checksum?: true
  seederName?: true
  startedAt?: true
  finishedAt?: true
  logs?: true
  _all?: true
}

export type SeederAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Seeder to aggregate.
   */
  where?: Prisma.SeederWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Seeders to fetch.
   */
  orderBy?: Prisma.SeederOrderByWithRelationInput | Prisma.SeederOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SeederWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Seeders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Seeders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Seeders
  **/
  _count?: true | SeederCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SeederMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SeederMaxAggregateInputType
}

export type GetSeederAggregateType<T extends SeederAggregateArgs> = {
      [P in keyof T & keyof AggregateSeeder]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSeeder[P]>
    : Prisma.GetScalarType<T[P], AggregateSeeder[P]>
}




export type SeederGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SeederWhereInput
  orderBy?: Prisma.SeederOrderByWithAggregationInput | Prisma.SeederOrderByWithAggregationInput[]
  by: Prisma.SeederScalarFieldEnum[] | Prisma.SeederScalarFieldEnum
  having?: Prisma.SeederScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SeederCountAggregateInputType | true
  _min?: SeederMinAggregateInputType
  _max?: SeederMaxAggregateInputType
}

export type SeederGroupByOutputType = {
  id: string
  checksum: string
  seederName: string
  startedAt: Date
  finishedAt: Date
  logs: string | null
  _count: SeederCountAggregateOutputType | null
  _min: SeederMinAggregateOutputType | null
  _max: SeederMaxAggregateOutputType | null
}

type GetSeederGroupByPayload<T extends SeederGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SeederGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SeederGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SeederGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SeederGroupByOutputType[P]>
      }
    >
  >



export type SeederWhereInput = {
  AND?: Prisma.SeederWhereInput | Prisma.SeederWhereInput[]
  OR?: Prisma.SeederWhereInput[]
  NOT?: Prisma.SeederWhereInput | Prisma.SeederWhereInput[]
  id?: Prisma.StringFilter<"Seeder"> | string
  checksum?: Prisma.StringFilter<"Seeder"> | string
  seederName?: Prisma.StringFilter<"Seeder"> | string
  startedAt?: Prisma.DateTimeFilter<"Seeder"> | Date | string
  finishedAt?: Prisma.DateTimeFilter<"Seeder"> | Date | string
  logs?: Prisma.StringNullableFilter<"Seeder"> | string | null
}

export type SeederOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  checksum?: Prisma.SortOrder
  seederName?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrder
  logs?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type SeederWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  seederName?: string
  AND?: Prisma.SeederWhereInput | Prisma.SeederWhereInput[]
  OR?: Prisma.SeederWhereInput[]
  NOT?: Prisma.SeederWhereInput | Prisma.SeederWhereInput[]
  checksum?: Prisma.StringFilter<"Seeder"> | string
  startedAt?: Prisma.DateTimeFilter<"Seeder"> | Date | string
  finishedAt?: Prisma.DateTimeFilter<"Seeder"> | Date | string
  logs?: Prisma.StringNullableFilter<"Seeder"> | string | null
}, "id" | "seederName">

export type SeederOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  checksum?: Prisma.SortOrder
  seederName?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrder
  logs?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.SeederCountOrderByAggregateInput
  _max?: Prisma.SeederMaxOrderByAggregateInput
  _min?: Prisma.SeederMinOrderByAggregateInput
}

export type SeederScalarWhereWithAggregatesInput = {
  AND?: Prisma.SeederScalarWhereWithAggregatesInput | Prisma.SeederScalarWhereWithAggregatesInput[]
  OR?: Prisma.SeederScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SeederScalarWhereWithAggregatesInput | Prisma.SeederScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Seeder"> | string
  checksum?: Prisma.StringWithAggregatesFilter<"Seeder"> | string
  seederName?: Prisma.StringWithAggregatesFilter<"Seeder"> | string
  startedAt?: Prisma.DateTimeWithAggregatesFilter<"Seeder"> | Date | string
  finishedAt?: Prisma.DateTimeWithAggregatesFilter<"Seeder"> | Date | string
  logs?: Prisma.StringNullableWithAggregatesFilter<"Seeder"> | string | null
}

export type SeederCreateInput = {
  id?: string
  checksum: string
  seederName: string
  startedAt: Date | string
  finishedAt: Date | string
  logs?: string | null
}

export type SeederUncheckedCreateInput = {
  id?: string
  checksum: string
  seederName: string
  startedAt: Date | string
  finishedAt: Date | string
  logs?: string | null
}

export type SeederUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  checksum?: Prisma.StringFieldUpdateOperationsInput | string
  seederName?: Prisma.StringFieldUpdateOperationsInput | string
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  logs?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SeederUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  checksum?: Prisma.StringFieldUpdateOperationsInput | string
  seederName?: Prisma.StringFieldUpdateOperationsInput | string
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  logs?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SeederCreateManyInput = {
  id?: string
  checksum: string
  seederName: string
  startedAt: Date | string
  finishedAt: Date | string
  logs?: string | null
}

export type SeederUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  checksum?: Prisma.StringFieldUpdateOperationsInput | string
  seederName?: Prisma.StringFieldUpdateOperationsInput | string
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  logs?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SeederUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  checksum?: Prisma.StringFieldUpdateOperationsInput | string
  seederName?: Prisma.StringFieldUpdateOperationsInput | string
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  logs?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SeederCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  checksum?: Prisma.SortOrder
  seederName?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrder
  logs?: Prisma.SortOrder
}

export type SeederMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  checksum?: Prisma.SortOrder
  seederName?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrder
  logs?: Prisma.SortOrder
}

export type SeederMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  checksum?: Prisma.SortOrder
  seederName?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrder
  logs?: Prisma.SortOrder
}



export type SeederSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  checksum?: boolean
  seederName?: boolean
  startedAt?: boolean
  finishedAt?: boolean
  logs?: boolean
}, ExtArgs["result"]["seeder"]>

export type SeederSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  checksum?: boolean
  seederName?: boolean
  startedAt?: boolean
  finishedAt?: boolean
  logs?: boolean
}, ExtArgs["result"]["seeder"]>

export type SeederSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  checksum?: boolean
  seederName?: boolean
  startedAt?: boolean
  finishedAt?: boolean
  logs?: boolean
}, ExtArgs["result"]["seeder"]>

export type SeederSelectScalar = {
  id?: boolean
  checksum?: boolean
  seederName?: boolean
  startedAt?: boolean
  finishedAt?: boolean
  logs?: boolean
}

export type SeederOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "checksum" | "seederName" | "startedAt" | "finishedAt" | "logs", ExtArgs["result"]["seeder"]>

export type $SeederPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Seeder"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    checksum: string
    seederName: string
    startedAt: Date
    finishedAt: Date
    logs: string | null
  }, ExtArgs["result"]["seeder"]>
  composites: {}
}

export type SeederGetPayload<S extends boolean | null | undefined | SeederDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SeederPayload, S>

export type SeederCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SeederFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SeederCountAggregateInputType | true
  }

export interface SeederDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Seeder'], meta: { name: 'Seeder' } }
  /**
   * Find zero or one Seeder that matches the filter.
   * @param {SeederFindUniqueArgs} args - Arguments to find a Seeder
   * @example
   * // Get one Seeder
   * const seeder = await prisma.seeder.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SeederFindUniqueArgs>(args: Prisma.SelectSubset<T, SeederFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SeederClient<runtime.Types.Result.GetResult<Prisma.$SeederPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Seeder that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SeederFindUniqueOrThrowArgs} args - Arguments to find a Seeder
   * @example
   * // Get one Seeder
   * const seeder = await prisma.seeder.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SeederFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SeederFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SeederClient<runtime.Types.Result.GetResult<Prisma.$SeederPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Seeder that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeederFindFirstArgs} args - Arguments to find a Seeder
   * @example
   * // Get one Seeder
   * const seeder = await prisma.seeder.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SeederFindFirstArgs>(args?: Prisma.SelectSubset<T, SeederFindFirstArgs<ExtArgs>>): Prisma.Prisma__SeederClient<runtime.Types.Result.GetResult<Prisma.$SeederPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Seeder that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeederFindFirstOrThrowArgs} args - Arguments to find a Seeder
   * @example
   * // Get one Seeder
   * const seeder = await prisma.seeder.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SeederFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SeederFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SeederClient<runtime.Types.Result.GetResult<Prisma.$SeederPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Seeders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeederFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Seeders
   * const seeders = await prisma.seeder.findMany()
   * 
   * // Get first 10 Seeders
   * const seeders = await prisma.seeder.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const seederWithIdOnly = await prisma.seeder.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SeederFindManyArgs>(args?: Prisma.SelectSubset<T, SeederFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeederPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Seeder.
   * @param {SeederCreateArgs} args - Arguments to create a Seeder.
   * @example
   * // Create one Seeder
   * const Seeder = await prisma.seeder.create({
   *   data: {
   *     // ... data to create a Seeder
   *   }
   * })
   * 
   */
  create<T extends SeederCreateArgs>(args: Prisma.SelectSubset<T, SeederCreateArgs<ExtArgs>>): Prisma.Prisma__SeederClient<runtime.Types.Result.GetResult<Prisma.$SeederPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Seeders.
   * @param {SeederCreateManyArgs} args - Arguments to create many Seeders.
   * @example
   * // Create many Seeders
   * const seeder = await prisma.seeder.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SeederCreateManyArgs>(args?: Prisma.SelectSubset<T, SeederCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Seeders and returns the data saved in the database.
   * @param {SeederCreateManyAndReturnArgs} args - Arguments to create many Seeders.
   * @example
   * // Create many Seeders
   * const seeder = await prisma.seeder.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Seeders and only return the `id`
   * const seederWithIdOnly = await prisma.seeder.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SeederCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SeederCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeederPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Seeder.
   * @param {SeederDeleteArgs} args - Arguments to delete one Seeder.
   * @example
   * // Delete one Seeder
   * const Seeder = await prisma.seeder.delete({
   *   where: {
   *     // ... filter to delete one Seeder
   *   }
   * })
   * 
   */
  delete<T extends SeederDeleteArgs>(args: Prisma.SelectSubset<T, SeederDeleteArgs<ExtArgs>>): Prisma.Prisma__SeederClient<runtime.Types.Result.GetResult<Prisma.$SeederPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Seeder.
   * @param {SeederUpdateArgs} args - Arguments to update one Seeder.
   * @example
   * // Update one Seeder
   * const seeder = await prisma.seeder.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SeederUpdateArgs>(args: Prisma.SelectSubset<T, SeederUpdateArgs<ExtArgs>>): Prisma.Prisma__SeederClient<runtime.Types.Result.GetResult<Prisma.$SeederPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Seeders.
   * @param {SeederDeleteManyArgs} args - Arguments to filter Seeders to delete.
   * @example
   * // Delete a few Seeders
   * const { count } = await prisma.seeder.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SeederDeleteManyArgs>(args?: Prisma.SelectSubset<T, SeederDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Seeders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeederUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Seeders
   * const seeder = await prisma.seeder.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SeederUpdateManyArgs>(args: Prisma.SelectSubset<T, SeederUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Seeders and returns the data updated in the database.
   * @param {SeederUpdateManyAndReturnArgs} args - Arguments to update many Seeders.
   * @example
   * // Update many Seeders
   * const seeder = await prisma.seeder.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Seeders and only return the `id`
   * const seederWithIdOnly = await prisma.seeder.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SeederUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SeederUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeederPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Seeder.
   * @param {SeederUpsertArgs} args - Arguments to update or create a Seeder.
   * @example
   * // Update or create a Seeder
   * const seeder = await prisma.seeder.upsert({
   *   create: {
   *     // ... data to create a Seeder
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Seeder we want to update
   *   }
   * })
   */
  upsert<T extends SeederUpsertArgs>(args: Prisma.SelectSubset<T, SeederUpsertArgs<ExtArgs>>): Prisma.Prisma__SeederClient<runtime.Types.Result.GetResult<Prisma.$SeederPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Seeders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeederCountArgs} args - Arguments to filter Seeders to count.
   * @example
   * // Count the number of Seeders
   * const count = await prisma.seeder.count({
   *   where: {
   *     // ... the filter for the Seeders we want to count
   *   }
   * })
  **/
  count<T extends SeederCountArgs>(
    args?: Prisma.Subset<T, SeederCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SeederCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Seeder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeederAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SeederAggregateArgs>(args: Prisma.Subset<T, SeederAggregateArgs>): Prisma.PrismaPromise<GetSeederAggregateType<T>>

  /**
   * Group by Seeder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeederGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SeederGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SeederGroupByArgs['orderBy'] }
      : { orderBy?: SeederGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SeederGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSeederGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Seeder model
 */
readonly fields: SeederFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Seeder.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SeederClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Seeder model
 */
export interface SeederFieldRefs {
  readonly id: Prisma.FieldRef<"Seeder", 'String'>
  readonly checksum: Prisma.FieldRef<"Seeder", 'String'>
  readonly seederName: Prisma.FieldRef<"Seeder", 'String'>
  readonly startedAt: Prisma.FieldRef<"Seeder", 'DateTime'>
  readonly finishedAt: Prisma.FieldRef<"Seeder", 'DateTime'>
  readonly logs: Prisma.FieldRef<"Seeder", 'String'>
}
    

// Custom InputTypes
/**
 * Seeder findUnique
 */
export type SeederFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seeder
   */
  select?: Prisma.SeederSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seeder
   */
  omit?: Prisma.SeederOmit<ExtArgs> | null
  /**
   * Filter, which Seeder to fetch.
   */
  where: Prisma.SeederWhereUniqueInput
}

/**
 * Seeder findUniqueOrThrow
 */
export type SeederFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seeder
   */
  select?: Prisma.SeederSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seeder
   */
  omit?: Prisma.SeederOmit<ExtArgs> | null
  /**
   * Filter, which Seeder to fetch.
   */
  where: Prisma.SeederWhereUniqueInput
}

/**
 * Seeder findFirst
 */
export type SeederFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seeder
   */
  select?: Prisma.SeederSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seeder
   */
  omit?: Prisma.SeederOmit<ExtArgs> | null
  /**
   * Filter, which Seeder to fetch.
   */
  where?: Prisma.SeederWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Seeders to fetch.
   */
  orderBy?: Prisma.SeederOrderByWithRelationInput | Prisma.SeederOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Seeders.
   */
  cursor?: Prisma.SeederWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Seeders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Seeders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Seeders.
   */
  distinct?: Prisma.SeederScalarFieldEnum | Prisma.SeederScalarFieldEnum[]
}

/**
 * Seeder findFirstOrThrow
 */
export type SeederFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seeder
   */
  select?: Prisma.SeederSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seeder
   */
  omit?: Prisma.SeederOmit<ExtArgs> | null
  /**
   * Filter, which Seeder to fetch.
   */
  where?: Prisma.SeederWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Seeders to fetch.
   */
  orderBy?: Prisma.SeederOrderByWithRelationInput | Prisma.SeederOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Seeders.
   */
  cursor?: Prisma.SeederWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Seeders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Seeders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Seeders.
   */
  distinct?: Prisma.SeederScalarFieldEnum | Prisma.SeederScalarFieldEnum[]
}

/**
 * Seeder findMany
 */
export type SeederFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seeder
   */
  select?: Prisma.SeederSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seeder
   */
  omit?: Prisma.SeederOmit<ExtArgs> | null
  /**
   * Filter, which Seeders to fetch.
   */
  where?: Prisma.SeederWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Seeders to fetch.
   */
  orderBy?: Prisma.SeederOrderByWithRelationInput | Prisma.SeederOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Seeders.
   */
  cursor?: Prisma.SeederWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Seeders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Seeders.
   */
  skip?: number
  distinct?: Prisma.SeederScalarFieldEnum | Prisma.SeederScalarFieldEnum[]
}

/**
 * Seeder create
 */
export type SeederCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seeder
   */
  select?: Prisma.SeederSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seeder
   */
  omit?: Prisma.SeederOmit<ExtArgs> | null
  /**
   * The data needed to create a Seeder.
   */
  data: Prisma.XOR<Prisma.SeederCreateInput, Prisma.SeederUncheckedCreateInput>
}

/**
 * Seeder createMany
 */
export type SeederCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Seeders.
   */
  data: Prisma.SeederCreateManyInput | Prisma.SeederCreateManyInput[]
}

/**
 * Seeder createManyAndReturn
 */
export type SeederCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seeder
   */
  select?: Prisma.SeederSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Seeder
   */
  omit?: Prisma.SeederOmit<ExtArgs> | null
  /**
   * The data used to create many Seeders.
   */
  data: Prisma.SeederCreateManyInput | Prisma.SeederCreateManyInput[]
}

/**
 * Seeder update
 */
export type SeederUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seeder
   */
  select?: Prisma.SeederSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seeder
   */
  omit?: Prisma.SeederOmit<ExtArgs> | null
  /**
   * The data needed to update a Seeder.
   */
  data: Prisma.XOR<Prisma.SeederUpdateInput, Prisma.SeederUncheckedUpdateInput>
  /**
   * Choose, which Seeder to update.
   */
  where: Prisma.SeederWhereUniqueInput
}

/**
 * Seeder updateMany
 */
export type SeederUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Seeders.
   */
  data: Prisma.XOR<Prisma.SeederUpdateManyMutationInput, Prisma.SeederUncheckedUpdateManyInput>
  /**
   * Filter which Seeders to update
   */
  where?: Prisma.SeederWhereInput
  /**
   * Limit how many Seeders to update.
   */
  limit?: number
}

/**
 * Seeder updateManyAndReturn
 */
export type SeederUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seeder
   */
  select?: Prisma.SeederSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Seeder
   */
  omit?: Prisma.SeederOmit<ExtArgs> | null
  /**
   * The data used to update Seeders.
   */
  data: Prisma.XOR<Prisma.SeederUpdateManyMutationInput, Prisma.SeederUncheckedUpdateManyInput>
  /**
   * Filter which Seeders to update
   */
  where?: Prisma.SeederWhereInput
  /**
   * Limit how many Seeders to update.
   */
  limit?: number
}

/**
 * Seeder upsert
 */
export type SeederUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seeder
   */
  select?: Prisma.SeederSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seeder
   */
  omit?: Prisma.SeederOmit<ExtArgs> | null
  /**
   * The filter to search for the Seeder to update in case it exists.
   */
  where: Prisma.SeederWhereUniqueInput
  /**
   * In case the Seeder found by the `where` argument doesn't exist, create a new Seeder with this data.
   */
  create: Prisma.XOR<Prisma.SeederCreateInput, Prisma.SeederUncheckedCreateInput>
  /**
   * In case the Seeder was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SeederUpdateInput, Prisma.SeederUncheckedUpdateInput>
}

/**
 * Seeder delete
 */
export type SeederDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seeder
   */
  select?: Prisma.SeederSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seeder
   */
  omit?: Prisma.SeederOmit<ExtArgs> | null
  /**
   * Filter which Seeder to delete.
   */
  where: Prisma.SeederWhereUniqueInput
}

/**
 * Seeder deleteMany
 */
export type SeederDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Seeders to delete
   */
  where?: Prisma.SeederWhereInput
  /**
   * Limit how many Seeders to delete.
   */
  limit?: number
}

/**
 * Seeder without action
 */
export type SeederDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seeder
   */
  select?: Prisma.SeederSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seeder
   */
  omit?: Prisma.SeederOmit<ExtArgs> | null
}
