// Generated by Appweaver. Please do not edit this file manually.

import {
  AggregateSelect,
  IResourceService,
  QueryFilter,
  QuerySort
} from '@appweaver/common';

export type Compensation = {
  id: number;
  baseSalary: number;
  currency: 'EUR' | 'USD' | 'GBP';
  bonusTargetPercent: number;
  reason: 'Hire' | 'Promotion' | 'Adjustment' | 'Market';
  effectiveFrom: Date;
  notes?: string | null;
  employee: EmployeeSingle;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  deletedAt?: Date | null;
  deletedById?: string | null;
};

export type CompensationSingle = {
  id: number;
  baseSalary: number;
  currency: 'EUR' | 'USD' | 'GBP';
  bonusTargetPercent: number;
  reason: 'Hire' | 'Promotion' | 'Adjustment' | 'Market';
  effectiveFrom: Date;
  notes?: string | null;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  employee?: EmployeeSingle;
};

export type CompensationMultiple = {
  id: number;
  baseSalary: number;
  currency: 'EUR' | 'USD' | 'GBP';
  bonusTargetPercent: number;
  reason: 'Hire' | 'Promotion' | 'Adjustment' | 'Market';
  effectiveFrom: Date;
  notes?: string | null;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  employee?: EmployeeSingle;
};

export type CompensationCreate = {
  baseSalary: number;
  currency?: 'EUR' | 'USD' | 'GBP';
  bonusTargetPercent?: number;
  reason?: 'Hire' | 'Promotion' | 'Adjustment' | 'Market';
  effectiveFrom: Date;
  notes?: string | null;
  employee:
    | {
        id: string;
      }
    | string;
};

export type CompensationUpdate = {
  baseSalary?: number;
  currency?: 'EUR' | 'USD' | 'GBP';
  bonusTargetPercent?: number;
  reason?: 'Hire' | 'Promotion' | 'Adjustment' | 'Market';
  effectiveFrom?: Date;
  notes?: string | null;
  employee?:
    | {
        id: string;
      }
    | string;
};

export type CompensationRelationCreate = {
  baseSalary: number;
  currency?: 'EUR' | 'USD' | 'GBP';
  bonusTargetPercent?: number;
  reason?: 'Hire' | 'Promotion' | 'Adjustment' | 'Market';
  effectiveFrom: Date;
  notes?: string | null;
};

export type CompensationRelationUpdate = {
  id: number;
  baseSalary?: number;
  currency?: 'EUR' | 'USD' | 'GBP';
  bonusTargetPercent?: number;
  reason?: 'Hire' | 'Promotion' | 'Adjustment' | 'Market';
  effectiveFrom?: Date;
  notes?: string | null;
};

export type CompensationRelationInput = {
  id?: number;
  baseSalary?: number;
  currency?: 'EUR' | 'USD' | 'GBP';
  bonusTargetPercent?: number;
  reason?: 'Hire' | 'Promotion' | 'Adjustment' | 'Market';
  effectiveFrom?: Date;
  notes?: string | null;
};

export type CompensationQuery = QueryFilter<Compensation>;

export type CompensationSort = QuerySort<CompensationMultiple>;

export type CompensationAggregate = AggregateSelect<Compensation>;

export type CompensationResourceService = IResourceService<
  Compensation,
  CompensationMultiple,
  CompensationCreate,
  CompensationUpdate,
  CompensationQuery
>;

export type Department = {
  id: number;
  name: string;
  code: string;
  description?: string | null;
  costCenter?: string | null;
  head?: EmployeeSingle;
  employees?: Array<EmployeeSingle>;
  positions?: Array<PositionSingle>;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
};

export type DepartmentSingle = {
  id: number;
  name: string;
  code: string;
  description?: string | null;
  costCenter?: string | null;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  head?: EmployeeSingle | null;
  employeesCount?: number;
  positions?: Array<PositionSingle>;
};

export type DepartmentMultiple = {
  id: number;
  name: string;
  code: string;
  description?: string | null;
  costCenter?: string | null;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  head?: EmployeeSingle | null;
  employeesCount?: number;
};

export type DepartmentCreate = {
  name: string;
  code: string;
  description?: string | null;
  costCenter?: string | null;
  head?:
    | {
        id: string;
      }
    | string;
};

export type DepartmentUpdate = {
  name?: string;
  code?: string;
  description?: string | null;
  costCenter?: string | null;
  head?:
    | {
        id: string;
      }
    | string;
};

export type DepartmentRelationCreate = {
  name: string;
  code: string;
  description?: string | null;
  costCenter?: string | null;
};

export type DepartmentRelationUpdate = {
  id: number;
  name?: string;
  code?: string;
  description?: string | null;
  costCenter?: string | null;
};

export type DepartmentRelationInput = {
  id?: number;
  name?: string;
  code?: string;
  description?: string | null;
  costCenter?: string | null;
};

export type DepartmentQuery = QueryFilter<Department>;

export type DepartmentSort = QuerySort<DepartmentMultiple>;

export type DepartmentAggregate = AggregateSelect<Department>;

export type DepartmentResourceService = IResourceService<
  Department,
  DepartmentMultiple,
  DepartmentCreate,
  DepartmentUpdate,
  DepartmentQuery
>;

export type EmployeeDocument = {
  id: number;
  title: string;
  category: 'Contract' | 'Payslip' | 'Certificate' | 'Policy' | 'Other';
  validUntil?: Date | null;
  employee: EmployeeSingle;
  file?: FileSingle | null;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  deletedAt?: Date | null;
  deletedById?: string | null;
};

export type EmployeeDocumentSingle = {
  id: number;
  title: string;
  category: 'Contract' | 'Payslip' | 'Certificate' | 'Policy' | 'Other';
  validUntil?: Date | null;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  employee?: EmployeeSingle;
  file?: FileSingle | null;
};

export type EmployeeDocumentMultiple = {
  id: number;
  title: string;
  category: 'Contract' | 'Payslip' | 'Certificate' | 'Policy' | 'Other';
  validUntil?: Date | null;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  employee?: EmployeeSingle;
  file?: FileSingle | null;
};

export type EmployeeDocumentCreate = {
  title: string;
  category?: 'Contract' | 'Payslip' | 'Certificate' | 'Policy' | 'Other';
  validUntil?: Date | null;
  employee:
    | {
        id: string;
      }
    | string;
};

export type EmployeeDocumentUpdate = {
  title?: string;
  category?: 'Contract' | 'Payslip' | 'Certificate' | 'Policy' | 'Other';
  validUntil?: Date | null;
  employee?:
    | {
        id: string;
      }
    | string;
};

export type EmployeeDocumentRelationCreate = {
  title: string;
  category?: 'Contract' | 'Payslip' | 'Certificate' | 'Policy' | 'Other';
  validUntil?: Date | null;
};

export type EmployeeDocumentRelationUpdate = {
  id: number;
  title?: string;
  category?: 'Contract' | 'Payslip' | 'Certificate' | 'Policy' | 'Other';
  validUntil?: Date | null;
};

export type EmployeeDocumentRelationInput = {
  id?: number;
  title?: string;
  category?: 'Contract' | 'Payslip' | 'Certificate' | 'Policy' | 'Other';
  validUntil?: Date | null;
};

export type EmployeeDocumentQuery = QueryFilter<EmployeeDocument>;

export type EmployeeDocumentSort = QuerySort<EmployeeDocumentMultiple>;

export type EmployeeDocumentAggregate = AggregateSelect<EmployeeDocument>;

export type EmployeeDocumentResourceService = IResourceService<
  EmployeeDocument,
  EmployeeDocumentMultiple,
  EmployeeDocumentCreate,
  EmployeeDocumentUpdate,
  EmployeeDocumentQuery
>;

export type Employee = {
  id: string;
  employeeNumber: string;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  employmentType: 'FullTime' | 'PartTime' | 'Contractor' | 'Intern';
  status: 'Active' | 'OnLeave' | 'Terminated';
  hireDate: Date;
  terminatedAt?: Date | null;
  passwordHash?: string | null;
  verifiedEmail: boolean;
  twoFactorAuth: 'None' | 'Email';
  enabled: boolean;
  logoutAt?: Date | null;
  fullName: string;
  yearsOfService: number;
  password: string;
  department?: DepartmentSingle;
  position?: PositionSingle;
  manager?: EmployeeSingle;
  reports?: Array<EmployeeSingle>;
  headOf?: DepartmentSingle;
  leaveBalances?: Array<LeaveBalanceSingle>;
  leaveRequests?: Array<LeaveRequestSingle>;
  decidedLeaveRequests?: Array<LeaveRequestSingle>;
  documents?: Array<EmployeeDocumentSingle>;
  compensations?: Array<CompensationSingle>;
  reviews?: Array<PerformanceReviewSingle>;
  writtenReviews?: Array<PerformanceReviewSingle>;
  roles: Array<RoleSingle>;
  avatar?: FileSingle | null;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  deletedAt?: Date | null;
  deletedById?: string | null;
};

export type EmployeeSingle = {
  id: string;
  employeeNumber: string;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  employmentType: 'FullTime' | 'PartTime' | 'Contractor' | 'Intern';
  status: 'Active' | 'OnLeave' | 'Terminated';
  hireDate: Date;
  terminatedAt?: Date | null;
  verifiedEmail: boolean;
  twoFactorAuth: 'None' | 'Email';
  enabled: boolean;
  logoutAt?: Date | null;
  fullName: string;
  yearsOfService: number;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  department?: DepartmentSingle | null;
  position?: PositionSingle | null;
  manager?: EmployeeSingle | null;
  reports?: Array<EmployeeSingle>;
  reportsCount?: number;
  leaveBalances?: Array<LeaveBalanceSingle>;
  leaveRequestsCount?: number;
  documentsCount?: number;
  roles?: Array<RoleSingle>;
  avatar?: FileSingle | null;
};

export type EmployeeMultiple = {
  id: string;
  employeeNumber: string;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  employmentType: 'FullTime' | 'PartTime' | 'Contractor' | 'Intern';
  status: 'Active' | 'OnLeave' | 'Terminated';
  hireDate: Date;
  terminatedAt?: Date | null;
  verifiedEmail: boolean;
  twoFactorAuth: 'None' | 'Email';
  enabled: boolean;
  logoutAt?: Date | null;
  fullName: string;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  department?: DepartmentSingle | null;
  position?: PositionSingle | null;
  manager?: EmployeeSingle | null;
  reportsCount?: number;
  leaveRequestsCount?: number;
  documentsCount?: number;
  roles?: Array<RoleSingle>;
  avatar?: FileSingle | null;
};

export type EmployeeCreate = {
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  employmentType?: 'FullTime' | 'PartTime' | 'Contractor' | 'Intern';
  hireDate: Date;
  twoFactorAuth?: 'None' | 'Email';
  enabled?: boolean;
  password: string;
  department?:
    | {
        id: number;
      }
    | number;
  position?:
    | {
        id: number;
      }
    | number;
  manager?:
    | {
        id: string;
      }
    | string;
  roles: Array<
    | {
        id: number;
      }
    | number
  >;
};

export type EmployeeUpdate = {
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string | null;
  employmentType?: 'FullTime' | 'PartTime' | 'Contractor' | 'Intern';
  status?: 'Active' | 'OnLeave' | 'Terminated';
  hireDate?: Date;
  twoFactorAuth?: 'None' | 'Email';
  enabled?: boolean;
  password?: string;
  department?:
    | {
        id: number;
      }
    | number;
  position?:
    | {
        id: number;
      }
    | number;
  manager?:
    | {
        id: string;
      }
    | string;
  roles?: Array<
    | {
        id: number;
      }
    | number
  >;
};

export type EmployeeRelationCreate = {
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  employmentType?: 'FullTime' | 'PartTime' | 'Contractor' | 'Intern';
  hireDate: Date;
  twoFactorAuth?: 'None' | 'Email';
  enabled?: boolean;
  password: string;
};

export type EmployeeRelationUpdate = {
  id: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string | null;
  employmentType?: 'FullTime' | 'PartTime' | 'Contractor' | 'Intern';
  status?: 'Active' | 'OnLeave' | 'Terminated';
  hireDate?: Date;
  twoFactorAuth?: 'None' | 'Email';
  enabled?: boolean;
  password?: string;
};

export type EmployeeRelationInput = {
  id?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string | null;
  employmentType?: 'FullTime' | 'PartTime' | 'Contractor' | 'Intern';
  hireDate?: Date;
  twoFactorAuth?: 'None' | 'Email';
  enabled?: boolean;
  password?: string;
  status?: 'Active' | 'OnLeave' | 'Terminated';
};

export type EmployeeQuery = QueryFilter<Employee>;

export type EmployeeSort = QuerySort<EmployeeMultiple>;

export type EmployeeAggregate = AggregateSelect<Employee>;

export type EmployeeResourceService = IResourceService<
  Employee,
  EmployeeMultiple,
  EmployeeCreate,
  EmployeeUpdate,
  EmployeeQuery
>;

export type LeaveBalance = {
  id: number;
  year: number;
  allowanceDays: number;
  carriedOverDays: number;
  usedDays: number;
  remainingDays: number;
  employee: EmployeeSingle;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  deletedAt?: Date | null;
  deletedById?: string | null;
};

export type LeaveBalanceSingle = {
  id: number;
  year: number;
  allowanceDays: number;
  carriedOverDays: number;
  usedDays: number;
  remainingDays: number;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
};

export type LeaveBalanceMultiple = {
  id: number;
  year: number;
  allowanceDays: number;
  carriedOverDays: number;
  usedDays: number;
  remainingDays: number;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  employee?: EmployeeSingle;
};

export type LeaveBalanceCreate = {
  year: number;
  allowanceDays: number;
  carriedOverDays?: number;
  employee:
    | {
        id: string;
      }
    | string;
};

export type LeaveBalanceUpdate = {
  year?: number;
  allowanceDays?: number;
  carriedOverDays?: number;
  employee?:
    | {
        id: string;
      }
    | string;
};

export type LeaveBalanceRelationCreate = {
  year: number;
  allowanceDays: number;
  carriedOverDays?: number;
};

export type LeaveBalanceRelationUpdate = {
  id: number;
  year?: number;
  allowanceDays?: number;
  carriedOverDays?: number;
};

export type LeaveBalanceRelationInput = {
  id?: number;
  year?: number;
  allowanceDays?: number;
  carriedOverDays?: number;
};

export type LeaveBalanceQuery = QueryFilter<LeaveBalance>;

export type LeaveBalanceSort = QuerySort<LeaveBalanceMultiple>;

export type LeaveBalanceAggregate = AggregateSelect<LeaveBalance>;

export type LeaveBalanceResourceService = IResourceService<
  LeaveBalance,
  LeaveBalanceMultiple,
  LeaveBalanceCreate,
  LeaveBalanceUpdate,
  LeaveBalanceQuery
>;

export type LeaveRequest = {
  id: number;
  type: 'Annual' | 'Sick' | 'Parental' | 'Unpaid';
  startDate: Date;
  endDate: Date;
  days: number;
  reason?: string | null;
  status: 'Pending' | 'Approved' | 'Rejected' | 'Cancelled';
  decidedAt?: Date | null;
  decisionNote?: string | null;
  employee?: EmployeeSingle;
  decidedBy?: EmployeeSingle;
  attachment?: FileSingle | null;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  deletedAt?: Date | null;
  deletedById?: string | null;
};

export type LeaveRequestSingle = {
  id: number;
  type: 'Annual' | 'Sick' | 'Parental' | 'Unpaid';
  startDate: Date;
  endDate: Date;
  days: number;
  reason?: string | null;
  status: 'Pending' | 'Approved' | 'Rejected' | 'Cancelled';
  decidedAt?: Date | null;
  decisionNote?: string | null;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  employee?: EmployeeSingle | null;
  decidedBy?: EmployeeSingle | null;
  attachment?: FileSingle | null;
};

export type LeaveRequestMultiple = {
  id: number;
  type: 'Annual' | 'Sick' | 'Parental' | 'Unpaid';
  startDate: Date;
  endDate: Date;
  days: number;
  reason?: string | null;
  status: 'Pending' | 'Approved' | 'Rejected' | 'Cancelled';
  decidedAt?: Date | null;
  decisionNote?: string | null;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  employee?: EmployeeSingle | null;
  attachment?: FileSingle | null;
};

export type LeaveRequestCreate = {
  type?: 'Annual' | 'Sick' | 'Parental' | 'Unpaid';
  startDate: Date;
  endDate: Date;
  reason?: string | null;
  employee?:
    | {
        id: string;
      }
    | string;
};

export type LeaveRequestUpdate = {
  type?: 'Annual' | 'Sick' | 'Parental' | 'Unpaid';
  startDate?: Date;
  endDate?: Date;
  reason?: string | null;
  employee?:
    | {
        id: string;
      }
    | string;
};

export type LeaveRequestRelationCreate = {
  type?: 'Annual' | 'Sick' | 'Parental' | 'Unpaid';
  startDate: Date;
  endDate: Date;
  reason?: string | null;
};

export type LeaveRequestRelationUpdate = {
  id: number;
  type?: 'Annual' | 'Sick' | 'Parental' | 'Unpaid';
  startDate?: Date;
  endDate?: Date;
  reason?: string | null;
};

export type LeaveRequestRelationInput = {
  id?: number;
  type?: 'Annual' | 'Sick' | 'Parental' | 'Unpaid';
  startDate?: Date;
  endDate?: Date;
  reason?: string | null;
};

export type LeaveRequestQuery = QueryFilter<LeaveRequest>;

export type LeaveRequestSort = QuerySort<LeaveRequestMultiple>;

export type LeaveRequestAggregate = AggregateSelect<LeaveRequest>;

export type LeaveRequestResourceService = IResourceService<
  LeaveRequest,
  LeaveRequestMultiple,
  LeaveRequestCreate,
  LeaveRequestUpdate,
  LeaveRequestQuery
>;

export type PerformanceReview = {
  id: number;
  period: string;
  rating: number;
  strengths?: string | null;
  improvements?: string | null;
  goals?: any | null;
  status: 'Draft' | 'Shared';
  employee: EmployeeSingle;
  reviewer?: EmployeeSingle;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  deletedAt?: Date | null;
  deletedById?: string | null;
};

export type PerformanceReviewSingle = {
  id: number;
  period: string;
  rating: number;
  strengths?: string | null;
  improvements?: string | null;
  goals?: any | null;
  status: 'Draft' | 'Shared';
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  employee?: EmployeeSingle;
  reviewer?: EmployeeSingle | null;
};

export type PerformanceReviewMultiple = {
  id: number;
  period: string;
  rating: number;
  strengths?: string | null;
  improvements?: string | null;
  goals?: any | null;
  status: 'Draft' | 'Shared';
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  employee?: EmployeeSingle;
  reviewer?: EmployeeSingle | null;
};

export type PerformanceReviewCreate = {
  period: string;
  rating: number;
  strengths?: string | null;
  improvements?: string | null;
  goals?: any | null;
  status?: 'Draft' | 'Shared';
  employee:
    | {
        id: string;
      }
    | string;
};

export type PerformanceReviewUpdate = {
  period?: string;
  rating?: number;
  strengths?: string | null;
  improvements?: string | null;
  goals?: any | null;
  status?: 'Draft' | 'Shared';
  employee?:
    | {
        id: string;
      }
    | string;
};

export type PerformanceReviewRelationCreate = {
  period: string;
  rating: number;
  strengths?: string | null;
  improvements?: string | null;
  goals?: any | null;
  status?: 'Draft' | 'Shared';
};

export type PerformanceReviewRelationUpdate = {
  id: number;
  period?: string;
  rating?: number;
  strengths?: string | null;
  improvements?: string | null;
  goals?: any | null;
  status?: 'Draft' | 'Shared';
};

export type PerformanceReviewRelationInput = {
  id?: number;
  period?: string;
  rating?: number;
  strengths?: string | null;
  improvements?: string | null;
  goals?: any | null;
  status?: 'Draft' | 'Shared';
};

export type PerformanceReviewQuery = QueryFilter<PerformanceReview>;

export type PerformanceReviewSort = QuerySort<PerformanceReviewMultiple>;

export type PerformanceReviewAggregate = AggregateSelect<PerformanceReview>;

export type PerformanceReviewResourceService = IResourceService<
  PerformanceReview,
  PerformanceReviewMultiple,
  PerformanceReviewCreate,
  PerformanceReviewUpdate,
  PerformanceReviewQuery
>;

export type Position = {
  id: number;
  title: string;
  level: 'Junior' | 'Mid' | 'Senior' | 'Lead' | 'Principal';
  salaryMin: number;
  salaryMax: number;
  openings: number;
  department: DepartmentSingle;
  employees?: Array<EmployeeSingle>;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
};

export type PositionSingle = {
  id: number;
  title: string;
  level: 'Junior' | 'Mid' | 'Senior' | 'Lead' | 'Principal';
  salaryMin: number;
  salaryMax: number;
  openings: number;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  department?: DepartmentSingle;
  employeesCount?: number;
};

export type PositionMultiple = {
  id: number;
  title: string;
  level: 'Junior' | 'Mid' | 'Senior' | 'Lead' | 'Principal';
  salaryMin: number;
  salaryMax: number;
  openings: number;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  department?: DepartmentSingle;
  employeesCount?: number;
};

export type PositionCreate = {
  title: string;
  level?: 'Junior' | 'Mid' | 'Senior' | 'Lead' | 'Principal';
  salaryMin: number;
  salaryMax: number;
  openings?: number;
  department:
    | {
        id: number;
      }
    | number;
};

export type PositionUpdate = {
  title?: string;
  level?: 'Junior' | 'Mid' | 'Senior' | 'Lead' | 'Principal';
  salaryMin?: number;
  salaryMax?: number;
  openings?: number;
  department?:
    | {
        id: number;
      }
    | number;
};

export type PositionRelationCreate = {
  title: string;
  level?: 'Junior' | 'Mid' | 'Senior' | 'Lead' | 'Principal';
  salaryMin: number;
  salaryMax: number;
  openings?: number;
};

export type PositionRelationUpdate = {
  id: number;
  title?: string;
  level?: 'Junior' | 'Mid' | 'Senior' | 'Lead' | 'Principal';
  salaryMin?: number;
  salaryMax?: number;
  openings?: number;
};

export type PositionRelationInput = {
  id?: number;
  title?: string;
  level?: 'Junior' | 'Mid' | 'Senior' | 'Lead' | 'Principal';
  salaryMin?: number;
  salaryMax?: number;
  openings?: number;
};

export type PositionQuery = QueryFilter<Position>;

export type PositionSort = QuerySort<PositionMultiple>;

export type PositionAggregate = AggregateSelect<Position>;

export type PositionResourceService = IResourceService<
  Position,
  PositionMultiple,
  PositionCreate,
  PositionUpdate,
  PositionQuery
>;

export type OneTimeToken = {
  id: number;
  tokenHash: string;
  purpose: string;
  data: any;
  expiresAt: Date;
  createdAt: Date;
};

export type OneTimeTokenSingle = {
  id: number;
  tokenHash: string;
  purpose: string;
  data: any;
  expiresAt: Date;
  createdAt: Date;
};

export type OneTimeTokenMultiple = {
  id: number;
  tokenHash: string;
  purpose: string;
  data: any;
  expiresAt: Date;
  createdAt: Date;
};

export type OneTimeTokenCreate = {
  tokenHash: string;
  purpose: string;
  data: any;
  expiresAt: Date;
};

export type OneTimeTokenUpdate = {
  tokenHash?: string;
  purpose?: string;
  data?: any;
  expiresAt?: Date;
};

export type OneTimeTokenRelationCreate = {
  tokenHash: string;
  purpose: string;
  data: any;
  expiresAt: Date;
};

export type OneTimeTokenRelationUpdate = {
  id: number;
  tokenHash?: string;
  purpose?: string;
  data?: any;
  expiresAt?: Date;
};

export type OneTimeTokenRelationInput = {
  id?: number;
  tokenHash?: string;
  purpose?: string;
  data?: any;
  expiresAt?: Date;
};

export type OneTimeTokenQuery = QueryFilter<OneTimeToken>;

export type OneTimeTokenSort = QuerySort<OneTimeTokenMultiple>;

export type OneTimeTokenAggregate = AggregateSelect<OneTimeToken>;

export type OneTimeTokenResourceService = IResourceService<
  OneTimeToken,
  OneTimeTokenMultiple,
  OneTimeTokenCreate,
  OneTimeTokenUpdate,
  OneTimeTokenQuery
>;

export type Role = {
  id: number;
  name: string;
  permissions: Array<PermissionSingle>;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
};

export type RoleSingle = {
  id: number;
  name: string;
  permissions?: Array<PermissionSingle>;
};

export type RoleMultiple = {
  id: number;
  name: string;
  permissions?: Array<PermissionSingle>;
};

export type RoleCreate = {
  name: string;
  permissions: Array<
    | {
        id: number;
      }
    | number
  >;
};

export type RoleUpdate = {
  name?: string;
  permissions?: Array<
    | {
        id: number;
      }
    | number
  >;
};

export type RoleRelationCreate = {
  name: string;
};

export type RoleRelationUpdate = {
  id: number;
  name?: string;
};

export type RoleRelationInput = {
  id?: number;
  name?: string;
};

export type RoleQuery = QueryFilter<Role>;

export type RoleSort = QuerySort<RoleMultiple>;

export type RoleAggregate = AggregateSelect<Role>;

export type RoleResourceService = IResourceService<
  Role,
  RoleMultiple,
  RoleCreate,
  RoleUpdate,
  RoleQuery
>;

export type Permission = {
  id: number;
  name: string;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
};

export type PermissionSingle = {
  id: number;
  name: string;
};

export type PermissionMultiple = {
  id: number;
  name: string;
};

export type PermissionCreate = {
  name: string;
};

export type PermissionUpdate = {
  name?: string;
};

export type PermissionRelationCreate = {
  name: string;
};

export type PermissionRelationUpdate = {
  id: number;
  name?: string;
};

export type PermissionRelationInput = {
  id?: number;
  name?: string;
};

export type PermissionQuery = QueryFilter<Permission>;

export type PermissionSort = QuerySort<PermissionMultiple>;

export type PermissionAggregate = AggregateSelect<Permission>;

export type PermissionResourceService = IResourceService<
  Permission,
  PermissionMultiple,
  PermissionCreate,
  PermissionUpdate,
  PermissionQuery
>;

export type File = {
  id: number;
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  checksum: string;
  title?: string | null;
  description?: string | null;
  resourceField?: string | null;
  resourceName?: string | null;
  resourceId?: string | null;
  url: string;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
  deletedAt?: Date | null;
  deletedById?: string | null;
};

export type FileSingle = {
  id: number;
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  checksum: string;
  title?: string | null;
  description?: string | null;
  url: string;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
};

export type FileMultiple = {
  id: number;
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  checksum: string;
  title?: string | null;
  description?: string | null;
  url: string;
  updatedAt: Date;
  createdAt: Date;
  createdById?: string | null;
};

export type FileCreate = {
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  checksum: string;
  title?: string | null;
  description?: string | null;
};

export type FileUpdate = {
  name?: string;
  originalName?: string;
  mimeType?: string;
  sizeBytes?: number;
  checksum?: string;
  title?: string | null;
  description?: string | null;
};

export type FileRelationCreate = {
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  checksum: string;
  title?: string | null;
  description?: string | null;
};

export type FileRelationUpdate = {
  id: number;
  name?: string;
  originalName?: string;
  mimeType?: string;
  sizeBytes?: number;
  checksum?: string;
  title?: string | null;
  description?: string | null;
};

export type FileRelationInput = {
  id?: number;
  name?: string;
  originalName?: string;
  mimeType?: string;
  sizeBytes?: number;
  checksum?: string;
  title?: string | null;
  description?: string | null;
};

export type FileQuery = QueryFilter<File>;

export type FileSort = QuerySort<FileMultiple>;

export type FileAggregate = AggregateSelect<File>;

export type FileResourceService = IResourceService<
  File,
  FileMultiple,
  FileCreate,
  FileUpdate,
  FileQuery
>;

declare module '@appweaver/common' {
  interface ResourceRegistry {
    Compensation: {
      model: Compensation;
      single: CompensationSingle;
      multiple: CompensationMultiple;
      create: CompensationCreate;
      update: CompensationUpdate;
      query: CompensationQuery;
      service: CompensationResourceService;
      relations: 'employee';
    };
    Department: {
      model: Department;
      single: DepartmentSingle;
      multiple: DepartmentMultiple;
      create: DepartmentCreate;
      update: DepartmentUpdate;
      query: DepartmentQuery;
      service: DepartmentResourceService;
      relations: 'head' | 'employees' | 'positions';
    };
    EmployeeDocument: {
      model: EmployeeDocument;
      single: EmployeeDocumentSingle;
      multiple: EmployeeDocumentMultiple;
      create: EmployeeDocumentCreate;
      update: EmployeeDocumentUpdate;
      query: EmployeeDocumentQuery;
      service: EmployeeDocumentResourceService;
      relations: 'employee';
    };
    Employee: {
      model: Employee;
      single: EmployeeSingle;
      multiple: EmployeeMultiple;
      create: EmployeeCreate;
      update: EmployeeUpdate;
      query: EmployeeQuery;
      service: EmployeeResourceService;
      relations:
        | 'department'
        | 'position'
        | 'manager'
        | 'reports'
        | 'headOf'
        | 'leaveBalances'
        | 'leaveRequests'
        | 'decidedLeaveRequests'
        | 'documents'
        | 'compensations'
        | 'reviews'
        | 'writtenReviews'
        | 'roles';
    };
    LeaveBalance: {
      model: LeaveBalance;
      single: LeaveBalanceSingle;
      multiple: LeaveBalanceMultiple;
      create: LeaveBalanceCreate;
      update: LeaveBalanceUpdate;
      query: LeaveBalanceQuery;
      service: LeaveBalanceResourceService;
      relations: 'employee';
    };
    LeaveRequest: {
      model: LeaveRequest;
      single: LeaveRequestSingle;
      multiple: LeaveRequestMultiple;
      create: LeaveRequestCreate;
      update: LeaveRequestUpdate;
      query: LeaveRequestQuery;
      service: LeaveRequestResourceService;
      relations: 'employee' | 'decidedBy';
    };
    PerformanceReview: {
      model: PerformanceReview;
      single: PerformanceReviewSingle;
      multiple: PerformanceReviewMultiple;
      create: PerformanceReviewCreate;
      update: PerformanceReviewUpdate;
      query: PerformanceReviewQuery;
      service: PerformanceReviewResourceService;
      relations: 'employee' | 'reviewer';
    };
    Position: {
      model: Position;
      single: PositionSingle;
      multiple: PositionMultiple;
      create: PositionCreate;
      update: PositionUpdate;
      query: PositionQuery;
      service: PositionResourceService;
      relations: 'department' | 'employees';
    };
    OneTimeToken: {
      model: OneTimeToken;
      single: OneTimeTokenSingle;
      multiple: OneTimeTokenMultiple;
      create: OneTimeTokenCreate;
      update: OneTimeTokenUpdate;
      query: OneTimeTokenQuery;
      service: OneTimeTokenResourceService;
      relations: never;
    };
    Role: {
      model: Role;
      single: RoleSingle;
      multiple: RoleMultiple;
      create: RoleCreate;
      update: RoleUpdate;
      query: RoleQuery;
      service: RoleResourceService;
      relations: 'permissions';
    };
    Permission: {
      model: Permission;
      single: PermissionSingle;
      multiple: PermissionMultiple;
      create: PermissionCreate;
      update: PermissionUpdate;
      query: PermissionQuery;
      service: PermissionResourceService;
      relations: never;
    };
    Seeder: {
      model: any;
      single: any;
      multiple: any;
      create: any;
      update: any;
      query: any;
      service: IResourceService;
      relations: string;
    };
    File: {
      model: File;
      single: FileSingle;
      multiple: FileMultiple;
      create: FileCreate;
      update: FileUpdate;
      query: FileQuery;
      service: FileResourceService;
      relations: never;
    };
  }
}
