// Generated by Appweaver. Please do not edit this file manually.

export type User = {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  updatedAt: Date;
  createdAt: Date;
  createdById?: number | null;
  posts: Array<Post>;
  avatar?: File | null;
};

export type UserMultiple = {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  updatedAt: Date;
  createdAt: Date;
  createdById?: number | null;
  posts: Array<Post>;
  avatar?: File | null;
};

export type UserCreate = {
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  posts:
    | Array<{
        id: number;
      }>
    | Array<number>;
};

export type UserUpdate = {
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  posts?:
    | Array<{
        id: number;
      }>
    | Array<number>;
};

export type Post = {
  id: number;
  title: string;
  slug: string;
  content?: string | null;
  counter: number;
  status?: ('Draft' | 'Published' | 'Archived') | null;
  lastActivity?: Date | null;
  updatedAt: Date;
  createdAt: Date;
  createdById?: number | null;
  author?: User | null;
  authorCount: number;
  coverImage?: File | null;
  galleryImages: Array<File>;
  galleryImagesCount: number;
};

export type PostMultiple = {
  id: number;
  title: string;
  slug: string;
  content?: string | null;
  counter: number;
  status?: ('Draft' | 'Published' | 'Archived') | null;
  lastActivity?: Date | null;
  updatedAt: Date;
  createdAt: Date;
  createdById?: number | null;
  author?: User | null;
  authorCount: number;
  coverImage?: File | null;
  galleryImagesCount: number;
};

export type PostCreate = {
  title: string;
  slug: string;
  content?: string | null;
  status?: ('Draft' | 'Published' | 'Archived') | null;
  lastActivity?: Date | null;
};

export type PostUpdate = {
  title?: string;
  content?: string | null;
};

export type Identity = {
  id: number;
  username: string;
  enabled: boolean;
  logoutAt?: Date | null;
  createdAt: Date;
  updatedAt: Date;
  createdById?: number | null;
  roles: Array<Role>;
};

export type IdentityMultiple = {
  id: number;
  username: string;
  enabled: boolean;
  logoutAt?: Date | null;
  createdAt: Date;
  updatedAt: Date;
  createdById?: number | null;
  roles: Array<Role>;
};

export type IdentityCreate = {
  username: string;
  enabled: boolean;
  logoutAt?: Date | null;
  roles:
    | Array<{
        id: number;
      }>
    | Array<number>;
};

export type IdentityUpdate = {
  username?: string;
  enabled?: boolean;
  logoutAt?: Date | null;
  roles?:
    | Array<{
        id: number;
      }>
    | Array<number>;
};

export type Role = {
  id: number;
  name: string;
  createdAt: Date;
  updatedAt: Date;
  createdById?: number | null;
  permissions: Array<Permission>;
};

export type RoleMultiple = {
  id: number;
  name: string;
  createdAt: Date;
  updatedAt: Date;
  createdById?: number | null;
  permissions: Array<Permission>;
};

export type RoleCreate = {
  name: string;
  permissions:
    | Array<{
        id: number;
      }>
    | Array<number>;
};

export type RoleUpdate = {
  name?: string;
  permissions?:
    | Array<{
        id: number;
      }>
    | Array<number>;
};

export type Permission = {
  id: number;
  name: string;
  createdAt: Date;
  updatedAt: Date;
  createdById?: number | null;
};

export type PermissionMultiple = {
  id: number;
  name: string;
  createdAt: Date;
  updatedAt: Date;
  createdById?: number | null;
};

export type PermissionCreate = {
  name: string;
};

export type PermissionUpdate = {
  name?: string;
};

export type File = {
  id: number;
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  title?: string | null;
  description?: string | null;
  createdAt: Date;
  updatedAt: Date;
  createdById?: number | null;
};

export type FileMultiple = {
  id: number;
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  title?: string | null;
  description?: string | null;
  createdAt: Date;
  updatedAt: Date;
  createdById?: number | null;
};

export type FileCreate = {
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  title?: string | null;
  description?: string | null;
};

export type FileUpdate = {
  name?: string;
  originalName?: string;
  mimeType?: string;
  sizeBytes?: number;
  title?: string | null;
  description?: string | null;
};
