
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `File` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model File
 * 
 */
export type FileModel = runtime.Types.Result.DefaultSelection<Prisma.$FilePayload>

export type AggregateFile = {
  _count: FileCountAggregateOutputType | null
  _avg: FileAvgAggregateOutputType | null
  _sum: FileSumAggregateOutputType | null
  _min: FileMinAggregateOutputType | null
  _max: FileMaxAggregateOutputType | null
}

export type FileAvgAggregateOutputType = {
  id: number | null
  sizeBytes: number | null
  resourceId: number | null
  createdById: number | null
}

export type FileSumAggregateOutputType = {
  id: number | null
  sizeBytes: number | null
  resourceId: number | null
  createdById: number | null
}

export type FileMinAggregateOutputType = {
  id: number | null
  name: string | null
  originalName: string | null
  mimeType: string | null
  sizeBytes: number | null
  title: string | null
  description: string | null
  resourceField: string | null
  resourceName: string | null
  resourceId: number | null
  updatedAt: Date | null
  createdAt: Date | null
  createdById: number | null
}

export type FileMaxAggregateOutputType = {
  id: number | null
  name: string | null
  originalName: string | null
  mimeType: string | null
  sizeBytes: number | null
  title: string | null
  description: string | null
  resourceField: string | null
  resourceName: string | null
  resourceId: number | null
  updatedAt: Date | null
  createdAt: Date | null
  createdById: number | null
}

export type FileCountAggregateOutputType = {
  id: number
  name: number
  originalName: number
  mimeType: number
  sizeBytes: number
  title: number
  description: number
  resourceField: number
  resourceName: number
  resourceId: number
  updatedAt: number
  createdAt: number
  createdById: number
  _all: number
}


export type FileAvgAggregateInputType = {
  id?: true
  sizeBytes?: true
  resourceId?: true
  createdById?: true
}

export type FileSumAggregateInputType = {
  id?: true
  sizeBytes?: true
  resourceId?: true
  createdById?: true
}

export type FileMinAggregateInputType = {
  id?: true
  name?: true
  originalName?: true
  mimeType?: true
  sizeBytes?: true
  title?: true
  description?: true
  resourceField?: true
  resourceName?: true
  resourceId?: true
  updatedAt?: true
  createdAt?: true
  createdById?: true
}

export type FileMaxAggregateInputType = {
  id?: true
  name?: true
  originalName?: true
  mimeType?: true
  sizeBytes?: true
  title?: true
  description?: true
  resourceField?: true
  resourceName?: true
  resourceId?: true
  updatedAt?: true
  createdAt?: true
  createdById?: true
}

export type FileCountAggregateInputType = {
  id?: true
  name?: true
  originalName?: true
  mimeType?: true
  sizeBytes?: true
  title?: true
  description?: true
  resourceField?: true
  resourceName?: true
  resourceId?: true
  updatedAt?: true
  createdAt?: true
  createdById?: true
  _all?: true
}

export type FileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which File to aggregate.
   */
  where?: Prisma.FileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Files to fetch.
   */
  orderBy?: Prisma.FileOrderByWithRelationInput | Prisma.FileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Files from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Files.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Files
  **/
  _count?: true | FileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FileAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FileSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FileMaxAggregateInputType
}

export type GetFileAggregateType<T extends FileAggregateArgs> = {
      [P in keyof T & keyof AggregateFile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFile[P]>
    : Prisma.GetScalarType<T[P], AggregateFile[P]>
}




export type FileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FileWhereInput
  orderBy?: Prisma.FileOrderByWithAggregationInput | Prisma.FileOrderByWithAggregationInput[]
  by: Prisma.FileScalarFieldEnum[] | Prisma.FileScalarFieldEnum
  having?: Prisma.FileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FileCountAggregateInputType | true
  _avg?: FileAvgAggregateInputType
  _sum?: FileSumAggregateInputType
  _min?: FileMinAggregateInputType
  _max?: FileMaxAggregateInputType
}

export type FileGroupByOutputType = {
  id: number
  name: string
  originalName: string
  mimeType: string
  sizeBytes: number
  title: string | null
  description: string | null
  resourceField: string | null
  resourceName: string | null
  resourceId: number | null
  updatedAt: Date
  createdAt: Date
  createdById: number | null
  _count: FileCountAggregateOutputType | null
  _avg: FileAvgAggregateOutputType | null
  _sum: FileSumAggregateOutputType | null
  _min: FileMinAggregateOutputType | null
  _max: FileMaxAggregateOutputType | null
}

export type GetFileGroupByPayload<T extends FileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FileGroupByOutputType[P]>
      }
    >
  >



export type FileWhereInput = {
  AND?: Prisma.FileWhereInput | Prisma.FileWhereInput[]
  OR?: Prisma.FileWhereInput[]
  NOT?: Prisma.FileWhereInput | Prisma.FileWhereInput[]
  id?: Prisma.IntFilter<"File"> | number
  name?: Prisma.StringFilter<"File"> | string
  originalName?: Prisma.StringFilter<"File"> | string
  mimeType?: Prisma.StringFilter<"File"> | string
  sizeBytes?: Prisma.IntFilter<"File"> | number
  title?: Prisma.StringNullableFilter<"File"> | string | null
  description?: Prisma.StringNullableFilter<"File"> | string | null
  resourceField?: Prisma.StringNullableFilter<"File"> | string | null
  resourceName?: Prisma.StringNullableFilter<"File"> | string | null
  resourceId?: Prisma.IntNullableFilter<"File"> | number | null
  updatedAt?: Prisma.DateTimeFilter<"File"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"File"> | Date | string
  createdById?: Prisma.IntNullableFilter<"File"> | number | null
  coverImagePosts?: Prisma.PostListRelationFilter
  galleryImagesPosts?: Prisma.PostListRelationFilter
  avatarUsers?: Prisma.UserListRelationFilter
  createdBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type FileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  originalName?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  resourceField?: Prisma.SortOrderInput | Prisma.SortOrder
  resourceName?: Prisma.SortOrderInput | Prisma.SortOrder
  resourceId?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrderInput | Prisma.SortOrder
  coverImagePosts?: Prisma.PostOrderByRelationAggregateInput
  galleryImagesPosts?: Prisma.PostOrderByRelationAggregateInput
  avatarUsers?: Prisma.UserOrderByRelationAggregateInput
  createdBy?: Prisma.UserOrderByWithRelationInput
}

export type FileWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  name?: string
  AND?: Prisma.FileWhereInput | Prisma.FileWhereInput[]
  OR?: Prisma.FileWhereInput[]
  NOT?: Prisma.FileWhereInput | Prisma.FileWhereInput[]
  originalName?: Prisma.StringFilter<"File"> | string
  mimeType?: Prisma.StringFilter<"File"> | string
  sizeBytes?: Prisma.IntFilter<"File"> | number
  title?: Prisma.StringNullableFilter<"File"> | string | null
  description?: Prisma.StringNullableFilter<"File"> | string | null
  resourceField?: Prisma.StringNullableFilter<"File"> | string | null
  resourceName?: Prisma.StringNullableFilter<"File"> | string | null
  resourceId?: Prisma.IntNullableFilter<"File"> | number | null
  updatedAt?: Prisma.DateTimeFilter<"File"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"File"> | Date | string
  createdById?: Prisma.IntNullableFilter<"File"> | number | null
  coverImagePosts?: Prisma.PostListRelationFilter
  galleryImagesPosts?: Prisma.PostListRelationFilter
  avatarUsers?: Prisma.UserListRelationFilter
  createdBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id" | "name">

export type FileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  originalName?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  resourceField?: Prisma.SortOrderInput | Prisma.SortOrder
  resourceName?: Prisma.SortOrderInput | Prisma.SortOrder
  resourceId?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.FileCountOrderByAggregateInput
  _avg?: Prisma.FileAvgOrderByAggregateInput
  _max?: Prisma.FileMaxOrderByAggregateInput
  _min?: Prisma.FileMinOrderByAggregateInput
  _sum?: Prisma.FileSumOrderByAggregateInput
}

export type FileScalarWhereWithAggregatesInput = {
  AND?: Prisma.FileScalarWhereWithAggregatesInput | Prisma.FileScalarWhereWithAggregatesInput[]
  OR?: Prisma.FileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FileScalarWhereWithAggregatesInput | Prisma.FileScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"File"> | number
  name?: Prisma.StringWithAggregatesFilter<"File"> | string
  originalName?: Prisma.StringWithAggregatesFilter<"File"> | string
  mimeType?: Prisma.StringWithAggregatesFilter<"File"> | string
  sizeBytes?: Prisma.IntWithAggregatesFilter<"File"> | number
  title?: Prisma.StringNullableWithAggregatesFilter<"File"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"File"> | string | null
  resourceField?: Prisma.StringNullableWithAggregatesFilter<"File"> | string | null
  resourceName?: Prisma.StringNullableWithAggregatesFilter<"File"> | string | null
  resourceId?: Prisma.IntNullableWithAggregatesFilter<"File"> | number | null
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"File"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"File"> | Date | string
  createdById?: Prisma.IntNullableWithAggregatesFilter<"File"> | number | null
}

export type FileCreateInput = {
  name: string
  originalName: string
  mimeType: string
  sizeBytes: number
  title?: string | null
  description?: string | null
  resourceField?: string | null
  resourceName?: string | null
  resourceId?: number | null
  updatedAt?: Date | string
  createdAt?: Date | string
  coverImagePosts?: Prisma.PostCreateNestedManyWithoutCoverImageInput
  galleryImagesPosts?: Prisma.PostCreateNestedManyWithoutGalleryImagesInput
  avatarUsers?: Prisma.UserCreateNestedManyWithoutAvatarInput
  createdBy?: Prisma.UserCreateNestedOneWithoutCreatedFilesInput
}

export type FileUncheckedCreateInput = {
  id?: number
  name: string
  originalName: string
  mimeType: string
  sizeBytes: number
  title?: string | null
  description?: string | null
  resourceField?: string | null
  resourceName?: string | null
  resourceId?: number | null
  updatedAt?: Date | string
  createdAt?: Date | string
  createdById?: number | null
  coverImagePosts?: Prisma.PostUncheckedCreateNestedManyWithoutCoverImageInput
  galleryImagesPosts?: Prisma.PostUncheckedCreateNestedManyWithoutGalleryImagesInput
  avatarUsers?: Prisma.UserUncheckedCreateNestedManyWithoutAvatarInput
}

export type FileUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceField?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverImagePosts?: Prisma.PostUpdateManyWithoutCoverImageNestedInput
  galleryImagesPosts?: Prisma.PostUpdateManyWithoutGalleryImagesNestedInput
  avatarUsers?: Prisma.UserUpdateManyWithoutAvatarNestedInput
  createdBy?: Prisma.UserUpdateOneWithoutCreatedFilesNestedInput
}

export type FileUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceField?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  coverImagePosts?: Prisma.PostUncheckedUpdateManyWithoutCoverImageNestedInput
  galleryImagesPosts?: Prisma.PostUncheckedUpdateManyWithoutGalleryImagesNestedInput
  avatarUsers?: Prisma.UserUncheckedUpdateManyWithoutAvatarNestedInput
}

export type FileCreateManyInput = {
  id?: number
  name: string
  originalName: string
  mimeType: string
  sizeBytes: number
  title?: string | null
  description?: string | null
  resourceField?: string | null
  resourceName?: string | null
  resourceId?: number | null
  updatedAt?: Date | string
  createdAt?: Date | string
  createdById?: number | null
}

export type FileUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceField?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FileUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceField?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type FileNullableScalarRelationFilter = {
  is?: Prisma.FileWhereInput | null
  isNot?: Prisma.FileWhereInput | null
}

export type FileListRelationFilter = {
  every?: Prisma.FileWhereInput
  some?: Prisma.FileWhereInput
  none?: Prisma.FileWhereInput
}

export type FileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  originalName?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  resourceField?: Prisma.SortOrder
  resourceName?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type FileAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type FileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  originalName?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  resourceField?: Prisma.SortOrder
  resourceName?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type FileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  originalName?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  resourceField?: Prisma.SortOrder
  resourceName?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type FileSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type FileCreateNestedOneWithoutCoverImagePostsInput = {
  create?: Prisma.XOR<Prisma.FileCreateWithoutCoverImagePostsInput, Prisma.FileUncheckedCreateWithoutCoverImagePostsInput>
  connectOrCreate?: Prisma.FileCreateOrConnectWithoutCoverImagePostsInput
  connect?: Prisma.FileWhereUniqueInput
}

export type FileCreateNestedManyWithoutGalleryImagesPostsInput = {
  create?: Prisma.XOR<Prisma.FileCreateWithoutGalleryImagesPostsInput, Prisma.FileUncheckedCreateWithoutGalleryImagesPostsInput> | Prisma.FileCreateWithoutGalleryImagesPostsInput[] | Prisma.FileUncheckedCreateWithoutGalleryImagesPostsInput[]
  connectOrCreate?: Prisma.FileCreateOrConnectWithoutGalleryImagesPostsInput | Prisma.FileCreateOrConnectWithoutGalleryImagesPostsInput[]
  connect?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
}

export type FileUncheckedCreateNestedManyWithoutGalleryImagesPostsInput = {
  create?: Prisma.XOR<Prisma.FileCreateWithoutGalleryImagesPostsInput, Prisma.FileUncheckedCreateWithoutGalleryImagesPostsInput> | Prisma.FileCreateWithoutGalleryImagesPostsInput[] | Prisma.FileUncheckedCreateWithoutGalleryImagesPostsInput[]
  connectOrCreate?: Prisma.FileCreateOrConnectWithoutGalleryImagesPostsInput | Prisma.FileCreateOrConnectWithoutGalleryImagesPostsInput[]
  connect?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
}

export type FileUpdateOneWithoutCoverImagePostsNestedInput = {
  create?: Prisma.XOR<Prisma.FileCreateWithoutCoverImagePostsInput, Prisma.FileUncheckedCreateWithoutCoverImagePostsInput>
  connectOrCreate?: Prisma.FileCreateOrConnectWithoutCoverImagePostsInput
  upsert?: Prisma.FileUpsertWithoutCoverImagePostsInput
  disconnect?: Prisma.FileWhereInput | boolean
  delete?: Prisma.FileWhereInput | boolean
  connect?: Prisma.FileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FileUpdateToOneWithWhereWithoutCoverImagePostsInput, Prisma.FileUpdateWithoutCoverImagePostsInput>, Prisma.FileUncheckedUpdateWithoutCoverImagePostsInput>
}

export type FileUpdateManyWithoutGalleryImagesPostsNestedInput = {
  create?: Prisma.XOR<Prisma.FileCreateWithoutGalleryImagesPostsInput, Prisma.FileUncheckedCreateWithoutGalleryImagesPostsInput> | Prisma.FileCreateWithoutGalleryImagesPostsInput[] | Prisma.FileUncheckedCreateWithoutGalleryImagesPostsInput[]
  connectOrCreate?: Prisma.FileCreateOrConnectWithoutGalleryImagesPostsInput | Prisma.FileCreateOrConnectWithoutGalleryImagesPostsInput[]
  upsert?: Prisma.FileUpsertWithWhereUniqueWithoutGalleryImagesPostsInput | Prisma.FileUpsertWithWhereUniqueWithoutGalleryImagesPostsInput[]
  set?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
  disconnect?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
  delete?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
  connect?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
  update?: Prisma.FileUpdateWithWhereUniqueWithoutGalleryImagesPostsInput | Prisma.FileUpdateWithWhereUniqueWithoutGalleryImagesPostsInput[]
  updateMany?: Prisma.FileUpdateManyWithWhereWithoutGalleryImagesPostsInput | Prisma.FileUpdateManyWithWhereWithoutGalleryImagesPostsInput[]
  deleteMany?: Prisma.FileScalarWhereInput | Prisma.FileScalarWhereInput[]
}

export type FileUncheckedUpdateManyWithoutGalleryImagesPostsNestedInput = {
  create?: Prisma.XOR<Prisma.FileCreateWithoutGalleryImagesPostsInput, Prisma.FileUncheckedCreateWithoutGalleryImagesPostsInput> | Prisma.FileCreateWithoutGalleryImagesPostsInput[] | Prisma.FileUncheckedCreateWithoutGalleryImagesPostsInput[]
  connectOrCreate?: Prisma.FileCreateOrConnectWithoutGalleryImagesPostsInput | Prisma.FileCreateOrConnectWithoutGalleryImagesPostsInput[]
  upsert?: Prisma.FileUpsertWithWhereUniqueWithoutGalleryImagesPostsInput | Prisma.FileUpsertWithWhereUniqueWithoutGalleryImagesPostsInput[]
  set?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
  disconnect?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
  delete?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
  connect?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
  update?: Prisma.FileUpdateWithWhereUniqueWithoutGalleryImagesPostsInput | Prisma.FileUpdateWithWhereUniqueWithoutGalleryImagesPostsInput[]
  updateMany?: Prisma.FileUpdateManyWithWhereWithoutGalleryImagesPostsInput | Prisma.FileUpdateManyWithWhereWithoutGalleryImagesPostsInput[]
  deleteMany?: Prisma.FileScalarWhereInput | Prisma.FileScalarWhereInput[]
}

export type FileCreateNestedOneWithoutAvatarUsersInput = {
  create?: Prisma.XOR<Prisma.FileCreateWithoutAvatarUsersInput, Prisma.FileUncheckedCreateWithoutAvatarUsersInput>
  connectOrCreate?: Prisma.FileCreateOrConnectWithoutAvatarUsersInput
  connect?: Prisma.FileWhereUniqueInput
}

export type FileCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.FileCreateWithoutCreatedByInput, Prisma.FileUncheckedCreateWithoutCreatedByInput> | Prisma.FileCreateWithoutCreatedByInput[] | Prisma.FileUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.FileCreateOrConnectWithoutCreatedByInput | Prisma.FileCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.FileCreateManyCreatedByInputEnvelope
  connect?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
}

export type FileUncheckedCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.FileCreateWithoutCreatedByInput, Prisma.FileUncheckedCreateWithoutCreatedByInput> | Prisma.FileCreateWithoutCreatedByInput[] | Prisma.FileUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.FileCreateOrConnectWithoutCreatedByInput | Prisma.FileCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.FileCreateManyCreatedByInputEnvelope
  connect?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
}

export type FileUpdateOneWithoutAvatarUsersNestedInput = {
  create?: Prisma.XOR<Prisma.FileCreateWithoutAvatarUsersInput, Prisma.FileUncheckedCreateWithoutAvatarUsersInput>
  connectOrCreate?: Prisma.FileCreateOrConnectWithoutAvatarUsersInput
  upsert?: Prisma.FileUpsertWithoutAvatarUsersInput
  disconnect?: Prisma.FileWhereInput | boolean
  delete?: Prisma.FileWhereInput | boolean
  connect?: Prisma.FileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FileUpdateToOneWithWhereWithoutAvatarUsersInput, Prisma.FileUpdateWithoutAvatarUsersInput>, Prisma.FileUncheckedUpdateWithoutAvatarUsersInput>
}

export type FileUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.FileCreateWithoutCreatedByInput, Prisma.FileUncheckedCreateWithoutCreatedByInput> | Prisma.FileCreateWithoutCreatedByInput[] | Prisma.FileUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.FileCreateOrConnectWithoutCreatedByInput | Prisma.FileCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.FileUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.FileUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.FileCreateManyCreatedByInputEnvelope
  set?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
  disconnect?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
  delete?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
  connect?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
  update?: Prisma.FileUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.FileUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.FileUpdateManyWithWhereWithoutCreatedByInput | Prisma.FileUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.FileScalarWhereInput | Prisma.FileScalarWhereInput[]
}

export type FileUncheckedUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.FileCreateWithoutCreatedByInput, Prisma.FileUncheckedCreateWithoutCreatedByInput> | Prisma.FileCreateWithoutCreatedByInput[] | Prisma.FileUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.FileCreateOrConnectWithoutCreatedByInput | Prisma.FileCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.FileUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.FileUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.FileCreateManyCreatedByInputEnvelope
  set?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
  disconnect?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
  delete?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
  connect?: Prisma.FileWhereUniqueInput | Prisma.FileWhereUniqueInput[]
  update?: Prisma.FileUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.FileUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.FileUpdateManyWithWhereWithoutCreatedByInput | Prisma.FileUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.FileScalarWhereInput | Prisma.FileScalarWhereInput[]
}

export type FileCreateWithoutCoverImagePostsInput = {
  name: string
  originalName: string
  mimeType: string
  sizeBytes: number
  title?: string | null
  description?: string | null
  resourceField?: string | null
  resourceName?: string | null
  resourceId?: number | null
  updatedAt?: Date | string
  createdAt?: Date | string
  galleryImagesPosts?: Prisma.PostCreateNestedManyWithoutGalleryImagesInput
  avatarUsers?: Prisma.UserCreateNestedManyWithoutAvatarInput
  createdBy?: Prisma.UserCreateNestedOneWithoutCreatedFilesInput
}

export type FileUncheckedCreateWithoutCoverImagePostsInput = {
  id?: number
  name: string
  originalName: string
  mimeType: string
  sizeBytes: number
  title?: string | null
  description?: string | null
  resourceField?: string | null
  resourceName?: string | null
  resourceId?: number | null
  updatedAt?: Date | string
  createdAt?: Date | string
  createdById?: number | null
  galleryImagesPosts?: Prisma.PostUncheckedCreateNestedManyWithoutGalleryImagesInput
  avatarUsers?: Prisma.UserUncheckedCreateNestedManyWithoutAvatarInput
}

export type FileCreateOrConnectWithoutCoverImagePostsInput = {
  where: Prisma.FileWhereUniqueInput
  create: Prisma.XOR<Prisma.FileCreateWithoutCoverImagePostsInput, Prisma.FileUncheckedCreateWithoutCoverImagePostsInput>
}

export type FileCreateWithoutGalleryImagesPostsInput = {
  name: string
  originalName: string
  mimeType: string
  sizeBytes: number
  title?: string | null
  description?: string | null
  resourceField?: string | null
  resourceName?: string | null
  resourceId?: number | null
  updatedAt?: Date | string
  createdAt?: Date | string
  coverImagePosts?: Prisma.PostCreateNestedManyWithoutCoverImageInput
  avatarUsers?: Prisma.UserCreateNestedManyWithoutAvatarInput
  createdBy?: Prisma.UserCreateNestedOneWithoutCreatedFilesInput
}

export type FileUncheckedCreateWithoutGalleryImagesPostsInput = {
  id?: number
  name: string
  originalName: string
  mimeType: string
  sizeBytes: number
  title?: string | null
  description?: string | null
  resourceField?: string | null
  resourceName?: string | null
  resourceId?: number | null
  updatedAt?: Date | string
  createdAt?: Date | string
  createdById?: number | null
  coverImagePosts?: Prisma.PostUncheckedCreateNestedManyWithoutCoverImageInput
  avatarUsers?: Prisma.UserUncheckedCreateNestedManyWithoutAvatarInput
}

export type FileCreateOrConnectWithoutGalleryImagesPostsInput = {
  where: Prisma.FileWhereUniqueInput
  create: Prisma.XOR<Prisma.FileCreateWithoutGalleryImagesPostsInput, Prisma.FileUncheckedCreateWithoutGalleryImagesPostsInput>
}

export type FileUpsertWithoutCoverImagePostsInput = {
  update: Prisma.XOR<Prisma.FileUpdateWithoutCoverImagePostsInput, Prisma.FileUncheckedUpdateWithoutCoverImagePostsInput>
  create: Prisma.XOR<Prisma.FileCreateWithoutCoverImagePostsInput, Prisma.FileUncheckedCreateWithoutCoverImagePostsInput>
  where?: Prisma.FileWhereInput
}

export type FileUpdateToOneWithWhereWithoutCoverImagePostsInput = {
  where?: Prisma.FileWhereInput
  data: Prisma.XOR<Prisma.FileUpdateWithoutCoverImagePostsInput, Prisma.FileUncheckedUpdateWithoutCoverImagePostsInput>
}

export type FileUpdateWithoutCoverImagePostsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceField?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  galleryImagesPosts?: Prisma.PostUpdateManyWithoutGalleryImagesNestedInput
  avatarUsers?: Prisma.UserUpdateManyWithoutAvatarNestedInput
  createdBy?: Prisma.UserUpdateOneWithoutCreatedFilesNestedInput
}

export type FileUncheckedUpdateWithoutCoverImagePostsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceField?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  galleryImagesPosts?: Prisma.PostUncheckedUpdateManyWithoutGalleryImagesNestedInput
  avatarUsers?: Prisma.UserUncheckedUpdateManyWithoutAvatarNestedInput
}

export type FileUpsertWithWhereUniqueWithoutGalleryImagesPostsInput = {
  where: Prisma.FileWhereUniqueInput
  update: Prisma.XOR<Prisma.FileUpdateWithoutGalleryImagesPostsInput, Prisma.FileUncheckedUpdateWithoutGalleryImagesPostsInput>
  create: Prisma.XOR<Prisma.FileCreateWithoutGalleryImagesPostsInput, Prisma.FileUncheckedCreateWithoutGalleryImagesPostsInput>
}

export type FileUpdateWithWhereUniqueWithoutGalleryImagesPostsInput = {
  where: Prisma.FileWhereUniqueInput
  data: Prisma.XOR<Prisma.FileUpdateWithoutGalleryImagesPostsInput, Prisma.FileUncheckedUpdateWithoutGalleryImagesPostsInput>
}

export type FileUpdateManyWithWhereWithoutGalleryImagesPostsInput = {
  where: Prisma.FileScalarWhereInput
  data: Prisma.XOR<Prisma.FileUpdateManyMutationInput, Prisma.FileUncheckedUpdateManyWithoutGalleryImagesPostsInput>
}

export type FileScalarWhereInput = {
  AND?: Prisma.FileScalarWhereInput | Prisma.FileScalarWhereInput[]
  OR?: Prisma.FileScalarWhereInput[]
  NOT?: Prisma.FileScalarWhereInput | Prisma.FileScalarWhereInput[]
  id?: Prisma.IntFilter<"File"> | number
  name?: Prisma.StringFilter<"File"> | string
  originalName?: Prisma.StringFilter<"File"> | string
  mimeType?: Prisma.StringFilter<"File"> | string
  sizeBytes?: Prisma.IntFilter<"File"> | number
  title?: Prisma.StringNullableFilter<"File"> | string | null
  description?: Prisma.StringNullableFilter<"File"> | string | null
  resourceField?: Prisma.StringNullableFilter<"File"> | string | null
  resourceName?: Prisma.StringNullableFilter<"File"> | string | null
  resourceId?: Prisma.IntNullableFilter<"File"> | number | null
  updatedAt?: Prisma.DateTimeFilter<"File"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"File"> | Date | string
  createdById?: Prisma.IntNullableFilter<"File"> | number | null
}

export type FileCreateWithoutAvatarUsersInput = {
  name: string
  originalName: string
  mimeType: string
  sizeBytes: number
  title?: string | null
  description?: string | null
  resourceField?: string | null
  resourceName?: string | null
  resourceId?: number | null
  updatedAt?: Date | string
  createdAt?: Date | string
  coverImagePosts?: Prisma.PostCreateNestedManyWithoutCoverImageInput
  galleryImagesPosts?: Prisma.PostCreateNestedManyWithoutGalleryImagesInput
  createdBy?: Prisma.UserCreateNestedOneWithoutCreatedFilesInput
}

export type FileUncheckedCreateWithoutAvatarUsersInput = {
  id?: number
  name: string
  originalName: string
  mimeType: string
  sizeBytes: number
  title?: string | null
  description?: string | null
  resourceField?: string | null
  resourceName?: string | null
  resourceId?: number | null
  updatedAt?: Date | string
  createdAt?: Date | string
  createdById?: number | null
  coverImagePosts?: Prisma.PostUncheckedCreateNestedManyWithoutCoverImageInput
  galleryImagesPosts?: Prisma.PostUncheckedCreateNestedManyWithoutGalleryImagesInput
}

export type FileCreateOrConnectWithoutAvatarUsersInput = {
  where: Prisma.FileWhereUniqueInput
  create: Prisma.XOR<Prisma.FileCreateWithoutAvatarUsersInput, Prisma.FileUncheckedCreateWithoutAvatarUsersInput>
}

export type FileCreateWithoutCreatedByInput = {
  name: string
  originalName: string
  mimeType: string
  sizeBytes: number
  title?: string | null
  description?: string | null
  resourceField?: string | null
  resourceName?: string | null
  resourceId?: number | null
  updatedAt?: Date | string
  createdAt?: Date | string
  coverImagePosts?: Prisma.PostCreateNestedManyWithoutCoverImageInput
  galleryImagesPosts?: Prisma.PostCreateNestedManyWithoutGalleryImagesInput
  avatarUsers?: Prisma.UserCreateNestedManyWithoutAvatarInput
}

export type FileUncheckedCreateWithoutCreatedByInput = {
  id?: number
  name: string
  originalName: string
  mimeType: string
  sizeBytes: number
  title?: string | null
  description?: string | null
  resourceField?: string | null
  resourceName?: string | null
  resourceId?: number | null
  updatedAt?: Date | string
  createdAt?: Date | string
  coverImagePosts?: Prisma.PostUncheckedCreateNestedManyWithoutCoverImageInput
  galleryImagesPosts?: Prisma.PostUncheckedCreateNestedManyWithoutGalleryImagesInput
  avatarUsers?: Prisma.UserUncheckedCreateNestedManyWithoutAvatarInput
}

export type FileCreateOrConnectWithoutCreatedByInput = {
  where: Prisma.FileWhereUniqueInput
  create: Prisma.XOR<Prisma.FileCreateWithoutCreatedByInput, Prisma.FileUncheckedCreateWithoutCreatedByInput>
}

export type FileCreateManyCreatedByInputEnvelope = {
  data: Prisma.FileCreateManyCreatedByInput | Prisma.FileCreateManyCreatedByInput[]
}

export type FileUpsertWithoutAvatarUsersInput = {
  update: Prisma.XOR<Prisma.FileUpdateWithoutAvatarUsersInput, Prisma.FileUncheckedUpdateWithoutAvatarUsersInput>
  create: Prisma.XOR<Prisma.FileCreateWithoutAvatarUsersInput, Prisma.FileUncheckedCreateWithoutAvatarUsersInput>
  where?: Prisma.FileWhereInput
}

export type FileUpdateToOneWithWhereWithoutAvatarUsersInput = {
  where?: Prisma.FileWhereInput
  data: Prisma.XOR<Prisma.FileUpdateWithoutAvatarUsersInput, Prisma.FileUncheckedUpdateWithoutAvatarUsersInput>
}

export type FileUpdateWithoutAvatarUsersInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceField?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverImagePosts?: Prisma.PostUpdateManyWithoutCoverImageNestedInput
  galleryImagesPosts?: Prisma.PostUpdateManyWithoutGalleryImagesNestedInput
  createdBy?: Prisma.UserUpdateOneWithoutCreatedFilesNestedInput
}

export type FileUncheckedUpdateWithoutAvatarUsersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceField?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  coverImagePosts?: Prisma.PostUncheckedUpdateManyWithoutCoverImageNestedInput
  galleryImagesPosts?: Prisma.PostUncheckedUpdateManyWithoutGalleryImagesNestedInput
}

export type FileUpsertWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.FileWhereUniqueInput
  update: Prisma.XOR<Prisma.FileUpdateWithoutCreatedByInput, Prisma.FileUncheckedUpdateWithoutCreatedByInput>
  create: Prisma.XOR<Prisma.FileCreateWithoutCreatedByInput, Prisma.FileUncheckedCreateWithoutCreatedByInput>
}

export type FileUpdateWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.FileWhereUniqueInput
  data: Prisma.XOR<Prisma.FileUpdateWithoutCreatedByInput, Prisma.FileUncheckedUpdateWithoutCreatedByInput>
}

export type FileUpdateManyWithWhereWithoutCreatedByInput = {
  where: Prisma.FileScalarWhereInput
  data: Prisma.XOR<Prisma.FileUpdateManyMutationInput, Prisma.FileUncheckedUpdateManyWithoutCreatedByInput>
}

export type FileUpdateWithoutGalleryImagesPostsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceField?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverImagePosts?: Prisma.PostUpdateManyWithoutCoverImageNestedInput
  avatarUsers?: Prisma.UserUpdateManyWithoutAvatarNestedInput
  createdBy?: Prisma.UserUpdateOneWithoutCreatedFilesNestedInput
}

export type FileUncheckedUpdateWithoutGalleryImagesPostsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceField?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  coverImagePosts?: Prisma.PostUncheckedUpdateManyWithoutCoverImageNestedInput
  avatarUsers?: Prisma.UserUncheckedUpdateManyWithoutAvatarNestedInput
}

export type FileUncheckedUpdateManyWithoutGalleryImagesPostsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceField?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type FileCreateManyCreatedByInput = {
  id?: number
  name: string
  originalName: string
  mimeType: string
  sizeBytes: number
  title?: string | null
  description?: string | null
  resourceField?: string | null
  resourceName?: string | null
  resourceId?: number | null
  updatedAt?: Date | string
  createdAt?: Date | string
}

export type FileUpdateWithoutCreatedByInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceField?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverImagePosts?: Prisma.PostUpdateManyWithoutCoverImageNestedInput
  galleryImagesPosts?: Prisma.PostUpdateManyWithoutGalleryImagesNestedInput
  avatarUsers?: Prisma.UserUpdateManyWithoutAvatarNestedInput
}

export type FileUncheckedUpdateWithoutCreatedByInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceField?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverImagePosts?: Prisma.PostUncheckedUpdateManyWithoutCoverImageNestedInput
  galleryImagesPosts?: Prisma.PostUncheckedUpdateManyWithoutGalleryImagesNestedInput
  avatarUsers?: Prisma.UserUncheckedUpdateManyWithoutAvatarNestedInput
}

export type FileUncheckedUpdateManyWithoutCreatedByInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceField?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resourceId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type FileCountOutputType
 */

export type FileCountOutputType = {
  coverImagePosts: number
  galleryImagesPosts: number
  avatarUsers: number
}

export type FileCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  coverImagePosts?: boolean | FileCountOutputTypeCountCoverImagePostsArgs
  galleryImagesPosts?: boolean | FileCountOutputTypeCountGalleryImagesPostsArgs
  avatarUsers?: boolean | FileCountOutputTypeCountAvatarUsersArgs
}

/**
 * FileCountOutputType without action
 */
export type FileCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileCountOutputType
   */
  select?: Prisma.FileCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FileCountOutputType without action
 */
export type FileCountOutputTypeCountCoverImagePostsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PostWhereInput
}

/**
 * FileCountOutputType without action
 */
export type FileCountOutputTypeCountGalleryImagesPostsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PostWhereInput
}

/**
 * FileCountOutputType without action
 */
export type FileCountOutputTypeCountAvatarUsersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
}


export type FileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  originalName?: boolean
  mimeType?: boolean
  sizeBytes?: boolean
  title?: boolean
  description?: boolean
  resourceField?: boolean
  resourceName?: boolean
  resourceId?: boolean
  updatedAt?: boolean
  createdAt?: boolean
  createdById?: boolean
  coverImagePosts?: boolean | Prisma.File$coverImagePostsArgs<ExtArgs>
  galleryImagesPosts?: boolean | Prisma.File$galleryImagesPostsArgs<ExtArgs>
  avatarUsers?: boolean | Prisma.File$avatarUsersArgs<ExtArgs>
  createdBy?: boolean | Prisma.File$createdByArgs<ExtArgs>
  _count?: boolean | Prisma.FileCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["file"]>

export type FileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  originalName?: boolean
  mimeType?: boolean
  sizeBytes?: boolean
  title?: boolean
  description?: boolean
  resourceField?: boolean
  resourceName?: boolean
  resourceId?: boolean
  updatedAt?: boolean
  createdAt?: boolean
  createdById?: boolean
  createdBy?: boolean | Prisma.File$createdByArgs<ExtArgs>
}, ExtArgs["result"]["file"]>

export type FileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  originalName?: boolean
  mimeType?: boolean
  sizeBytes?: boolean
  title?: boolean
  description?: boolean
  resourceField?: boolean
  resourceName?: boolean
  resourceId?: boolean
  updatedAt?: boolean
  createdAt?: boolean
  createdById?: boolean
  createdBy?: boolean | Prisma.File$createdByArgs<ExtArgs>
}, ExtArgs["result"]["file"]>

export type FileSelectScalar = {
  id?: boolean
  name?: boolean
  originalName?: boolean
  mimeType?: boolean
  sizeBytes?: boolean
  title?: boolean
  description?: boolean
  resourceField?: boolean
  resourceName?: boolean
  resourceId?: boolean
  updatedAt?: boolean
  createdAt?: boolean
  createdById?: boolean
}

export type FileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "originalName" | "mimeType" | "sizeBytes" | "title" | "description" | "resourceField" | "resourceName" | "resourceId" | "updatedAt" | "createdAt" | "createdById", ExtArgs["result"]["file"]>
export type FileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  coverImagePosts?: boolean | Prisma.File$coverImagePostsArgs<ExtArgs>
  galleryImagesPosts?: boolean | Prisma.File$galleryImagesPostsArgs<ExtArgs>
  avatarUsers?: boolean | Prisma.File$avatarUsersArgs<ExtArgs>
  createdBy?: boolean | Prisma.File$createdByArgs<ExtArgs>
  _count?: boolean | Prisma.FileCountOutputTypeDefaultArgs<ExtArgs>
}
export type FileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdBy?: boolean | Prisma.File$createdByArgs<ExtArgs>
}
export type FileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdBy?: boolean | Prisma.File$createdByArgs<ExtArgs>
}

export type $FilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "File"
  objects: {
    /**
     * Related models with file columns
     */
    coverImagePosts: Prisma.$PostPayload<ExtArgs>[]
    galleryImagesPosts: Prisma.$PostPayload<ExtArgs>[]
    avatarUsers: Prisma.$UserPayload<ExtArgs>[]
    createdBy: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    originalName: string
    mimeType: string
    sizeBytes: number
    title: string | null
    description: string | null
    resourceField: string | null
    resourceName: string | null
    resourceId: number | null
    /**
     * Audit columns
     */
    updatedAt: Date
    createdAt: Date
    createdById: number | null
  }, ExtArgs["result"]["file"]>
  composites: {}
}

export type FileGetPayload<S extends boolean | null | undefined | FileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FilePayload, S>

export type FileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FileCountAggregateInputType | true
  }

export interface FileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['File'], meta: { name: 'File' } }
  /**
   * Find zero or one File that matches the filter.
   * @param {FileFindUniqueArgs} args - Arguments to find a File
   * @example
   * // Get one File
   * const file = await prisma.file.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FileFindUniqueArgs>(args: Prisma.SelectSubset<T, FileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FileClient<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one File that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FileFindUniqueOrThrowArgs} args - Arguments to find a File
   * @example
   * // Get one File
   * const file = await prisma.file.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FileClient<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first File that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileFindFirstArgs} args - Arguments to find a File
   * @example
   * // Get one File
   * const file = await prisma.file.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FileFindFirstArgs>(args?: Prisma.SelectSubset<T, FileFindFirstArgs<ExtArgs>>): Prisma.Prisma__FileClient<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first File that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileFindFirstOrThrowArgs} args - Arguments to find a File
   * @example
   * // Get one File
   * const file = await prisma.file.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FileClient<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Files that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Files
   * const files = await prisma.file.findMany()
   * 
   * // Get first 10 Files
   * const files = await prisma.file.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const fileWithIdOnly = await prisma.file.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FileFindManyArgs>(args?: Prisma.SelectSubset<T, FileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a File.
   * @param {FileCreateArgs} args - Arguments to create a File.
   * @example
   * // Create one File
   * const File = await prisma.file.create({
   *   data: {
   *     // ... data to create a File
   *   }
   * })
   * 
   */
  create<T extends FileCreateArgs>(args: Prisma.SelectSubset<T, FileCreateArgs<ExtArgs>>): Prisma.Prisma__FileClient<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Files.
   * @param {FileCreateManyArgs} args - Arguments to create many Files.
   * @example
   * // Create many Files
   * const file = await prisma.file.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FileCreateManyArgs>(args?: Prisma.SelectSubset<T, FileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Files and returns the data saved in the database.
   * @param {FileCreateManyAndReturnArgs} args - Arguments to create many Files.
   * @example
   * // Create many Files
   * const file = await prisma.file.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Files and only return the `id`
   * const fileWithIdOnly = await prisma.file.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a File.
   * @param {FileDeleteArgs} args - Arguments to delete one File.
   * @example
   * // Delete one File
   * const File = await prisma.file.delete({
   *   where: {
   *     // ... filter to delete one File
   *   }
   * })
   * 
   */
  delete<T extends FileDeleteArgs>(args: Prisma.SelectSubset<T, FileDeleteArgs<ExtArgs>>): Prisma.Prisma__FileClient<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one File.
   * @param {FileUpdateArgs} args - Arguments to update one File.
   * @example
   * // Update one File
   * const file = await prisma.file.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FileUpdateArgs>(args: Prisma.SelectSubset<T, FileUpdateArgs<ExtArgs>>): Prisma.Prisma__FileClient<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Files.
   * @param {FileDeleteManyArgs} args - Arguments to filter Files to delete.
   * @example
   * // Delete a few Files
   * const { count } = await prisma.file.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FileDeleteManyArgs>(args?: Prisma.SelectSubset<T, FileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Files.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Files
   * const file = await prisma.file.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FileUpdateManyArgs>(args: Prisma.SelectSubset<T, FileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Files and returns the data updated in the database.
   * @param {FileUpdateManyAndReturnArgs} args - Arguments to update many Files.
   * @example
   * // Update many Files
   * const file = await prisma.file.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Files and only return the `id`
   * const fileWithIdOnly = await prisma.file.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one File.
   * @param {FileUpsertArgs} args - Arguments to update or create a File.
   * @example
   * // Update or create a File
   * const file = await prisma.file.upsert({
   *   create: {
   *     // ... data to create a File
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the File we want to update
   *   }
   * })
   */
  upsert<T extends FileUpsertArgs>(args: Prisma.SelectSubset<T, FileUpsertArgs<ExtArgs>>): Prisma.Prisma__FileClient<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Files.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileCountArgs} args - Arguments to filter Files to count.
   * @example
   * // Count the number of Files
   * const count = await prisma.file.count({
   *   where: {
   *     // ... the filter for the Files we want to count
   *   }
   * })
  **/
  count<T extends FileCountArgs>(
    args?: Prisma.Subset<T, FileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a File.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FileAggregateArgs>(args: Prisma.Subset<T, FileAggregateArgs>): Prisma.PrismaPromise<GetFileAggregateType<T>>

  /**
   * Group by File.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FileGroupByArgs['orderBy'] }
      : { orderBy?: FileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the File model
 */
readonly fields: FileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for File.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  coverImagePosts<T extends Prisma.File$coverImagePostsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.File$coverImagePostsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  galleryImagesPosts<T extends Prisma.File$galleryImagesPostsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.File$galleryImagesPostsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  avatarUsers<T extends Prisma.File$avatarUsersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.File$avatarUsersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  createdBy<T extends Prisma.File$createdByArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.File$createdByArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the File model
 */
export interface FileFieldRefs {
  readonly id: Prisma.FieldRef<"File", 'Int'>
  readonly name: Prisma.FieldRef<"File", 'String'>
  readonly originalName: Prisma.FieldRef<"File", 'String'>
  readonly mimeType: Prisma.FieldRef<"File", 'String'>
  readonly sizeBytes: Prisma.FieldRef<"File", 'Int'>
  readonly title: Prisma.FieldRef<"File", 'String'>
  readonly description: Prisma.FieldRef<"File", 'String'>
  readonly resourceField: Prisma.FieldRef<"File", 'String'>
  readonly resourceName: Prisma.FieldRef<"File", 'String'>
  readonly resourceId: Prisma.FieldRef<"File", 'Int'>
  readonly updatedAt: Prisma.FieldRef<"File", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"File", 'DateTime'>
  readonly createdById: Prisma.FieldRef<"File", 'Int'>
}
    

// Custom InputTypes
/**
 * File findUnique
 */
export type FileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileInclude<ExtArgs> | null
  /**
   * Filter, which File to fetch.
   */
  where: Prisma.FileWhereUniqueInput
}

/**
 * File findUniqueOrThrow
 */
export type FileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileInclude<ExtArgs> | null
  /**
   * Filter, which File to fetch.
   */
  where: Prisma.FileWhereUniqueInput
}

/**
 * File findFirst
 */
export type FileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileInclude<ExtArgs> | null
  /**
   * Filter, which File to fetch.
   */
  where?: Prisma.FileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Files to fetch.
   */
  orderBy?: Prisma.FileOrderByWithRelationInput | Prisma.FileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Files.
   */
  cursor?: Prisma.FileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Files from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Files.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Files.
   */
  distinct?: Prisma.FileScalarFieldEnum | Prisma.FileScalarFieldEnum[]
}

/**
 * File findFirstOrThrow
 */
export type FileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileInclude<ExtArgs> | null
  /**
   * Filter, which File to fetch.
   */
  where?: Prisma.FileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Files to fetch.
   */
  orderBy?: Prisma.FileOrderByWithRelationInput | Prisma.FileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Files.
   */
  cursor?: Prisma.FileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Files from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Files.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Files.
   */
  distinct?: Prisma.FileScalarFieldEnum | Prisma.FileScalarFieldEnum[]
}

/**
 * File findMany
 */
export type FileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileInclude<ExtArgs> | null
  /**
   * Filter, which Files to fetch.
   */
  where?: Prisma.FileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Files to fetch.
   */
  orderBy?: Prisma.FileOrderByWithRelationInput | Prisma.FileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Files.
   */
  cursor?: Prisma.FileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Files from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Files.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Files.
   */
  distinct?: Prisma.FileScalarFieldEnum | Prisma.FileScalarFieldEnum[]
}

/**
 * File create
 */
export type FileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileInclude<ExtArgs> | null
  /**
   * The data needed to create a File.
   */
  data: Prisma.XOR<Prisma.FileCreateInput, Prisma.FileUncheckedCreateInput>
}

/**
 * File createMany
 */
export type FileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Files.
   */
  data: Prisma.FileCreateManyInput | Prisma.FileCreateManyInput[]
}

/**
 * File createManyAndReturn
 */
export type FileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * The data used to create many Files.
   */
  data: Prisma.FileCreateManyInput | Prisma.FileCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * File update
 */
export type FileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileInclude<ExtArgs> | null
  /**
   * The data needed to update a File.
   */
  data: Prisma.XOR<Prisma.FileUpdateInput, Prisma.FileUncheckedUpdateInput>
  /**
   * Choose, which File to update.
   */
  where: Prisma.FileWhereUniqueInput
}

/**
 * File updateMany
 */
export type FileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Files.
   */
  data: Prisma.XOR<Prisma.FileUpdateManyMutationInput, Prisma.FileUncheckedUpdateManyInput>
  /**
   * Filter which Files to update
   */
  where?: Prisma.FileWhereInput
  /**
   * Limit how many Files to update.
   */
  limit?: number
}

/**
 * File updateManyAndReturn
 */
export type FileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * The data used to update Files.
   */
  data: Prisma.XOR<Prisma.FileUpdateManyMutationInput, Prisma.FileUncheckedUpdateManyInput>
  /**
   * Filter which Files to update
   */
  where?: Prisma.FileWhereInput
  /**
   * Limit how many Files to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * File upsert
 */
export type FileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileInclude<ExtArgs> | null
  /**
   * The filter to search for the File to update in case it exists.
   */
  where: Prisma.FileWhereUniqueInput
  /**
   * In case the File found by the `where` argument doesn't exist, create a new File with this data.
   */
  create: Prisma.XOR<Prisma.FileCreateInput, Prisma.FileUncheckedCreateInput>
  /**
   * In case the File was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FileUpdateInput, Prisma.FileUncheckedUpdateInput>
}

/**
 * File delete
 */
export type FileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileInclude<ExtArgs> | null
  /**
   * Filter which File to delete.
   */
  where: Prisma.FileWhereUniqueInput
}

/**
 * File deleteMany
 */
export type FileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Files to delete
   */
  where?: Prisma.FileWhereInput
  /**
   * Limit how many Files to delete.
   */
  limit?: number
}

/**
 * File.coverImagePosts
 */
export type File$coverImagePostsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Post
   */
  select?: Prisma.PostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Post
   */
  omit?: Prisma.PostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostInclude<ExtArgs> | null
  where?: Prisma.PostWhereInput
  orderBy?: Prisma.PostOrderByWithRelationInput | Prisma.PostOrderByWithRelationInput[]
  cursor?: Prisma.PostWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PostScalarFieldEnum | Prisma.PostScalarFieldEnum[]
}

/**
 * File.galleryImagesPosts
 */
export type File$galleryImagesPostsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Post
   */
  select?: Prisma.PostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Post
   */
  omit?: Prisma.PostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostInclude<ExtArgs> | null
  where?: Prisma.PostWhereInput
  orderBy?: Prisma.PostOrderByWithRelationInput | Prisma.PostOrderByWithRelationInput[]
  cursor?: Prisma.PostWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PostScalarFieldEnum | Prisma.PostScalarFieldEnum[]
}

/**
 * File.avatarUsers
 */
export type File$avatarUsersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  cursor?: Prisma.UserWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * File.createdBy
 */
export type File$createdByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * File without action
 */
export type FileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileInclude<ExtArgs> | null
}
