/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const CommentStatus = {
  Pending: 'Pending',
  Approved: 'Approved',
  Spam: 'Spam'
} as const;

export type CommentStatus = (typeof CommentStatus)[keyof typeof CommentStatus];

export const PageStatus = {
  Draft: 'Draft',
  Published: 'Published',
  Archived: 'Archived'
} as const;

export type PageStatus = (typeof PageStatus)[keyof typeof PageStatus];

export const PostStatus = {
  Draft: 'Draft',
  Published: 'Published',
  Archived: 'Archived'
} as const;

export type PostStatus = (typeof PostStatus)[keyof typeof PostStatus];

export const UserTwoFactorAuth = {
  None: 'None',
  Email: 'Email'
} as const;

export type UserTwoFactorAuth =
  (typeof UserTwoFactorAuth)[keyof typeof UserTwoFactorAuth];
