import path from 'node:path';
import fs from 'node:fs';
import { spawn } from 'node:child_process';
import { TModule, TSchema, Type } from '@sinclair/typebox';
import { ModelToTypeScript } from '@sinclair/typebox-codegen';
import { File } from '@appweaver/core';
import { ResourceModelSchema } from '@appweaver/common';

export async function generateTypes(
  resources: Record<string, ResourceModelSchema>,
  typesPath: string
): Promise<void> {
  const currentDir = process.cwd();
  const typesDir = path.join(currentDir, path.dirname(typesPath));

  if (!fs.existsSync(typesDir)) {
    fs.mkdirSync(typesDir, { recursive: true });
    console.log(`Types directory created ${typesDir}`);
  }

  try {
    const resourceModels: Record<string, TSchema> = {
      File: File
    };

    for (const [modelName, schema] of Object.entries(resources)) {
      resourceModels[modelName] = schema.readModel;
      resourceModels[`${modelName}Create`] = schema.createModel;
      resourceModels[`${modelName}Update`] = schema.updateModel;
      resourceModels[`${modelName}Relations`] = schema.relationsModel;
      resourceModels[`${modelName}Files`] = schema.filesModel;
      resourceModels[`${modelName}Virtual`] = schema.virtualModel;
    }

    const module = Type.Module(resourceModels);

    const typesContent: string[] = [
      `// Generated by Appweaver. Please do not edit this file manually.`,
      ``
    ];

    for (const modelName of Object.keys(resourceModels)) {
      typesContent.push(generateTypeScriptType(module, modelName), ``);
    }

    const outputPath = path.join(currentDir, typesPath);
    fs.writeFileSync(outputPath, typesContent.join('\n'));

    spawn(`prettier --log-level silent --write ${outputPath}`, {
      stdio: 'inherit',
      shell: true
    });

    console.log(`Types generated to ${outputPath}`);
  } catch (error) {
    console.error(`Types generation failed:`, error);
  }
}

function generateTypeScriptType(
  module: TModule<{ [p: string]: TSchema }, { [p: string]: TSchema }>,
  name: string
): string {
  const model: TSchema = module.Import(name);
  const types = [model.$defs[name]];
  return ModelToTypeScript.GenerateType({ types }, name);
}
