import path from 'node:path';
import fsp from 'node:fs/promises';
import prettier from 'prettier';
import { TModule, TObject, TSchema, Type } from '@sinclair/typebox';
import { ModelToTypeScript } from '@sinclair/typebox-codegen';
import {
  DateType,
  EnumType,
  isArray,
  NullType,
  ResourceModel
} from '@appweaver/common';
import { ensureDirExists } from '../utils';

export async function generateTypes(
  models: Record<string, ResourceModel>,
  typesPath: string,
  quiet: boolean = false
): Promise<number> {
  const cwd = process.cwd();

  try {
    await ensureDirExists(path.join(cwd, typesPath));

    const resourceModels: Record<string, TSchema> = {};

    for (const [name, schema] of Object.entries(models)) {
      if (schema.config.generateTypes === false) {
        continue;
      }

      resourceModels[name] = transformUnsafeTypes(schema.readModel);
      resourceModels[`${name}Single`] = transformUnsafeTypes(
        schema.readOneModel
      );
      resourceModels[`${name}Multiple`] = transformUnsafeTypes(
        schema.readManyModel
      );
      resourceModels[`${name}Create`] = transformUnsafeTypes(
        schema.createOneModel
      );
      resourceModels[`${name}Update`] = transformUnsafeTypes(
        schema.updateOneModel
      );
    }

    const module = Type.Module(resourceModels);

    const typesContent: string[] = [
      `// Generated by Appweaver. Please do not edit this file manually.`,
      ``
    ];

    for (const name of Object.keys(resourceModels)) {
      typesContent.push(generateTypeScriptType(module, name), ``);
    }

    const outputPath = path.join(cwd, typesPath);

    const prettierConfig = await prettier.resolveConfig(outputPath);
    const formattedTypes = await prettier.format(typesContent.join('\n'), {
      ...prettierConfig,
      filepath: outputPath
    });

    await fsp.writeFile(outputPath, formattedTypes);

    console.log(`Types generated to ${path.relative(cwd, outputPath)}`);

    return 0;
  } catch (error) {
    console.error(
      `Types generation failed.${quiet ? ' Start with --verbose flag to see error details.' : ''}`
    );
    if (!quiet) {
      console.error(error);
    }
    return 2;
  }
}

function generateTypeScriptType(
  module: TModule<{ [p: string]: TSchema }, { [p: string]: TSchema }>,
  name: string
): string {
  const model: TSchema = module.Import(name);
  const schema = model.$defs[name];
  return ModelToTypeScript.GenerateType({ types: [schema] }, name);
}

function transformUnsafeTypes(schema: TObject): TObject {
  const properties: Record<string, TSchema> = {};

  for (const [name, field] of Object.entries(schema.properties)) {
    if (field.type === 'string' && isArray(field.enum)) {
      properties[name] = EnumType(field.enum);
    } else if (
      field.type === 'string' &&
      ['date-time', 'date'].includes(field.format)
    ) {
      properties[name] = DateType(field);
    } else {
      properties[name] = field;
    }

    if (field.nullable === true) {
      properties[name] = NullType(properties[name]);
    }
  }

  return Type.Object(properties, { ...schema });
}
