import path from 'node:path';
import fsp from 'node:fs/promises';
import fs from 'node:fs';
import {
  AuditFields,
  capitalize,
  config,
  FileField,
  FilesConfig,
  IdField,
  IndexConfig,
  isArray,
  plural,
  RelationConfig,
  RelationField,
  ResourceModelSchema,
  ScalarConfig,
  ScalarField,
  uncapitalize
} from '@appweaver/common';

type PrismaSchemaField = {
  name: string;
  type: string;
  attributes?: string[];
};

type PrismaSchemaModel = {
  id: PrismaSchemaField;
  scalars: PrismaSchemaField[];
  relations: PrismaSchemaField[];
  files: PrismaSchemaField[];
  audit: PrismaSchemaField[];
  index: string[];
  extra?: Record<string, PrismaSchemaField[]>;
};

export async function generateSchema(
  models: Record<string, ResourceModelSchema>,
  schemaPath: string
): Promise<void> {
  const cwd = process.cwd();
  const schemaDir = path.join(cwd, path.dirname(schemaPath));

  try {
    await fsp.access(schemaDir, fs.constants.F_OK);
  } catch (e) {
    await fsp.mkdir(schemaDir, { recursive: true });
  }

  try {
    const prismaModels: Record<string, PrismaSchemaModel> = {};
    const prismaEnums: Record<string, string[]> = {};

    const schemaContent = [
      `// This is your Prisma schema file,`,
      `// learn more about it in the docs: https://pris.ly/d/prisma-schema`,
      ``,
      `datasource db {`,
      `  provider = "${config.DATABASE_TYPE}"`,
      `}`,
      ``,
      `generator client {`,
      `  provider = "prisma-client-js"`,
      `  output   = "${config.DATABASE_CLIENT_OUTPUT_PATH}"`,
      `}`,
      ``,
      `// Generated by Appweaver. Please do not edit this part manually.`
    ];

    // Create Prisma models and enums from resource model config
    for (const [name, schema] of Object.entries(models)) {
      prismaModels[name] = {
        id: createIdSchema(schema.config.id),
        scalars: createScalarsSchema(name, schema.config.scalars),
        relations: createRelationsSchema(name, schema.config.relations),
        files: createFilesSchema(name, schema.config.files),
        audit: createAuditSchema(name, schema.config.audit),
        index: createIndexSchema(schema.config.index)
      };

      for (const [fieldName, scalar] of Object.entries(
        schema.config.scalars ?? {}
      )) {
        if (scalar.type === 'enum' && scalar.values?.length) {
          prismaEnums[`${name}${capitalize(fieldName)}`] = scalar.values;
        }
      }
    }

    // Resolve model relations to match Prisma schema relationship convention
    const createdByIdentities: PrismaSchemaField[] = [];
    const fileFields: PrismaSchemaField[] = [];
    for (const [name, model] of Object.entries(prismaModels)) {
      const modelSchema = Object.entries(models).find(
        ([key]) => key === name
      )?.[1];

      for (const relation of model.relations) {
        if (relation.type.startsWith('Int')) {
          continue;
        }

        const relationConfig = modelSchema?.config.relations?.[relation.name];
        const referencedName = relation.type
          .replaceAll('[]', '')
          .replaceAll('?', '');
        const referencedModel = prismaModels[referencedName];

        const mappedField = referencedModel.relations.find(
          (r) => r.name === relationConfig?.mappedBy
        );
        if (mappedField?.type.startsWith('Int')) {
          continue;
        }

        if (mappedField && mappedField.attributes?.length) {
          // Ensure that mapped fields have the same reference name
          const relationAttribute = mappedField.attributes[0];
          const relationParts = relationAttribute.split('"');
          const referenceName = relation.attributes?.[0].split('"')[1];
          relationParts.splice(1, 1, `${referenceName}`);
          mappedField.attributes[0] = relationParts.join('"');
        } else {
          // For unmapped relations add a default relation field using the same
          // reference name
          const refName = uncapitalize(plural(name));
          if (!referencedModel.relations.some((r) => r.name === refName)) {
            referencedModel.relations.push({
              name: uncapitalize(plural(name)),
              type: `${name}[]`,
              attributes: relation.attributes
            });
          }
        }
      }

      for (const auditField of model.audit) {
        if (auditField.name === 'createdBy') {
          const referenceName = auditField.attributes?.[0].split('"')[1];
          createdByIdentities.push({
            name: `created${plural(name)}`,
            type: `${name}[]`,
            attributes: [`@relation("${referenceName}")`]
          });
        }
      }

      for (const fileField of model.files) {
        const referenceName = fileField.attributes?.[0].split('"')[1];
        if (referenceName) {
          fileFields.push({
            name: `${fileField.name}${plural(name)}`,
            type: `${name}[]`,
            attributes: [`@relation("${referenceName}")`]
          });
        }
      }
    }

    // Add identity ownership relations
    const identityModel = prismaModels['Identity'];
    if (identityModel) {
      identityModel.extra = {
        'Ownership models referenced with createdById column':
          createdByIdentities
      };
    }

    // Add file fields relations
    const fileModel = prismaModels['File'];
    if (fileModel) {
      fileModel.extra = {
        'Related models with file columns': fileFields
      };
    }

    // Add Prisma models to the schema content
    for (const [name, model] of Object.entries(prismaModels)) {
      schemaContent.push(`model ${name} {`);

      // Group 1: id + scalars
      const initialFields = [model.id, ...model.scalars];
      const { nameLength, typeLength } = calculateMaxLengths(initialFields);
      schemaContent.push(buildPrismaField(model.id, nameLength, typeLength));
      for (const scalar of model.scalars) {
        schemaContent.push(buildPrismaField(scalar, nameLength, typeLength));
      }

      // Group 2: relations
      if (model.relations.length > 0) {
        schemaContent.push(``);
        schemaContent.push(`  /// Related columns`);
        const { nameLength, typeLength } = calculateMaxLengths(model.relations);
        for (const relation of model.relations) {
          schemaContent.push(
            buildPrismaField(relation, nameLength, typeLength)
          );
        }
      }

      // Group 3: files
      if (model.files.length > 0) {
        schemaContent.push(``);
        schemaContent.push(`  /// File columns`);
        const { nameLength, typeLength } = calculateMaxLengths(model.files);
        for (const file of model.files) {
          schemaContent.push(buildPrismaField(file, nameLength, typeLength));
        }
      }

      // Group 4: extra fields
      for (const [title, extraFields] of Object.entries(model.extra ?? {})) {
        schemaContent.push(``);
        schemaContent.push(`  /// ${title}`);
        const { nameLength, typeLength } = calculateMaxLengths(extraFields);
        for (const extraField of extraFields) {
          schemaContent.push(
            buildPrismaField(extraField, nameLength, typeLength)
          );
        }
      }

      // Group 5: audit
      if (model.audit.length > 0) {
        schemaContent.push(``);
        schemaContent.push(`  /// Audit columns`);
        const { nameLength, typeLength } = calculateMaxLengths(model.audit);
        for (const audit of model.audit) {
          schemaContent.push(buildPrismaField(audit, nameLength, typeLength));
        }
      }

      if (model.index.length) {
        schemaContent.push(``);
      }

      for (const index of model.index) {
        schemaContent.push(index);
      }

      schemaContent.push(`}`, ``);
    }

    // Add Prisma enums to the schema content
    for (const [name, enumValues] of Object.entries(prismaEnums)) {
      schemaContent.push(`enum ${name} {`);

      for (const value of enumValues) {
        schemaContent.push(`  ${value}`);
      }

      schemaContent.push(`}`, ``);
    }

    const outputPath = path.join(cwd, schemaPath);
    await fsp.writeFile(outputPath, schemaContent.join('\n'));

    // spawn(`prisma generate`, { stdio: 'inherit', shell: true });

    console.log(`Schema generated to ${outputPath}`);
  } catch (error) {
    console.error(`Schema generation failed:`, error);
  }
}

function buildPrismaField(
  field: PrismaSchemaField,
  nameLength = 0,
  typeLength = 0
): string {
  const paddedName = field.name.padEnd(nameLength);
  const paddedType = field.type.padEnd(typeLength);
  return `  ${paddedName} ${paddedType} ${field.attributes?.join(' ') ?? ''}`.trimEnd();
}

function calculateMaxLengths(fields: PrismaSchemaField[]): {
  nameLength: number;
  typeLength: number;
} {
  let nameLength = 0;
  let typeLength = 0;

  for (const field of fields) {
    if (field.name.length > nameLength) {
      nameLength = field.name.length;
    }
    if (field.type.length > typeLength) {
      typeLength = field.type.length;
    }
  }

  return { nameLength, typeLength };
}

function createIdSchema(id: IdField = {}): PrismaSchemaField {
  const defaultType =
    !id.generator || id.generator === 'autoincrement()' ? 'Int' : 'String';
  const defaultGenerator = id.type !== 'string' ? 'autoincrement()' : 'uuid()';
  return {
    name: 'id',
    type: capitalize(id.type ?? defaultType),
    attributes: ['@id', `@default(${id.generator ?? defaultGenerator})`]
  };
}

function createScalarsSchema(
  modelName: string,
  scalars: ScalarConfig = {}
): PrismaSchemaField[] {
  const fields: PrismaSchemaField[] = [];

  for (const [name, scalar] of Object.entries(scalars)) {
    fields.push(createScalarSchema(name, modelName, scalar));
  }

  return fields;
}

function createScalarSchema(
  name: string,
  modelName: string,
  scalar: ScalarField
): PrismaSchemaField {
  const attributes: string[] = [];

  let typeSuffix = scalar.required === false ? '?' : '';
  if (scalar.array) {
    typeSuffix = '[]';
  }

  const type =
    scalar.type === 'enum' && scalar.values?.length
      ? `${modelName}${capitalize(name)}${typeSuffix}`
      : `${capitalize(scalar.type)}${typeSuffix}`;

  if (scalar.unique) {
    attributes.push(`@unique`);
  }

  if (scalar.default) {
    if (['string', 'dateTime', 'json'].includes(scalar.type) && !scalar.array) {
      attributes.push(`@default("${scalar.default}")`);
    } else if (scalar.array) {
      let defaultValues = scalar.default;
      if (isArray(scalar.default)) {
        defaultValues = scalar.default.map((v) => `"${v}"`).join(', ');
      }
      attributes.push(`@default([${defaultValues}])`);
    } else {
      attributes.push(`@default(${scalar.default})`);
    }
  }

  return {
    name,
    type,
    attributes
  };
}

function createRelationsSchema(
  modelName: string,
  relations: RelationConfig = {}
): PrismaSchemaField[] {
  const fields: PrismaSchemaField[] = [];

  for (const [name, relation] of Object.entries(relations)) {
    fields.push(...createRelationSchema(name, modelName, relation));
  }

  return fields;
}

function createRelationSchema(
  name: string,
  modelName: string,
  relation: RelationField
): PrismaSchemaField[] {
  const attributes: string[] = [];
  const relationName = `${modelName}${capitalize(name)}${relation.model}`;
  const relationFieldName = `${name}Id`;
  const relationSuffix = relation.required === false ? '?' : '';
  const type = relation.array
    ? `${relation.model}[]`
    : `${relation.model}${relationSuffix}`;

  if (relation.array) {
    attributes.push(`@relation("${relationName}")`);
  } else {
    let referentialActions: string[] = [];
    if (relation.onDelete) {
      referentialActions.push(`onDelete: ${relation.onDelete}`);
    }
    if (relation.onUpdate) {
      referentialActions.push(`onUpdate: ${relation.onUpdate}`);
    }
    const referentialConfig =
      referentialActions.length > 0 ? `, ${referentialActions.join(', ')}` : '';
    attributes.push(
      `@relation("${relationName}", fields: [${relationFieldName}], references: [id]${referentialConfig})`
    );
  }

  const relationFields: PrismaSchemaField[] = [
    {
      name,
      type,
      attributes
    }
  ];

  if (!relation.array && relation.owner) {
    relationFields.push({
      name: relationFieldName,
      type: `Int${relationSuffix}`,
      attributes: relation.unique === true ? ['@unique'] : []
    });
  }

  return relationFields;
}

function createFilesSchema(
  modelName: string,
  files: FilesConfig = {}
): PrismaSchemaField[] {
  const fields: PrismaSchemaField[] = [];

  for (const [name, file] of Object.entries(files)) {
    fields.push(...createFileSchema(name, modelName, file));
  }

  return fields;
}

function createFileSchema(
  name: string,
  modelName: string,
  file: FileField
): PrismaSchemaField[] {
  const attributes: string[] = [];
  const type = file.array ? 'File[]' : 'File?';
  const fileRelationName = `${modelName}${capitalize(name)}File`;
  const fileRelationFieldName = `${name}Id`;

  if (file.array) {
    attributes.push(`@relation("${fileRelationName}")`);
  } else {
    attributes.push(
      `@relation("${fileRelationName}", fields: [${fileRelationFieldName}], references: [id])`
    );
  }

  const fileFields: PrismaSchemaField[] = [
    {
      name,
      type,
      attributes
    }
  ];

  if (!file.array) {
    fileFields.push({
      name: fileRelationFieldName,
      type: 'Int?',
      attributes: ['@unique']
    });
  }

  return fileFields;
}

function createAuditSchema(
  modelName: string,
  audit: AuditFields = { createdAt: true, updatedAt: true, createdById: true }
): PrismaSchemaField[] {
  const fields: PrismaSchemaField[] = [];

  if (audit.updatedAt) {
    fields.push({
      name: 'updatedAt',
      type: 'DateTime',
      attributes: ['@updatedAt']
    });
  }

  if (audit.createdAt) {
    fields.push({
      name: 'createdAt',
      type: 'DateTime',
      attributes: ['@default(now())']
    });
  }

  if (audit.createdById) {
    fields.push({
      name: 'createdBy',
      type: 'Identity?',
      attributes: [
        `@relation("${modelName}CreatedByIdentity", fields: [createdById], references: [id])`
      ]
    });
    fields.push({
      name: 'createdById',
      type: 'Int?'
    });
  }

  return fields;
}

function createIndexSchema(index?: IndexConfig): string[] {
  const indexes: string[] = [];

  if (!index || indexes.length === 0) {
    return indexes;
  }

  if (typeof index[0] === 'string') {
    for (const idx of index) {
      indexes.push(`@@index(${idx})`);
    }
  } else if (isArray(index[0])) {
    for (const indexGroups of index as string[][]) {
      indexes.push(`@@index([${indexGroups.join(', ')}])`);
    }
  }

  return indexes;
}
