services:
  movies-api-bun.migrations:
    image: movies-api-bun:latest
    container_name: movies-api-bun-migrations
    restart: no
    build:
      context: .
    env_file:
      - .env
    command: [ "migrations" ]
    volumes:
      - ./storage:/usr/app/storage
      - ./logs:/usr/app/logs
      - sqlite-data:/usr/app/data
    networks:
      - movies-api-bun

  movies-api-bun.seed:
    image: movies-api-bun:latest
    container_name: movies-api-bun-seed
    restart: no
    build:
      context: .
    depends_on:
      movies-api-bun.migrations:
        condition: service_completed_successfully
    env_file:
      - .env
    command: [ "seed" ]
    volumes:
      - ./storage:/usr/app/storage
      - ./logs:/usr/app/logs
      - sqlite-data:/usr/app/data
    networks:
      - movies-api-bun

  movies-api-bun:
    image: movies-api-bun:latest
    container_name: movies-api-bun
    restart: unless-stopped
    build:
      context: .
    healthcheck:
      test: "wget -qO - http://127.0.0.1:5005/health/ready || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
      start_interval: 5s
    depends_on:
      movies-api-bun.seed:
        condition: service_completed_successfully
    ports:
      - "127.0.0.1:5005:5005"
    volumes:
      - ./storage:/usr/app/storage
      - ./logs:/usr/app/logs
      - sqlite-data:/usr/app/data
    env_file:
      - .env
    networks:
      - movies-api-bun

networks:
  movies-api-bun:
    driver: bridge
    name: movies-api-bun-network

volumes:
  sqlite-data:
