import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Type } from '@sinclair/typebox';
import { ResourceModel } from '@appweaver/common';

// fkill (pulled in through the utils barrel) and prettier are ESM only
// packages that cannot be loaded by the CommonJS test runtime.
jest.mock('fkill', () => ({ __esModule: true, default: jest.fn() }));
jest.mock('prettier', () => ({
  __esModule: true,
  default: {
    resolveConfig: async () => ({}),
    format: async (content: string) => content
  }
}));

import { generateTypes } from '../../generate/generate-types';

/** Creates a resource model with the typebox models used for type generation. */
function model(name: string, readModel: any, config: any = {}): ResourceModel {
  return {
    name,
    config,
    readModel,
    readOneModel: Type.Object({ id: Type.Integer() }),
    readManyModel: Type.Object({ items: Type.Array(Type.Integer()) }),
    createOneModel: Type.Object({ title: Type.String() }),
    updateOneModel: Type.Object({ title: Type.Optional(Type.String()) }),
    relationCreateModel: Type.Object({ title: Type.String() }),
    relationUpdateModel: Type.Object({
      id: Type.Integer(),
      title: Type.Optional(Type.String())
    }),
    relationInputModel: Type.Object({
      id: Type.Optional(Type.Integer()),
      title: Type.Optional(Type.String())
    })
  } as unknown as ResourceModel;
}

describe('generate-types', () => {
  let tempDir: string;
  let originalCwd: string;
  const typesPath = './src/types/generated.ts';

  const generate = async (
    models: Record<string, ResourceModel>
  ): Promise<{ status: number; types: string }> => {
    const status = await generateTypes(models, typesPath, true);
    const typesFile = path.join(tempDir, typesPath);
    return {
      status,
      types: fs.existsSync(typesFile) ? fs.readFileSync(typesFile, 'utf8') : ''
    };
  };

  beforeEach(() => {
    originalCwd = process.cwd();
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'appweaver-cli-types-'));
    process.chdir(tempDir);
    jest.spyOn(console, 'log').mockImplementation(() => {});
  });

  afterEach(() => {
    process.chdir(originalCwd);
    fs.rmSync(tempDir, { recursive: true, force: true });
    jest.restoreAllMocks();
  });

  describe('generateTypes', () => {
    test('writes the generated types and creates the output directory', async () => {
      const { status, types } = await generate({
        Post: model('Post', Type.Object({ id: Type.Integer() }))
      });

      expect(status).toBe(0);
      expect(fs.existsSync(path.join(tempDir, 'src', 'types'))).toBe(true);
      expect(types).toContain(
        '// Generated by Appweaver. Please do not edit this file manually.'
      );
    });

    test('generates a type for every CRUD model of a resource', async () => {
      const { types } = await generate({
        Post: model('Post', Type.Object({ id: Type.Integer() }))
      });

      expect(types).toContain('export type Post = {');
      expect(types).toContain('export type PostSingle = {');
      expect(types).toContain('export type PostMultiple = {');
      expect(types).toContain('export type PostCreate = {');
      expect(types).toContain('export type PostUpdate = {');
      expect(types).toContain('export type PostRelationCreate = {');
      expect(types).toContain('export type PostRelationUpdate = {');
      expect(types).toContain('export type PostRelationInput = {');
    });

    test('maps the scalar types to TypeScript types', async () => {
      const { types } = await generate({
        Post: model(
          'Post',
          Type.Object({
            id: Type.Integer(),
            title: Type.String(),
            enabled: Type.Boolean(),
            tags: Type.Array(Type.String()),
            summary: Type.Optional(Type.String())
          })
        )
      });

      expect(types).toContain('id: number');
      expect(types).toContain('title: string');
      expect(types).toContain('enabled: boolean');
      expect(types).toContain('tags: Array<string>');
      expect(types).toContain('summary?: string');
    });

    test('converts string enums into union types', async () => {
      const { types } = await generate({
        Post: model(
          'Post',
          Type.Object({
            status: Type.String({ enum: ['draft', 'published'] })
          })
        )
      });

      expect(types).toContain(`status: ('draft' | 'published')`);
    });

    test('converts date formats into Date types', async () => {
      const { types } = await generate({
        Post: model(
          'Post',
          Type.Object({
            publishedAt: Type.String({ format: 'date-time' }),
            publishedOn: Type.String({ format: 'date' })
          })
        )
      });

      expect(types).toContain('publishedAt: Date');
      expect(types).toContain('publishedOn: Date');
    });

    test('adds null to nullable properties', async () => {
      const { types } = await generate({
        Post: model(
          'Post',
          Type.Object({ content: Type.String({ nullable: true }) })
        )
      });

      expect(types).toContain('string | null');
    });

    test('generates types for every resource', async () => {
      const { types } = await generate({
        Post: model('Post', Type.Object({ id: Type.Integer() })),
        User: model('User', Type.Object({ email: Type.String() }))
      });

      expect(types).toContain('export type Post = {');
      expect(types).toContain('export type User = {');
    });

    test('skips models with type generation disabled', async () => {
      const { types } = await generate({
        Post: model('Post', Type.Object({ id: Type.Integer() })),
        Draft: model('Draft', Type.Object({ id: Type.Integer() }), {
          generateTypes: false
        })
      });

      expect(types).toContain('export type Post = {');
      expect(types).not.toContain('export type Draft = {');
    });

    test('generates a query filter type for every resource', async () => {
      const { types } = await generate({
        Post: model('Post', Type.Object({ id: Type.Integer() })),
        User: model('User', Type.Object({ email: Type.String() }))
      });

      expect(types).toContain(
        `import { AggregateSelect, IResourceService, QueryFilter, QuerySort } from '@appweaver/common';`
      );
      expect(types).toContain('export type PostQuery = QueryFilter<Post>;');
      expect(types).toContain('export type UserQuery = QueryFilter<User>;');
    });

    test('generates a query sort type for every resource', async () => {
      const { types } = await generate({
        Post: model('Post', Type.Object({ id: Type.Integer() })),
        User: model('User', Type.Object({ email: Type.String() }))
      });

      expect(types).toContain(
        'export type PostSort = QuerySort<PostMultiple>;'
      );
      expect(types).toContain(
        'export type UserSort = QuerySort<UserMultiple>;'
      );
    });

    test('generates an aggregate selection type for every resource', async () => {
      const { types } = await generate({
        Post: model('Post', Type.Object({ id: Type.Integer() })),
        User: model('User', Type.Object({ email: Type.String() }))
      });

      expect(types).toContain(
        'export type PostAggregate = AggregateSelect<Post>;'
      );
      expect(types).toContain(
        'export type UserAggregate = AggregateSelect<User>;'
      );
    });

    test('generates a resource service type for every resource', async () => {
      const { types } = await generate({
        Post: model('Post', Type.Object({ id: Type.Integer() })),
        User: model('User', Type.Object({ email: Type.String() }))
      });

      expect(types).toContain(
        'export type PostResourceService = IResourceService<Post, PostMultiple, PostCreate, PostUpdate, PostQuery>;'
      );
      expect(types).toContain(
        'export type UserResourceService = IResourceService<User, UserMultiple, UserCreate, UserUpdate, UserQuery>;'
      );
    });

    test('skips the query filter type for disabled models', async () => {
      const { types } = await generate({
        Draft: model('Draft', Type.Object({ id: Type.Integer() }), {
          generateTypes: false
        })
      });

      expect(types).not.toContain('import { AggregateSelect, IResourceService');
      expect(types).not.toContain('export type DraftQuery');
      expect(types).not.toContain('export type DraftSort');
      expect(types).not.toContain('export type DraftAggregate');
      expect(types).not.toContain('export type DraftResourceService');
    });

    test('emits the query type at the end of its own model group', async () => {
      const { types } = await generate({
        Post: model('Post', Type.Object({ id: Type.Integer() })),
        User: model('User', Type.Object({ email: Type.String() }))
      });

      // The query type of a model follows the last type of that model and
      // still precedes the first type of the next model
      expect(types.indexOf('export type PostRelationInput')).toBeLessThan(
        types.indexOf('export type PostQuery')
      );
      expect(types.indexOf('export type PostQuery')).toBeLessThan(
        types.indexOf('export type PostSort')
      );
      expect(types.indexOf('export type PostSort')).toBeLessThan(
        types.indexOf('export type PostAggregate')
      );
      expect(types.indexOf('export type PostAggregate')).toBeLessThan(
        types.indexOf('export type PostResourceService')
      );
      expect(types.indexOf('export type PostResourceService')).toBeLessThan(
        types.indexOf('export type User = {')
      );
      expect(types.indexOf('export type UserRelationInput')).toBeLessThan(
        types.indexOf('export type UserQuery')
      );
    });

    test('returns 2 when the generation fails', async () => {
      const error = jest.spyOn(console, 'error').mockImplementation(() => {});

      const status = await generateTypes(
        { Post: { name: 'Post', config: {} } as any },
        typesPath,
        true
      );

      expect(status).toBe(2);
      expect(error).toHaveBeenCalledWith(
        expect.stringContaining('Types generation failed')
      );
    });

    test('prints the error details when not quiet', async () => {
      const error = jest.spyOn(console, 'error').mockImplementation(() => {});

      await generateTypes(
        { Post: { name: 'Post', config: {} } as any },
        typesPath
      );

      expect(error).toHaveBeenCalledTimes(2);
    });
  });
});
