// Generated by Appweaver. Please do not edit this file manually.

import { AggregateSelect, QueryFilter, QuerySort } from '@appweaver/common';

export type ApiKey = {
  id: number;
  key: string;
  keyHash: string;
  name?: string | null;
  description?: string | null;
  enabled: boolean;
  expiresAt?: Date | null;
  updatedAt: Date;
  createdAt: Date;
  createdById?: number | null;
};

export type ApiKeySingle = {
  id: number;
  key: string;
  name?: string | null;
  description?: string | null;
  enabled: boolean;
  expiresAt?: Date | null;
  updatedAt: Date;
  createdAt: Date;
  createdById?: number | null;
};

export type ApiKeyMultiple = {
  id: number;
  key: string;
  name?: string | null;
  description?: string | null;
  enabled: boolean;
  expiresAt?: Date | null;
  updatedAt: Date;
  createdAt: Date;
  createdById?: number | null;
};

export type ApiKeyCreate = {
  name?: string | null;
  description?: string | null;
  enabled?: boolean;
  expiresAt?: Date | null;
};

export type ApiKeyUpdate = {
  name?: string | null;
  description?: string | null;
  enabled?: boolean;
};

export type ApiKeyRelationCreate = {
  name?: string | null;
  description?: string | null;
  enabled?: boolean;
  expiresAt?: Date | null;
};

export type ApiKeyRelationUpdate = {
  id: number;
  name?: string | null;
  description?: string | null;
  enabled?: boolean;
};

export type ApiKeyRelationInput = {
  id?: number;
  name?: string | null;
  description?: string | null;
  enabled?: boolean;
  expiresAt?: Date | null;
};

export type ApiKeyQuery = QueryFilter<ApiKey>;

export type ApiKeySort = QuerySort<ApiKeyMultiple>;

export type ApiKeyAggregate = AggregateSelect<ApiKey>;

export type OneTimeToken = {
  id: number;
  tokenHash: string;
  purpose: string;
  expiresAt: Date;
  data: any;
  updatedAt: Date;
  createdAt: Date;
};

export type OneTimeTokenSingle = {
  id: number;
  tokenHash: string;
  purpose: string;
  expiresAt: Date;
  data: any;
  updatedAt: Date;
  createdAt: Date;
};

export type OneTimeTokenMultiple = {
  id: number;
  tokenHash: string;
  purpose: string;
  expiresAt: Date;
  data: any;
  updatedAt: Date;
  createdAt: Date;
};

export type OneTimeTokenCreate = {
  tokenHash: string;
  purpose: string;
  expiresAt: Date;
  data: any;
};

export type OneTimeTokenUpdate = {
  tokenHash?: string;
  purpose?: string;
  expiresAt?: Date;
  data?: any;
};

export type OneTimeTokenRelationCreate = {
  tokenHash: string;
  purpose: string;
  expiresAt: Date;
  data: any;
};

export type OneTimeTokenRelationUpdate = {
  id: number;
  tokenHash?: string;
  purpose?: string;
  expiresAt?: Date;
  data?: any;
};

export type OneTimeTokenRelationInput = {
  id?: number;
  tokenHash?: string;
  purpose?: string;
  expiresAt?: Date;
  data?: any;
};

export type OneTimeTokenQuery = QueryFilter<OneTimeToken>;

export type OneTimeTokenSort = QuerySort<OneTimeTokenMultiple>;

export type OneTimeTokenAggregate = AggregateSelect<OneTimeToken>;

export type Permission = {
  id: number;
  name: string;
  updatedAt: Date;
  createdAt: Date;
  createdById?: number | null;
};

export type PermissionSingle = {
  id: number;
  name: string;
};

export type PermissionMultiple = {
  id: number;
  name: string;
};

export type PermissionCreate = {
  name: string;
};

export type PermissionUpdate = {
  name?: string;
};

export type PermissionRelationCreate = {
  name: string;
};

export type PermissionRelationUpdate = {
  id: number;
  name?: string;
};

export type PermissionRelationInput = {
  id?: number;
  name?: string;
};

export type PermissionQuery = QueryFilter<Permission>;

export type PermissionSort = QuerySort<PermissionMultiple>;

export type PermissionAggregate = AggregateSelect<Permission>;

export type Role = {
  id: number;
  name: string;
  permissions: Array<PermissionSingle>;
  updatedAt: Date;
  createdAt: Date;
  createdById?: number | null;
};

export type RoleSingle = {
  id: number;
  name: string;
  permissions?: Array<PermissionSingle>;
};

export type RoleMultiple = {
  id: number;
  name: string;
  permissions?: Array<PermissionSingle>;
};

export type RoleCreate = {
  name: string;
  permissions: Array<
    | {
        id: number;
      }
    | number
  >;
};

export type RoleUpdate = {
  name?: string;
  permissions?: Array<
    | {
        id: number;
      }
    | number
  >;
};

export type RoleRelationCreate = {
  name: string;
};

export type RoleRelationUpdate = {
  id: number;
  name?: string;
};

export type RoleRelationInput = {
  id?: number;
  name?: string;
};

export type RoleQuery = QueryFilter<Role>;

export type RoleSort = QuerySort<RoleMultiple>;

export type RoleAggregate = AggregateSelect<Role>;

export type File = {
  id: number;
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  checksum: string;
  title?: string | null;
  description?: string | null;
  resourceField?: string | null;
  resourceName?: string | null;
  resourceId?: number | null;
  url: string;
  updatedAt: Date;
  createdAt: Date;
  createdById?: number | null;
};

export type FileSingle = {
  id: number;
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  checksum: string;
  title?: string | null;
  description?: string | null;
  url: string;
  updatedAt: Date;
  createdAt: Date;
  createdById?: number | null;
};

export type FileMultiple = {
  id: number;
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  checksum: string;
  title?: string | null;
  description?: string | null;
  url: string;
  updatedAt: Date;
  createdAt: Date;
  createdById?: number | null;
};

export type FileCreate = {
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  checksum: string;
  title?: string | null;
  description?: string | null;
};

export type FileUpdate = {
  name?: string;
  originalName?: string;
  mimeType?: string;
  sizeBytes?: number;
  checksum?: string;
  title?: string | null;
  description?: string | null;
};

export type FileRelationCreate = {
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  checksum: string;
  title?: string | null;
  description?: string | null;
};

export type FileRelationUpdate = {
  id: number;
  name?: string;
  originalName?: string;
  mimeType?: string;
  sizeBytes?: number;
  checksum?: string;
  title?: string | null;
  description?: string | null;
};

export type FileRelationInput = {
  id?: number;
  name?: string;
  originalName?: string;
  mimeType?: string;
  sizeBytes?: number;
  checksum?: string;
  title?: string | null;
  description?: string | null;
};

export type FileQuery = QueryFilter<File>;

export type FileSort = QuerySort<FileMultiple>;

export type FileAggregate = AggregateSelect<File>;
