// Generated by Appweaver. Please do not edit this file manually.

export type File = {
  id: number;
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  title?: string | null;
  description?: string | null;
  resourceField?: string | null;
  resourceName?: string | null;
  resourceId?: number | null;
  createdAt: Date;
  updatedAt: Date;
  createdById?: number | null;
};

export type FileSingle = {
  id: number;
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  title?: string | null;
  description?: string | null;
  createdAt: Date;
  updatedAt: Date;
  createdById?: number | null;
};

export type FileMultiple = {
  id: number;
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  title?: string | null;
  description?: string | null;
  createdAt: Date;
  updatedAt: Date;
  createdById?: number | null;
};

export type FileCreate = {
  name: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  title?: string | null;
  description?: string | null;
};

export type FileUpdate = {
  name?: string;
  originalName?: string;
  mimeType?: string;
  sizeBytes?: number;
  title?: string | null;
  description?: string | null;
};

export type Role = {
  id: number;
  name: string;
  permissions: Array<PermissionSingle>;
  createdAt: Date;
  updatedAt: Date;
  createdById?: number | null;
};

export type RoleSingle = {
  id: number;
  name: string;
  permissions: Array<PermissionSingle>;
};

export type RoleMultiple = {
  id: number;
  name: string;
  permissions: Array<PermissionSingle>;
};

export type RoleCreate = {
  name: string;
  permissions:
    | Array<{
        id: number;
      }>
    | Array<number>;
};

export type RoleUpdate = {
  name?: string;
  permissions?:
    | Array<{
        id: number;
      }>
    | Array<number>;
};

export type Permission = {
  id: number;
  name: string;
  createdAt: Date;
  updatedAt: Date;
  createdById?: number | null;
};

export type PermissionSingle = {
  id: number;
  name: string;
};

export type PermissionMultiple = {
  id: number;
  name: string;
};

export type PermissionCreate = {
  name: string;
};

export type PermissionUpdate = {
  name?: string;
};
